### ISSUE TITLE
fxHide.gt-sm stopped working with beta 21

### ISSUE THREAD

**Issue by alexfung888** [angular/flex-layout#930] opened 2018-12-17 08:18 UTC
# Bug Report

#### What is the expected behavior?
The following should be visible on md/lg/xl
```html
  <div fxHide [fxShow.gt-sm]='true'>
    gt-sm
  </div>
```

#### What is the current behavior?
It is never visible.

#### What are the steps to reproduce?

fail in beta 21:
https://stackblitz.com/edit/angular-flex-layout-seed-b21

OK in beta 18 and 19 (only change is in package.json):
https://stackblitz.com/edit/angular-flex-layout-seed-b18
https://stackblitz.com/edit/angular-flex-layout-seed-b19

resize windows. It will show the current size (xs/sm/md/lg/xl).
With beta 18/19, it also shows gt-sm/lt-md.
With beta 21, it never shows gt-sm/lt-md.

The fxShow/fxHide are in the template HTML of app.component.ts

I also followed 
https://github.com/angular/flex-layout/wiki/BreakPoints
to add gt-sm as if it were custom breakpoint code, and made no difference.
This code is added at lines 12-21 of `app.component.ts`

#### What is the use-case or motivation for changing an existing behavior?
normal use of fxHide

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular 7.1.3
material 7.1.1
OS w10 64 bit
Chrome 71.0.3578.98

**Comment by CaerusKaru** [comment] 2018-12-17 10:20
Duplicate of #915

**Closed by CaerusKaru** 2018-12-17 10:20 UTC

**Comment by alexfung888** [comment] 2018-12-17 10:41
Oops. I only searched for open issues and the closed one escaped me. 
I failed to use 
```
"angular/flex-layout": "7.0.0-beta.21",
```
either, so I have to wait for the next beta release.

**Comment by alexfung888** [comment] 2018-12-20 12:15
fixed in beta 22.
