### ISSUE TITLE
ngclass with breakpoints doesn't remove class once added.

### ISSUE THREAD

**Issue by lokeshdaiya** [angular/flex-layout#967] opened 2019-01-03 10:24 UTC
# Bug Report

#### What is the expected behavior?

When  `ngClass` is used with breakpoint then it should add specified class for that breakpoint and remove once breakpoint changes

for below example
`
[ngClass.xs] = "'test'"
`

it should add `test` class only for xs breakpoint . If breackpoint changes then it should remove that class.
 

#### What is the current behavior?

ngClass is not removing class when screen size changes.

#### What are the steps to reproduce?
Have a look on below stackblitz.
https://stackblitz.com/edit/angular-jau3sq

Try to resize the screen and observe behavior. You will notice `test` class is not getting removed when you go from xs to larger size.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7+
flex-layout 7.0.0-beta22

#### Is there anything else we should know?

It was working fine till 7.0.0-beta.19

**Comment by CaerusKaru** [comment] 2019-01-03 17:30
I feel like this is a duplicate of #947. Can you pull the latest nightly branch (`npm i angular/flex-layout-builds`, no `@`) and test to see if it's resolved?

**Comment by CaerusKaru** [comment] 2019-01-11 15:33
Closing with no response. I think this has been patched in beta 23. If this isn’t the case, we can reopen this.

**Closed by CaerusKaru** 2019-01-11 15:33 UTC
Labels: can be closed?

**Comment by mhosman** [comment] 2019-01-14 06:06
This is still failing in latest version

**Comment by lincolngup** [comment] 2019-02-19 21:20
It's not working in 7.0.0-beta.23 for me, either. With the code below, the class `document-margin ` is correctly added as the window size increases past sm (starting with an xs or sm window). But the class is not removed as the window size is then reduced to sm and xs screens.
`ngClass.gt-sm="document-margin"`

**Comment by sebastiangug** [comment] 2019-04-09 14:03
idk why this was closed -- this still does NOT work.
