### ISSUE TITLE
AOT Builds fail with Angular 5.2.7

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/flex-layout#638] opened 2018-03-03 19:52 UTC
Delete `package-lock.json` and run `npm i && npm run lib:build:aot`
See failures in terminal.

> Works fine in Angular 5.2.6.

**Comment by CaerusKaru** [comment] 2018-03-04 00:13
The issue is actually that the build doesn't work with TypeScript 2.7.x, the PR referenced above locks the version back to 2.6.x

**Comment by CaerusKaru** [comment] 2018-03-04 15:25
Pretty simple: https://github.com/angular/angular/pull/22097 hasn't been merged yet

**Comment by CaerusKaru** [comment] 2018-03-04 15:47
Closed by 95a6e83

**Closed by CaerusKaru** 2018-03-04 15:47 UTC
Labels: P1: urgent, build, has pr
