### ISSUE TITLE
Bug: angular Ivy failed: ERROR in EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by splincode** [angular/flex-layout#1104] opened 2019-07-24 08:33 UTC
# Bug Report

#### What is the expected behavior?

Success build Angular 8 with Ivy

#### What is the current behavior?

When I enable Ivy we expected errors

```ts
ERROR in EISDIR: illegal operation on a directory, read
i ｢wdm｣: Failed to compile.
    
    ERROR in node_modules/@angular/flex-layout/extended/typings/class/class.d.ts(30,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).
    node_modules/@angular/flex-layout/extended/typings/img-src/img-src.d.ts(38,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).
    node_modules/@angular/flex-layout/flex/typings/flex/flex.d.ts(50,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).
    node_modules/@angular/flex-layout/grid/typings/align-columns/align-columns.d.ts(28,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).
    node_modules/@angular/flex-layout/grid/typings/align-rows/align-rows.d.ts(28,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).
    node_modules/@angular/flex-layout/grid/typings/areas/areas.d.ts(31,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).
    node_modules/@angular/flex-layout/grid/typings/auto/auto.d.ts(31,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).
    node_modules/@angular/flex-layout/grid/typings/columns/columns.d.ts(32,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).
    node_modules/@angular/flex-layout/grid/typings/gap/gap.d.ts(31,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).
    node_modules/@angular/flex-layout/grid/typings/rows/rows.d.ts(32,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).

```

#### What are the steps to reproduce?
Providing a StackBlitz (or similar) is the *best* way to get the team to see your issue.

*  [StackBlitz starter](https://goo.gl/y38GUZ) using latest `npm` nightly release: 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

```
        "@angular-ru/logger": "^1.11.0",
        "@angular/animations": "^8.1.2",
        "@angular/cdk": "^8.1.1",
        "@angular/common": "^8.1.2",
        "@angular/compiler": "^8.1.2",
        "@angular/core": "^8.1.2",
        "@angular/flex-layout": "8.0.0-beta.26",
        "@angular/forms": "^8.1.2",
        "@angular/material": "^8.1.1",
        "@angular/platform-browser": "^8.1.2",
        "@angular/platform-browser-dynamic": "^8.1.2",
        "@angular/router": "^8.1.2",
        "core-js": "^3.1.4",
        "hammerjs": "^2.0.8",
        "rxjs": "^6.5.1",
        "zone.js": "~0.9.1"
```

**Comment by CaerusKaru** [comment] 2019-07-25 14:19
Duplicate of #1105

**Closed by CaerusKaru** 2019-07-25 14:19 UTC
