### ISSUE TITLE
Layout is not responsive when reducing browser window size 

### ISSUE THREAD

**Issue by dereklin** [angular/flex-layout#203] opened 2017-03-02 22:27 UTC
Here is my plunk: https://plnkr.co/edit/nmbNHCyYpcqVf6W358J4?p=preview

Run it in a small size browser window (Chrome), expand the browser window gradually, the layout expands as expected.  Now reduce the browser window size, it's no longer responsive.

How can I make this work properly?

**Comment by ThomasBurleson** [comment] 2017-03-02 23:00
General discussion and how-to questions should be posted to the community forum areas:

*  [Google Groups](https://groups.google.com/forum/#!forum/angular-flex-layout)
*  [Gitter Channel](https://gitter.im/angular/flex-layout)

Closing this issue as 'invalid'. Thank you.

**Closed by ThomasBurleson** 2017-03-02 23:00 UTC

**Comment by dereklin** [comment] 2017-03-02 23:05
This is not a bug?

**Comment by ThomasBurleson** [comment] 2017-03-02 23:10
@dereklin - I am unable to reproduce an issue on Chrome. On Safari, it looks like the Column bug is at-play again. And while we already have an issue for that bug, I think your layout itself is too complex... hence my request that you get the community to help.
