### ISSUE TITLE
Cannot use fxShow with custom breakpoints

### ISSUE THREAD

**Issue by wilhelmhb** [angular/flex-layout#510] opened 2017-11-21 16:59 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
With custom breakpoints, we should be able to show/hide elements when one of these breakpoints is used, while still using the default breakpoints.

#### What is the current behavior?
Hiding works fine, showing doesn't. Nothing work for default breakpoints.

#### What are the steps to reproduce?
A Plunker is available [here](https://plnkr.co/edit/sDMETYIbNlYd46Qyhvak?p=preview).
See also [this question on StackOverFlow](https://stackoverflow.com/questions/47399796/show-hide-using-custom-breakpoints-and-angular-flex-layout)

#### What is the use-case or motivation for changing an existing behavior?
Have the expected behavior.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Tested with Angular 5.0.2 + Windows10 + Typescript2.3.4 + Firefox and Chrome
Tested with the latest beta of flex-layout and the nightly build.

#### Is there anything else we should know?
[This part of the documentation](https://github.com/angular/flex-layout/wiki/BreakPoints#custom-breakpoints-and-directives) seems to be out-dated: the constructor of the custom directive doesn't match the constructor of the ShowHideDirective.

**Comment by CaerusKaru** [comment] 2018-01-15 06:25
I'm marking this as a duplicate of #518 since that seems like a more concise issue, and I'll add a note about updating the docs on that issue.

**Closed by CaerusKaru** 2018-01-15 06:25 UTC
Labels: P3: important
