### ISSUE TITLE
Using responsive API based on container width instead of viewport

### ISSUE THREAD

**Issue by aaronte** [angular/flex-layout#589] opened 2018-01-30 01:09 UTC
#### Bug, feature request, or proposal:
• Question

#### What is the expected behavior?
• Wondering whether the responsive api (i.e. `gt-xs`, `lt-sm`, etc) can be dependent on the element container instead of the whole browser viewport.

#### What is the current behavior?
• Currently, the responsive api only responds to the width of the browser viewport. I think it will be nice if there was a way to make elements change their layouts based on the width of it's container. Not sure if this exists yet since I'm unable to find it in any docs.

**Comment by intellix** [comment] 2018-01-30 01:24
Dupe of https://github.com/angular/flex-layout/issues/218

**Comment by CaerusKaru** [comment] 2018-01-30 02:53
Closing as duplicate of #218, but see #512 for tracking progress on CSS Grid.

**Closed by CaerusKaru** 2018-01-30 02:53 UTC
