### ISSUE TITLE
Bad NPM Install Warning

### ISSUE THREAD

**Issue by pragmadaegon** [angular/flex-layout#475] opened 2017-11-01 15:20 UTC
#### Bug
I am getting the following warnings while running npm install:

npm WARN @angular/flex-layout@2.0.0-beta.10 requires a peer of @angular/core@0.0.0-NG but none was installed.
npm WARN @angular/flex-layout@2.0.0-beta.10 requires a peer of @angular/common@0.0.0-NG but none was installed. 

with the following package.json: 

```
{
  "name": "web",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.4.4",
    "@angular/cdk": "2.0.0-beta.12",
    "@angular/common": "^4.4.4",
    "@angular/compiler": "^4.4.4",
    "@angular/core": "^4.4.4",
    "@angular/flex-layout": "2.0.0-beta.10",
    "@angular/forms": "^4.4.4",
    "@angular/http": "^4.4.4",
    "@angular/material": "2.0.0-beta.12",
    "@angular/platform-browser": "^4.4.4",
    "@angular/platform-browser-dynamic": "^4.4.4",
    "@angular/router": "^4.4.4",
    "angular2-notifications": "0.7.7",
    "core-js": "^2.4.1",
    "ng2-dragula": "^1.5.0",
    "rxjs": "^5.4.2",
    "spinkit": "^1.2.5",
    "web-animations-js": "^2.3.1",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.4.9",
    "@angular/compiler-cli": "^4.4.4",
    "@angular/language-service": "^4.4.4",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.1.1",
    "hammerjs": "^2.0.8",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "~2.3.3"
  }
}
```

#### What is the expected behavior?
Considering I am using the same version of angular core and common as beta.10, I would expect no warning. If there are dependency issues however, I would expect the correct component and version to be displayed.

**Comment by Splaktar** [comment] 2017-11-01 19:55
I can confirm that I am seeing this as well with Angular `5.0.0` and the CLI `1.5.0`.

**Comment by codepj** [comment] 2017-11-01 21:03
I see this in both angular cli 1.5.0 and 1.4.9

**Comment by qaznine** [comment] 2017-11-02 03:20
+1

**Comment by bOOm-X** [comment] 2017-11-02 12:30
The peer dependencies section of the package.json (retrieved from the extracted npm package) seems quite bad : 
`"peerDependencies": {
    "@angular/core": "0.0.0-NG",
    "@angular/common": "0.0.0-NG"
  }`
The rxjs dependencies is missing (it is neither in the dependencies)
The version should be at least 5.5.0 (from the package.json of the sources)

I had the version 5.4.3, and so no warning during the install step,
but at the compilation I got an error:
`ERROR in ./node_modules/@angular/flex-layout/esm5/flex-layout.es5.js
Module not found: Error: Can't resolve 'rxjs/operators' in 'D:\myProjects\customAudience\identification\hadoop-crm-matching\customaudience-app\src\main\webapp\node_modules\@angular\flex-layout\esm5'
 @ ./node_modules/@angular/flex-layout/esm5/flex-layout.es5.js 10:0-45`

After bumping the rxjs version to 5.5.2, everything is OK

**Comment by ThomasBurleson** [comment] 2017-11-04 09:44
Duplicate of #479.

**Closed by ThomasBurleson** 2017-11-04 09:44 UTC
