### ISSUE TITLE
fxFlex sets both min and max width to element that should grow and shrink

### ISSUE THREAD

**Issue by jbojcic1** [angular/flex-layout#737] opened 2018-05-09 10:46 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When I set fxFlex="1 1 220px" there shouldn't be min-width or max-width set. 

#### What is the current behavior?
min-width and max-width are both set to flex basis value and element cannot grow nor shrink.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-flex-layout-seed-y2f5nz

#### Is there anything else we should know?
I am not even sure why min-width or max-width is needed but even according to https://github.com/angular/flex-layout/wiki/fxFlex-API#additional-fxflex-stylings, min-width should be set only for grow and max-width only for shrink. It doesn't say any additional styles should be applied if you have both.

**Comment by CaerusKaru** [comment] 2018-05-09 14:37
Duplicate of #438

**Closed by CaerusKaru** 2018-05-09 14:37 UTC
