### ISSUE TITLE
es2015/es6 directive support

### ISSUE THREAD

**Issue by epelc** [angular/flex-layout#953] opened 2018-12-21 19:51 UTC
# Bug Report

#### What is the expected behavior?
The layout directive(and I think others like flex directive) do not work when targeting es6 in your tsconfig. Everything works fine when targeting es5. I also suspect this might affect the custom breakpoint directives because they are also subclasses.

#### What is the current behavior?

You get an error that `init` is not a method on undefined because I assume the constructor arguments are not injected on subclasses.
![image](https://user-images.githubusercontent.com/5204642/50360807-50e07580-052f-11e9-90ab-ba59e643b511.png)
![image](https://user-images.githubusercontent.com/5204642/50360815-5b027400-052f-11e9-8311-784cc76bbc2c.png)
>core.js:18374 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'init' of undefined

Basically none of the arguments are injected.

#### What are the steps to reproduce?
Providing a StackBlitz (or similar) is the *best* way to get the team to see your issue.

*  [StackBlitz starter](https://goo.gl/y38GUZ) using latest `npm` nightly release: 

Change the value of `"target"` in tsconfig.js to `es6`.

#### What is the use-case or motivation for changing an existing behavior?
Compiling smaller libs with newer/faster es6

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
7.0 beta 22

#### Is there anything else we should know?

Angular material had the same issue and it was very finicky but has finally been fixed in https://github.com/angular/material2/pull/13834. It is really due to an underlying issue with angular itself which ivy is supposed to fix but there is an outstanding PR to fix it in the current renderer.

@devversion has dealt with fixing this heavily perhaps he could advise best course of action? There were a lot of pitfalls during the fixes for angular material so hopefully he has some input on the final fix.

**Comment by CaerusKaru** [comment] 2018-12-21 19:52
Duplicate of #950

**Closed by CaerusKaru** 2018-12-21 19:52 UTC
