### ISSUE TITLE
wiki link broken

### ISSUE THREAD

**Issue by buddudevelopers** [angular/flex-layout#1345] opened 2021-05-22 10:58 UTC
# Bug Report
wiki link https://github.com/angular/flex-layout/wiki/gdAlignColumns-API cant be accessed.
#### What is the expected behavior?
 expect to read the documentation

#### What is the current behavior?
redirects to https://github.com/angular/flex-layout/wiki

**Comment by CaerusKaru** [comment] 2021-05-22 15:57
Duplicate of #1026

**Closed by CaerusKaru** 2021-05-22 15:57 UTC
