### ISSUE TITLE
fxShow breaks flex layout by adding a "display: initial" inline property 

### ISSUE THREAD

**Issue by ericjeker** [angular/flex-layout#1255] opened 2020-05-15 05:33 UTC
# Bug Report

#### What is the expected behavior?
When using fxShow or fxHide, I want my design to remain the same.

#### What is the current behavior?
When using fxShow or fxHide, the design is broken because the directive add a `display: initial` property inline on the element which overwrites the previously set `display` property.

#### What are the steps to reproduce?
As you can see in this example, the "Age" column is aligned at the top of the cell because I added a fxHide and fxShow directive in it. It should be aligned center as I previously defined a flex display and `align-items: center` property.

A simple fix would be to use `display: inherit` instead.

Note: the Age column appear in Desktop mode only.

https://stackblitz.com/edit/angular-3dcttj

#### What is the use-case or motivation for changing an existing behavior?
Make it work properly so it doesn't break the existing design.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 9.1.7, Material 9.2.3, tested on Firefox.

#### Is there anything else we should know?
Nop, thanks.

**Comment by CaerusKaru** [comment] 2020-05-15 05:34
Duplicate of #1250

**Closed by CaerusKaru** 2020-05-15 05:34 UTC
