### ISSUE TITLE
Media observable is not triggering in Firefox print preview

### ISSUE THREAD

**Issue by aciccarello** [angular/flex-layout#615] opened 2018-02-13 21:31 UTC
#### Bug:
The media observable is not firing for a custom breakpoint in the Firefox print preview.

#### What is the expected behavior?
When printing, both Chrome and Firefox should be updated by the media observable.

#### What is the current behavior?
Chrome is updating on the media observable while Firefox is not.

#### What are the steps to reproduce?

View this [StackBlitz](https://stackblitz.com/edit/ajc-angular-flex-layout-print-media?file=app%2Fcustom-breakpoints.ts) and open a print preview (it's best to open the app in another page). Chrome will show "Print: true" while Firefox will show "Print: false" indicating that the media query did not update the print view.

#### What is the use-case or motivation for changing an existing behavior?
The media observable should function the same across browsers. Print media is an example of custom breakpoints in the library.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.1.1
Chrome Version 66.0.3346.0 (Official Build) canary (64-bit)
Firefox 58.0.1 (64-bit)
Windows 7 64-bit

**Comment by CaerusKaru** [comment] 2018-12-19 23:54
I'm going to say that this is not a bug with our implementation, and likely a bug with the Firefox implementation. One of two things is probably happening: 1) Firefox doesn't fire the print event in time for the print preview dialog to be rendered (likely), 2) there's a bug preventing matchMedia from picking up print events (unlikely).

In either case, this isn't a bug with our library. Unless there's evidence provided to the contrary, I'm closing this issue. We can reopen if evidence is given.

**Closed by CaerusKaru** 2018-12-19 23:54 UTC
Labels: bug, needs: investigation, print
