### ISSUE TITLE
[docs] fxLayoutGap not usable in combination with wrap and breakpoints

### ISSUE THREAD

**Issue by GoGoris** [angular/flex-layout#753] opened 2018-05-25 07:02 UTC
#### Bug, feature request, or proposal:
It would be nice if fxLayoutGap could be improved (or an alternative could be made) to make it work in combination with flexLayout="row wrap" without custom CSS.

#### What is the expected behavior?
Each line fill the complete width.

#### What is the current behavior?
The layout gap at the end of the line is not accounted for. Each diff except the last one has an offset on the right.

#### What are the steps to reproduce?
Providing a StackBlitz (or similar) is the *best* way to get the team to see your issue.

https://stackblitz.com/edit/flexlayoutgap-breakpoints

#### What is the use-case or motivation for changing an existing behavior?
I know about the fxFlex="calc(100% - gap px)" workaround but writing this for each element and each breakpoint is a lot of work.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.0.x
@angular/flex-layout 6.0.0-beta.15

#### Is there anything else we should know?

I used the following scss as an alternative to fxLayoutGap:

```sass
$md-layout-gap: 24px;

[fxLayout].md-layout-gap {
    margin-right: (-$md-layout-gap) !important;

    [fxFlex] {
        margin-right: $md-layout-gap !important;
    }
}
```
I am sure this can be done a lot nicer if this was implemented in flexLayout (no !important, layoutGap as a property)

**Comment by CaerusKaru** [comment] 2018-05-30 06:55
Did you try using `fxLayoutGap` in grid mode?

E.g. `fxLayoutGap=“10px grid”`

**Comment by GoGoris** [comment] 2018-05-30 10:26
Thank you, is this a new feature? I could not find this in any of the documentation.
The horizontal layout gap is correct when I use `fxLayoutGap=“24px grid”`, but when the rows are wrapped there is a vertical layout gap that should not be there.

**Comment by GoGoris** [comment] 2018-05-30 11:11
I tried to reproduce it in my stackblitz example but there it adds padding instead of margin. I have no idea why it behaves this way in stackblitz. The only difference I can think of is that I don't have angular material included.

**Comment by CaerusKaru** [comment] 2018-06-04 16:45
It actually adds padding and margin. It's the only effective way to achieve what you're looking for while maintaining expected behavior across use cases.

I see now that what you really want is grid mode with no vertical offset, which is an interesting use case (basically the grid without the gutter). I'll mark this as a feature request, but it isn't likely to be a high priority for now.

**Comment by KatzeKahn** [comment] 2018-07-26 01:07
Please add the "grid-mode" behavior to the documentation since it's an essential feature! Thx :)

**Comment by stoto34** [comment] 2018-09-04 16:05
I'm using fxLayout (row wrap) and fxLayoutGap (20px grid)  and I have a padding on the last element of my row. How can I avoid this padding ?

**Comment by CaerusKaru** [comment] 2018-12-07 05:33
I'm going to mark this as a docs issue since I think the grid mode properly configured fixes this (if not, we can revisit this).

**Comment by CaerusKaru** [comment] 2018-12-28 04:58
I've updated the page by adding a section [here](https://github.com/angular/flex-layout/wiki/fxLayoutGap-API#grid-mode). I've also made mention of the secondary option in the first paragraph. I hope this is satisfactory and I apologize for the delay in getting this done. If anyone has any other suggestions, I'd be happy to incorporate them as well. In the meantime, without argument I'm closing this issue.

**Closed by CaerusKaru** 2018-12-28 04:58 UTC
Labels: docs

**Comment by BizzottoClaudio** [comment] 2019-08-02 16:26
> I'm going to mark this as a docs issue since I think the grid mode properly configured fixes this (if not, we can revisit this).

Actually it would be great if the library could do it by itself: removing the padding/margin for the last element of each row.
In [this example](https://stackblitz.com/edit/lacolaco-angular-flex-layout-example-t7raqx
) the drawback is clear: i have a father-container with `fixed width` and some children (also with fixed width) that are `row wrap` by the father with some `gap`: in the stackblitz toggle the threePerRow property to see the differences.
I would calculate the width of the father just by doing `(child_width + gap) * desired_children_per_row) - gap`, but by doing so i'll get `desired_children_per_row - 1` in each row, because the calculated width do not account for the padding of the last element of each row.
Just using the `fxLayoutGap="20px grid"` does not solve the problem without further changes to the code.
