### ISSUE TITLE
fxLayout="row-reverse" not rendering correctly when nested inside a fxLayout="row"

### ISSUE THREAD

**Issue by adrian-heath** [angular/flex-layout#78] opened 2016-12-31 09:49 UTC
The use of row-reverse is not being rendered correctly as shown in the below HTML for the nested flex container which shows flex-direction:row.  

*  Browser is Chrome, 
*  flex-layout v2.0.0-beta.1. 

Changing the outer container to also be row-reverse still doesn't correct the inner containers direction.

```html
<div _ngcontent-gew-112="" 
        class="flex-container bottom-margin" 
        fxlayout="row-reverse" 
        fxlayoutalign="center center" 
        ng-reflect-layout="row-reverse" 
        ng-reflect-align="center center" 
        style="box-sizing: border-box; 
                    max-height: 100%; 
                    display: flex; 
                    flex-direction: row; 
                    justify-content: center; 
                    align-items: center; 
                    align-content: center;">
```

**Comment by ThomasBurleson** [comment] 2016-12-31 15:42
Issues are considered invalid without a working Plunkr or CodePen demo. 

---- 

Also here are some important guidelines for investigating a Layout issue:

* The Layout API is case-sensitive
  *  `fxlayout` is not valid
  *  `fxLayout` is valid
*  If you cannot get Flex-Layout to work with an example, try to manually use CSS flexbox stylings. If that still does not work to achieve your goals, then Flex-Layout is <u>**not**</u> the issue.
*  If hand-crafted CSS resolves the issue, but Flex-Layout does not then we **definitely** have a bug in this repository.

#### Templates 

* [Plunkr Template](https://plnkr.co/edit/h8hzyoEyqdCXmTBA7DfK?p=info)
* [Plunkr Template with Material2](https://plnkr.co/edit/rkF70n7X4Yv8WmP4Thu5?p=preview)
* [CodePen Template]() - not yet available.

**Comment by adrian-heath** [comment] 2017-01-01 12:08
Here is a Plunkr

https://plnkr.co/edit/JcQRiKbeU0uB3m91RMHo?p=preview

The inner layout is set to row-reverse but always shows as row irrespecitive of the outer containers layout

**Comment by ThomasBurleson** [comment] 2017-01-01 16:01
@adrian-heath - This is a great Plnkr. Thank you very much!

---- 

You will laugh > the issue is simply and easy to stumble into. Your version is using binding to expression that is actually a static value:

Yours:

```html
<div [fxLayout]="row-reverse" class="colored box" >
```

Corrected

```html
<div fxLayout="row-reverse" class="colored box" >
```

**Comment by ThomasBurleson** [comment] 2017-01-01 16:02
Closing as not-an-issue.

**Closed by ThomasBurleson** 2017-01-01 16:02 UTC

**Comment by d3viant0ne** [comment] 2017-01-01 16:07
I've done that more than once myself.

**Comment by ThomasBurleson** [comment] 2017-01-01 16:45
Me too!

**Comment by adrian-heath** [comment] 2017-01-04 09:52
Turns out whilst I thought I had recreated as it was in my code, I'd missed something which does break row-reverse.  I added fxLayoutAlign="center center" to the inner container and row-reverse was broken again.  I'll create a separate issue since this one is now closed
