### ISSUE TITLE
Flexlayout loading desktop view while loading website in Mobile

### ISSUE THREAD

**Issue by cstrd** [angular/flex-layout#803] opened 2018-07-14 16:05 UTC
# Bug Report

I'm opening my website(https://therightdoctors.com - site built using Angular6, Angular Material design, Flex layout, CSS) on mobile, while loading site first it is displaying the desktop view design and later it is displaying mobile view design. At the time of loading Flex layout, responsive styles are not working. please check below screenshot of how it is displaying 

![screenshot_20180714-145556](https://user-images.githubusercontent.com/11487982/42726163-9ceada38-87ad-11e8-9298-2764f4abb02e.png)

Please check the screen below of after loading

![capture12](https://user-images.githubusercontent.com/11487982/42726159-87c43e1a-87ad-11e8-9db6-31675ab358ae.PNG)

**Comment by julianobrasil** [comment] 2018-07-14 20:40
As @angular/flex-layout is based on javascript and you're loading a lot of external resources, if I had to pick a reason, I'd say some javascript activity is blocking flex-layout in such a way it cannot switch the layout from desktop to mobile. This just a feeling and can be completely wrong.

If so and you're using the responsive directives, maybe you can try out using [`@angular/cdk ` layout](https://material.angular.io/cdk/layout/overview) like this:

```html
<div [fxLayout]="_isHandset ? 'column' : 'row'"></div>
```

```ts
constructor(private _breakpointObserver: BreakpointObserver) {
    this._breakpointObserver
      .observe([Breakpoints.Handset, Breakpoints.Tablet])
      .subscribe((result: BreakpointState) => {
        this._isHandset = result.matches;
      });
  }
```

As I didn't look inside `@angular/flex-layout` code, this can be a completely non-sense suggestion (maybe they already do it).

Another approach would be using pure css instead of `@angular/flex-layout` as suggested at https://github.com/angular/flex-layout/wiki/Performance-Considerations

**Comment by cstrd** [comment] 2018-07-15 14:36
HI, julianobrasil ,
Thanks for replying, as you told I tried to solve (hide /show) layout based on the viewport, but still, it's not applying flex layout at the first-page load in mobile view,... below is my code .. please check and suggest some solution .......

```
nav.ts --
 constructor(private _breakpointObserver: BreakpointObserver,private route:ActivatedRoute) {
    this._breakpointObserver
      .observe([Breakpoints.Handset, Breakpoints.Tablet])
      .subscribe((result: BreakpointState) => {
        this._isHandset = result.matches;
      });
  }
```

tav.componenet.html 

`

<div class="top_line wow fadeIn animated "
     style="border-bottom:2px solid #d9534f;visibility: visible; animation-name: fadeIn;" fxHide fxShow.gt-sm
     xmlns="http://www.w3.org/1999/html">
  <div class="container relative">
    <div fxLayout="row">
      <div fxFlex="20" class="pull-left">
        <img src="/assets/new-home-page/single/images/logo.jpg" alt="TheRightDoctors Logo">
        <div class="pre_alpha">Pre Alpha</div>
      </div>


      <div fxFlex="60" class="pull-4" style="vertical-align: center" fxFlexAlign="center center">
        <div class="insight_frm" style=""><b>Insights from the World's Best Medical Minds </b></div>
      </div>

      <div fxFlex="20" class="pull-right nne">
        <a [routerLink]="['/showcase']"><img src="/assets/new-home-page/single/images/nine.png" alt="nine"></a>
      </div>
    </div>
  </div>
</div>
<div class="top_line wow fadeIn animated "
     style="border-bottom:2px solid #d9534f;visibility: visible; animation-name: fadeIn;" fxShow="false"
     [fxShow.lt-md]="_isHandset">

  <div class="container relative">
    <div class="pull-left">
      <img src="/assets/new-home-page/single/images/logo.jpg" alt="TheRightDoctors Logo">

      <span *ngIf="this.home==='Home'"
            style="color:#333;margin-top: 20px;font-size:18px;margin-top:27px;position:absolute;padding-left:11px;">
        <a [routerLink]="['/']">Home</a>
      </span>
      <span *ngIf="this.home==='The-Interview'"
            style="color:#333;margin-top: 20px;font-size:18px;margin-top:27px;position:absolute;padding-left:11px;">
        <a [routerLink]="['/the-interview']">The Interview</a>
      </span>
      <span *ngIf="this.home=='The-Speakers'"
            style="color:#333;margin-top: 20px;font-size:18px;margin-top:27px;position:absolute;padding-left:11px;">
        <a [routerLink]="['/the-speakers']">The Speakers</a>
      </span>
      <span *ngIf="this.home==='One-More-Thing'"
            style="color:#333;margin-top: 20px;font-size:18px;margin-top:27px;position:absolute;padding-left:11px;">
        <a [routerLink]="['/one-more-thing']">One More Thing</a>
      </span>
      <span *ngIf="this.home==='In-Conversation'"
            style="color:#333;margin-top: 20px;font-size:18px;margin-top:27px;position:absolute;padding-left:11px;">
        <a [routerLink]="['/in-conversation']">In Conversation</a>
      </span>
      <span *ngIf="((this.home==='Specials'))"
            style="color:#333;margin-top: 20px;font-size:18px;margin-top:27px;position:absolute;padding-left:11px;">
        <a [routerLink]="['/specials']">Specials</a>
      </span>
      <span *ngIf="((this.home==='Dr-Hk-Chopra'))"
            style="color:#333;margin-top: 20px;font-size:18px;margin-top:27px;position:absolute;padding-left:11px;">
        <a [routerLink]="['/Dr-Hk-Chopra-Sr-Cardiologist-Moolchand-Hospital-Delhi']"> Dr Hk Chopra</a>
      </span>
      <span *ngIf="((this.home==='Dr-Manish-Verma'))"
            style="color:#333;margin-top: 20px;font-size:18px;margin-top:27px;position:absolute;padding-left:11px;">
        <a [routerLink]="['/Dr-Manish-Verma-Sr-Cardiologist-Fortis-Hospital-Bangalore']">Dr Manish Verma</a>
      </span>
      <span *ngIf="((this.home==='Dr-Rishi-Jain'))"
            style="color:#333;margin-top: 20px;font-size:18px;margin-top:27px;position:absolute;padding-left:11px;">
        <a [routerLink]="['/Dr-Rishi-Jain-Sr-Cardiologist']">Dr Rishi Jain</a>
      </span>
      <span *ngIf="this.home==='Revolution-Talk'"
            style="color:#333;margin-top: 20px;font-size:18px;margin-top:27px;position:absolute;padding-left:11px;">
        <a [routerLink]="['/revolution-talk']">Revolution Talk</a>
      </span>
      <span *ngIf="this.home==='Synapse'"
            style="color:#333;margin-top: 20px;font-size:18px;margin-top:27px;position:absolute;padding-left:11px;">
        <a [routerLink]="['/synapse']">Synapse</a>
      </span>
      <span *ngIf="this.home==='Live'"
            style="color:#333;margin-top: 20px;font-size:18px;margin-top:27px;position:absolute;padding-left:11px;">
        <a [routerLink]="['/the-interview']">Live</a>
      </span>
      <span *ngIf="this.home==='Live-Cases'"
            style="color:#333;margin-top: 20px;font-size:18px;margin-top:27px;position:absolute;padding-left:11px;">
        <a [routerLink]="['/csinic-2016/live_cases']">Live Cases</a>
      </span>

      <span *ngIf="this.category==='the-interview'"
            style="color:#333;margin-top: 20px;font-size:18px;margin-top:27px;position:absolute;padding-left:11px;">
        <a [routerLink]="['/the-interview']">The Interview</a>
      </span>

      <span *ngIf="this.category==='the-speakers'"
            style="color:#333;margin-top: 20px;font-size:18px;margin-top:27px;position:absolute;padding-left:11px;">
        <a [routerLink]="['/the-speakers']">The Speakers</a>
      </span>
      <span *ngIf="this.category==='one-more-thing'"
            style="color:#333;margin-top: 20px;font-size:18px;margin-top:27px;position:absolute;padding-left:11px;">
        <a [routerLink]="['/one-more-thing']">One More Thing</a>
      </span>
      <span *ngIf="this.category==='in-conversation'"
            style="color:#333;margin-top: 20px;font-size:18px;margin-top:27px;position:absolute;padding-left:11px;">
        <a [routerLink]="['/in-conversation']">In Conversation</a>
      </span>
      <span *ngIf="(this.category==='live-case')"
            style="color:#333;margin-top: 20px;font-size:18px;margin-top:27px;position:absolute;padding-left:11px;">
        <a [routerLink]="['/csinic-2016/live_cases']">Live Cases</a>
      </span>
      <span *ngIf="this.category==='revolution-talk'"
            style="color:#333;margin-top: 20px;font-size:18px;margin-top:27px;position:absolute;padding-left:11px;">
        <a [routerLink]="['/revolution-talk']">Revolutation Talk</a>
      </span>
      <span *ngIf="(this.category==='highlights')"
            style="color:#333;margin-top: 20px;font-size:18px;margin-top:27px;position:absolute;padding-left:11px;">
        <a [routerLink]="['/']">Highlights</a>
      </span>
      <span *ngIf="(this.category==='ias-2014')"
            style="color:#333;margin-top: 20px;font-size:18px;margin-top:27px;position:absolute;padding-left:11px;">
        <a [routerLink]="['/specials/ias-2014']">IAS 2014</a>
      </span>
      <span *ngIf="(this.category==='wcchd-2015')"
            style="color:#333;margin-top: 20px;font-size:18px;margin-top:27px;position:absolute;padding-left:11px;">
        <a [routerLink]="['/specials/wcchd-2015']">WCCHD 2015</a>
      </span>
      <span *ngIf="(this.category==='csicon-2014')"
            style="color:#333;margin-top: 20px;font-size:18px;margin-top:27px;position:absolute;padding-left:11px;">
        <a [routerLink]="['/specials/csicon-2014']">CSICON 2014</a>
      </span>
      <span *ngIf="(this.category==='wccpci-2015')"
            style="color:#333;margin-top: 20px;font-size:18px;margin-top:27px;position:absolute;padding-left:11px;">
        <a [routerLink]="['/specials/wccpci-2015']">WCCPCI 2015</a>
      </span>

      <span *ngIf="(this.category==='cardiac-prevent-2015')"
            style="color:#333;margin-top: 20px;font-size:18px;margin-top:27px;position:absolute;padding-left:11px;">
        <a [routerLink]="['/specials/cardiac-prevent-2015']">Cardiac Prevent 2015</a>
      </span>
      <span *ngIf="(this.category==='ihj-2015')"
            style="color:#333;margin-top: 20px;font-size:18px;margin-top:27px;position:absolute;padding-left:11px;">
        <a [routerLink]="['/specials/ihj-2015']">IHJ 2015</a>
      </span>
      <span *ngIf="(this.category==='wccpci-2016')"
            style="color:#333;margin-top: 20px;font-size:18px;margin-top:27px;position:absolute;padding-left:11px;">
        <a [routerLink]="['/specials/wccpci-2016']">WCCPCI 2016</a>
      </span>
      <span *ngIf="(this.category==='csikochi-2016')"
            style="color:#333;margin-top: 20px;font-size:18px;margin-top:27px;position:absolute;padding-left:11px;">
        <a [routerLink]="['/specials/csikochi-2016']">CSIKochi 2016</a>
      </span>
      <span *ngIf="(this.category==='csinic-2016')"
            style="color:#333;margin-top: 20px;font-size:18px;margin-top:27px;position:absolute;padding-left:11px;">
        <a [routerLink]="['/specials/csinic-2016']">CSINIC 2016</a>
      </span>
      <span *ngIf="(this.category==='apvic')"
            style="color:#333;margin-top: 20px;font-size:18px;margin-top:27px;position:absolute;padding-left:11px;">
        <a [routerLink]="['/specials/apvic']">APVIC</a>
      </span>
      <span *ngIf="(this.category==='c3')"
            style="color:#333;margin-top: 20px;font-size:18px;margin-top:27px;position:absolute;padding-left:11px;">
        <a [routerLink]="['/specials/c3']">C3</a>
      </span>
      <span *ngIf="(this.category==='wccicc-2017')"
            style="color:#333;margin-top: 20px;font-size:18px;margin-top:27px;position:absolute;padding-left:11px;">
        <a [routerLink]="['/specials/wccicc-2017']">WCCICC 2017</a>
      </span>
      <span *ngIf="((this.categoryy==='highlights') && (this.categorye == 'wccicc-2017'))"
            style="color:#333;margin-top: 20px;font-size:18px;margin-top:27px;position:absolute;padding-left:11px;">
        <a [routerLink]="['/specials/wccicc-2017']"
           style="color: #333;font-size:18px;margin-top:27px;">WCCICC 2017  <span> Highlights </span></a>
      </span>

      <span *ngIf="((this.categoryy==='highlights') && (this.categorye == 'csinic-2016'))"
            style="color:#333;margin-top: 20px;font-size:18px;margin-top:27px;position:absolute;padding-left:11px;">
        <a [routerLink]="['/specials/wccicc-2017']"
           style="color: #333;font-size:18px;margin-top:27px;">CSINIC 2016 <span> Highlights </span></a>
      </span>
      <span *ngIf="((this.categoryy==='highlights') && (this.categorye == 'wccpci-2015'))"
            style="color:#333;margin-top: 20px;font-size:18px;margin-top:27px;position:absolute;padding-left:11px;">
        <a [routerLink]="['/specials/wccicc-2017']"
           style="color: #333;font-size:18px;margin-top:27px;">WCCPCI 2015 <span> Highlights </span></a>
      </span>

      <span *ngIf="((this.categoryy==='highlights') && (this.categorye == 'wccpci-2016'))">
        <a [routerLink]="['/specials/wccicc-2017']"
           style="color: #333;font-size:18px;margin-top:27px;">WCCPCI 2016 <span> Highlights </span></a>
      </span>
      <span *ngIf="((this.categoryy==='the-speakers') && (this.categorye == 'wccpci-2016'))">
        <a [routerLink]="['/specials/wccpci-2016/the-speakers']" style="color: #333;font-size:18px;margin-top:27px;">WCCPCI 2016 <span> The Speakers </span></a>
      </span>
      <span *ngIf="((this.categoryy==='the-interview') && (this.categorye == 'wccpci-2016'))">
        <a [routerLink]="['/specials/wccpci-2016/the-interview']" style="color: #333;font-size:18px;margin-top:27px;">WCCPCI 2016 <span> The Interview </span></a>
      </span>
      <span *ngIf="((this.categoryy==='one-more-thing') && (this.categorye == 'wccpci-2016'))">
        <a [routerLink]="['/specials/wccpci-2016/one-more-thing']" style="color: #333;font-size:18px;margin-top:27px;">WCCPCI 2016 <span> One More Thing </span></a>
      </span>

      <span *ngIf="((this.categoryy==='the-speakers') && (this.categorye == 'wccpci-2015'))">
        <a [routerLink]="['/specials/wccpci-2015/the-speakers']" style="color: #333;font-size:18px;margin-top:27px;">WCCPCI 2015 <span> The Speakers </span></a>
      </span>
      <span *ngIf="((this.categoryy==='the-interview') && (this.categorye == 'wccpci-2015'))">
        <a [routerLink]="['/specials/wccpci-2015/the-interview']" style="color: #333;font-size:18px;margin-top:27px;">WCCPCI 2015 <span> The Interview </span></a>
      </span>
      <span *ngIf="((this.categoryy==='one-more-thing') && (this.categorye == 'wccpci-2015'))">
        <a [routerLink]="['/specials/wccpci-2015/one-more-thing']" style="color: #333;font-size:18px;margin-top:27px;">WCCPCI 2015 <span> One More Thing </span></a>
      </span>

      <span *ngIf="((this.categoryy==='the-speakers') && (this.categorye == 'csinic-2016'))">
        <a [routerLink]="['/specials/csinic-2016/the-speakers']" style="color: #333;font-size:18px;margin-top:27px;">CSINIC 2016 <span> The Speakers </span></a>
      </span>
      <span *ngIf="((this.categoryy==='live_cases') && (this.categorye == 'csinic-2016'))">
        <a [routerLink]="['/specials/csinic-2016/live_cases']" style="color: #333;font-size:18px;margin-top:27px;">CSINIC 2016 <span> Live Cases </span></a>
      </span>
      <span *ngIf="((this.categoryy==='the-interview') && (this.categorye == 'csinic-2016'))">
        <a [routerLink]="['/specials/csinic-2016/the-interview']" style="color: #333;font-size:18px;margin-top:27px;">CSINIC 2016 <span> The Interview </span></a>
      </span>
      <span *ngIf="((this.categoryy==='one-more-thing') && (this.categorye == 'csinic-2016'))">
        <a [routerLink]="['/specials/csinic-2016/one-more-thing']" style="color: #333;font-size:18px;margin-top:27px;">CSINIC 2016 <span> One More Thing </span></a>
      </span>

      <span *ngIf="((this.categoryy==='the-interview') && (this.categorye == 'ias-2014'))">
        <a [routerLink]="['/specials/ias-2014/the-interview']" style="color: #333;font-size:18px;margin-top:27px;">IAS 2014 <span> The Interview </span></a>
      </span>

      <span *ngIf="((this.categoryy==='the-interview') && (this.categorye == 'wcchd-2015'))">
        <a [routerLink]="['/specials/wcchd-2015/the-interview']" style="color: #333;font-size:18px;margin-top:27px;">WCCHD 2015 <span> The Interview </span></a>
      </span>

      <span *ngIf="((this.categoryy==='highlights') && (this.categorye == 'csicon-2014'))">
        <a [routerLink]="['/specials/csicon-2014/highlights']" style="color: #333;font-size:18px;margin-top:27px;">CSICON 2014 <span> Highlights </span></a>
      </span>
      <span *ngIf="((this.categoryy==='the-speakers') && (this.categorye == 'csicon-2014'))">
        <a [routerLink]="['/specials/csicon-2014/the-speakers']" style="color: #333;font-size:18px;margin-top:27px;">CSICON 2014 <span> The Speakers </span></a>
      </span>
      <span *ngIf="((this.categoryy==='the-interview') && (this.categorye == 'csicon-2014'))">
        <a [routerLink]="['/specials/csicon-2014/the-interview']" style="color: #333;font-size:18px;margin-top:27px;">CSICON 2014 <span> The Interview </span></a>
      </span>
      <span *ngIf="((this.categoryy==='one-more-thing') && (this.categorye == 'csicon-2014'))">
        <a [routerLink]="['/specials/csicon-2014/one-more-thing']" style="color: #333;font-size:18px;margin-top:27px;">CSICON 2014 <span> One More Thing </span></a>
      </span>

      <span *ngIf="((this.categoryy==='highlights') && (this.categorye == 'apvic'))">
        <a [routerLink]="['/specials/apvic/highlights']"
           style="color: #333;font-size:18px;margin-top:27px;">APVIC <span> Highlights </span></a>
      </span>
      <span *ngIf="((this.categoryy==='the-interview') && (this.categorye == 'apvic'))">
        <a [routerLink]="['/specials/apvic/the-interview']"
           style="color: #333;font-size:18px;margin-top:27px;">APVIC <span> The Interview </span></a>
      </span>
      <span *ngIf="((this.categoryy==='one-more-thing') && (this.categorye == 'apvic'))">
        <a [routerLink]="['/specials/apvic/one-more-thing']"
           style="color: #333;font-size:18px;margin-top:27px;">APVIC <span> One More Thing </span></a>
      </span>

      <span *ngIf="((this.categoryy==='highlights') && (this.categorye == 'c3'))">
        <a [routerLink]="['/specials/c3/highlights']" style="color: #333;font-size:18px;margin-top:27px;">C3 <span> Highlights </span></a>
      </span>

      <span *ngIf="((this.categoryy==='highlights') && (this.categorye == 'csikochi-2016'))">
        <a [routerLink]="['/specials/csikochi-2016/highlights']" style="color: #333;font-size:18px;margin-top:27px;">CSIKochi <span> Highlights </span></a>
      </span>
      <span *ngIf="((this.categoryy==='the-speakers') && (this.categorye == 'csikochi-2016'))">
        <a [routerLink]="['/specials/csikochi-2016/the-speakers']" style="color: #333;font-size:18px;margin-top:27px;">CSIKochi 2016 <span> The Speakers </span></a>
      </span>
      <span *ngIf="((this.categoryy==='live_cases') && (this.categorye == 'csikochi-2016'))">
        <a [routerLink]="['/specials/csikochi-2016/live_cases']" style="color: #333;font-size:18px;margin-top:27px;">CSIKochi 2016 <span> Live Cases </span></a>
      </span>
      <span *ngIf="((this.categoryy==='the-interview') && (this.categorye == 'csikochi-2016'))">
        <a [routerLink]="['/specials/csikochi-2016/the-interview']" style="color: #333;font-size:18px;margin-top:27px;">CSIKochi 2016 <span> The Interview </span></a>
      </span>
      <span *ngIf="((this.categoryy==='one-more-thing') && (this.categorye == 'csikochi-2016'))">
        <a [routerLink]="['/specials/csikochi-2016/one-more-thing']"
           style="color: #333;font-size:18px;margin-top:27px;">CSIKochi 2016 <span> One More Thing </span></a>
      </span>

      <span *ngIf="((this.categoryy==='the-speakers') && (this.categorye == 'wccicc-2017'))">
        <a [routerLink]="['/specials/wccicc-2017/the-speakers']" style="color: #333;font-size:18px;margin-top:27px;">WCCICC 2017 <span> The Speakers </span></a>
      </span>
      <span *ngIf="((this.categoryy==='live_cases') && (this.categorye == 'wccicc-2017'))">
        <a [routerLink]="['/specials/wccicc-2017/live_cases']" style="color: #333;font-size:18px;margin-top:27px;">WCCICC 2017 <span> Live Cases </span></a>
      </span>
      <span *ngIf="((this.categoryy==='the-interview') && (this.categorye == 'wccicc-2017'))">
        <a [routerLink]="['/specials/wccicc-2017/the-interview']" style="color: #333;font-size:18px;margin-top:27px;">WCCICC 2017 <span> The Interview </span></a>
      </span>
      <span *ngIf="((this.categoryy==='one-more-thing') && (this.categorye == 'wccicc-2017'))">
        <a [routerLink]="['/specials/wccicc-2017/one-more-thing']" style="color: #333;font-size:18px;margin-top:27px;">WCCICC 2017 <span> One More Thing </span></a>
      </span>
      <span *ngIf="(this.category==='wccpci-2015')">
      <a [routerLink]="['/specials/wccpci-2015/presentation/slide/home']">wccpci-2015</a>
    </span>


      <div class="pre_alpha">Pre Alpha</div>
    </div>

    <div class="pull-right nne">


      
      <mat-icon [matMenuTriggerFor]="menu" fxShow="false" fxShow.lt-md="true" fxShow.lt-sm="true" fxHide.gt-sm>menu
      </mat-icon>
      


    </div>
  </div>
</div>


<div fxShow.lt-sm="true" fxShow.lt-md="true" fxShow="false">
  <mat-menu #menu="matMenu" [overlapTrigger]="false" yPosition="above">
    <button mat-menu-item [routerLink]="['/']">Home</button>
    <button mat-menu-item [routerLink]="['live']">Live</button>
    <button mat-menu-item href="https://aicogtv.therightdoctors.com/">Emcure AIOCIG tv</button>
    <button mat-menu-item [routerLink]="['/the-interview']">The Interview</button>
    <button mat-menu-item [routerLink]="['/one-more-thing']">One More Thing</button>
    <button mat-menu-item [routerLink]="['/the-speakers']">The Speakers</button>
    <button mat-menu-item [routerLink]="['/in-conversation']">In Conversation</button>
    <button mat-menu-item [routerLink]="['/specials']">Specials</button>
    <button mat-menu-item [routerLink]="['/synapse']">Synapse</button>

  </mat-menu>
</div>


<div fxShow="true" fxShow.lt-md="false" style="background-color: #0C58A5">
  <mat-toolbar color="primary" class="newsty" style="font-size:14px;">

    <span class="fill-remaining-space"></span>
    <div class=" menustyle container"
         fxLayout="row"
         fxLayout.xs="column"

         fxLayoutGap="25px"
         fxLayoutGap.xs="0" fxShow.xs="false">
      <div class="menustyle" fxFlexOrder="0"><a [routerLink]="['/']" style="color:white">Home</a></div>
      <div class="menustyle" fxFlexOrder="1"><a style="color:white" [routerLink]="['/live']">Live</a></div>
      <div class="item item-3" fxFlexOrder="2"><a style="color:white" class="menustyle"
                                                  href="https://aicogtv.therightdoctors.com/">Emcure AIOCIG tv</a></div>
      <div class="item item-4" fxFlexOrder="3"><a style="color:white" class="menustyle"
                                                  [routerLink]="['/the-interview']">The Interview</a></div>
      <div class="item item-5" fxFlexOrder="4"><a class="menustyle" style="color:white"
                                                  [routerLink]="['/one-more-thing']">One More Thing</a></div>
      <div class="item item-7" fxFlexOrder="6"><a class="menustyle" style="color:white"
                                                  [routerLink]="['/the-speakers']">Speakers</a></div>
      <div class="item item-8" fxFlexOrder="7"><a style="color:white" class="menustyle"
                                                  [routerLink]="['/in-conversation']">In Conversation</a></div>
      <div class="item item-9" fxFlexOrder="8"><a class="menustyle" style="color:white" [routerLink]="['/specials']">Specials</a>
      </div>
      <div class="item item-10" fxFlexOrder="9"><a style="color:white" class="menustyle" [routerLink]="['/synapse']">Synapse</a>
      </div>
    </div>

  </mat-toolbar>
</div>



`

**Comment by julianobrasil** [comment] 2018-07-16 15:55
Just to make shure I got it right, you tried to turn this:

```html
<div class=" menustyle container"
     fxLayout="row"
     fxLayout.xs="column"
     fxLayoutGap="25px"
     fxLayoutGap.xs="0" fxShow.xs="false">
```

into this:

```html
<div class=" menustyle container"
     [fxLayout]="_isHandset ? 'column': 'row'"
     [fxLayoutGap]="_isHandset ? 0: '25px'"
     [fxShow]="[_isHandset]">
```

Is that right?

**Comment by julianobrasil** [comment] 2018-07-16 15:57
BTW, it would be easier if you managed to put together a  [StackBlitz demo](https://goo.gl/y38GUZ).

**Comment by cstrd** [comment] 2018-07-16 18:47
Thanks for replying..
Yes. It' is right . I will share demo on stackbiz tomorrow.  And now we are thinking to make seprate project for mobile version.  So based on viewport it will forward to m.mytherightdoctors.com. 
Is it good to do that? Wht you would suggest?

**Comment by mackelito** [comment] 2018-07-16 19:19
Now I might be why off here.. but having a mobile version might punish you due to duplicate content right?...

I would say that stay with a plain responsive site...

**Comment by julianobrasil** [comment] 2018-07-16 20:54
I agree with @mackelito. If javascript based directives don't give you the expected ux you wish, you should go with pure CSS...

**Comment by CaerusKaru** [comment] 2018-07-19 06:41
I'm not sure I understand the issue, can you please be specific as to what part of the Flex Layout library isn't working?

**Comment by julianobrasil** [comment] 2018-07-19 08:57
@CaerusKaru, if you access the link he provided,  from a small device,  you'll see his app opening with the desktop layout configurations. After a few seconds it switches to the correct small device layout configs. Basically he wants it to open in right layout configuration from the very beginning losing time. 

The link: https://therightdoctors.com/

**Comment by cstrd** [comment] 2018-07-19 10:23
Hi.. @julianobrasil..
We have changed Flex layout into CSS(https://therightdoctors.com/), Design issues sorted out.. But now we are facing loading issue, to load complete website home page it is taking around 20 secs. We are using all custom CSS files

Please suggest us, any solution...

**Comment by mackelito** [comment] 2018-07-19 10:39
@cstrd looks like that's a service issue.. Time to first byte are reaaally slow..
Request URL: https://therightdoctors.com/api/beta/article?day=Thursday&key=7xOyNH554tY83cBN7Ktpw3s1y68ql6Eg&top_category=true
4.83 seconds to load...

**Comment by mackelito** [comment] 2018-07-19 14:11
Still to slow.. and even slower for me...
![screen shot 2018-07-19 at 16 10 20](https://user-images.githubusercontent.com/598463/42947753-49f7b570-8b6e-11e8-8c23-4c20a0276e50.png)


Also it looks like you are first loading default images.. and then on highres screens swapping then out for large versions..?

**Comment by cstrd** [comment] 2018-07-19 16:32
Hi.. please suggest us how to decrease the loading speed..

**Comment by mackelito** [comment] 2018-07-19 18:04
The problem is not Frontend but backend.. server is not responding fast enough

**Comment by cstrd** [comment] 2018-07-21 16:10
Hi, we are planning to implement, lazy loading(https://angular.io/guide/lazy-loading-ngmodules) in our application to decrease the page load time(now 12.4 sec - https://therightdoctors.com). please suggest us does it will work as we are thinking?

**Comment by mackelito** [comment] 2018-07-21 16:55
This will help to delay the loading.. but not speed up anything... The problem is still backend

**Comment by cstrd** [comment] 2018-07-28 03:00
HI.. @mackelito

We built a website using Angular 6 Universal App, Meta tags are not Updating in the View Page Source. (https://therightdoctors.com/one-more-thing/dr-s-ramakrishnan-additional-professor-cad-stroke-and-renal-diseases-are-on-a-scale-that-is-unbelievable)

Please check below code of updating metags in component.ts file 

```
this.titleService.setTitle('Dr.S Ramakrishnan | TheRightDoctors');

this.meta.updateTag({name: 'description', content:'TheRightDoctors  Dr.S Ramakrishnan After discharge of a STEMI patient… story continues'});

this.meta.updateTag({name: 'keywords', content:'dr s ramakrishnan,dr s ramakrishnan iit madras,Cardiologist, TheRightDoctors, TheRightDoctors.com, the right doctors,Dr. S RamaKrishnan, Dept. of Cardiology, AIIMS, New Delhi'});

            this.meta.updateTag({
              property: 'vr:canonical',
              content: 'https://therightdoctors.com/one-more-thing/dr-s-ramakrishnan-additional-professor-cad-stroke-and-renal-diseases-are-on-a-scale-that-is-unbelievable'
            });
```


In view page Source meta tags are not updating, it is displaying whatever it is there in index.html (Please check this URL - https://therightdoctors.com/one-more-thing/dr-s-ramakrishnan-additional-professor-cad-stroke-and-renal-diseases-are-on-a-scale-that-is-unbelievable)

Note:- If we will change Route for this URL (https://therightdoctors.com/one-more-thing/dr-s-ramakrishnan-additional-professor-cad-stroke-and-renal-diseases-are-on-a-scale-that-is-unbelievable) to (https://therightdoctors.com/all/one-more-thing/dr-s-ramakrishnan-additional-professor-cad-stroke-and-renal-diseases-are-on-a-scale-that-is-unbelievable  - I added 'all') then it is working.. Problem here is i can't change the route(url). please suggest some solution...

**Comment by mackelito** [comment] 2018-08-01 21:42
@cstrd sorry but this is not a support forum.. if bugs are found, great, post it here.. When looking for help on non bug related issues I would suggest using stackoverflow :) 👍

**Comment by CaerusKaru** [comment] 2018-08-02 15:11
Closing as @mackelito is correct. Please use StackOverflow or Gitter for help with non-bugs or feature requests.

**Closed by CaerusKaru** 2018-08-02 15:11 UTC
Labels: can be closed?, needs: investigation
