### ISSUE TITLE
fxFlex seems to ignore the grow alias when 1-way data-bound using the box-notation

### ISSUE THREAD

**Issue by parker-mike** [angular/flex-layout#580] opened 2018-01-19 15:22 UTC
#### Bug, feature request, or proposal:
Seems to be a bug, since `noshrink` or `nogrow` work as expected.

#### What is the expected behavior?
The style attribute is expected to be updated,...

#### What is the current behavior?
... but it is not.

#### Reproduction example:
https://angular-flex-layout-fxflex-grow-databind-problem.stackblitz.io

#### Versons:
Angular: 5.1.1
Material: 5.0.1
flex-layout: 2.0.0-beta.12
Win10 FCU(1709)
Chrome 63.0.3239.132 (x64)

**Comment by CaerusKaru** [comment] 2018-01-19 21:09
Can you please provide a link to the StackBlitz source?

**Comment by parker-mike** [comment] 2018-01-20 02:00
@CaerusKaru it's already there, under `Reproduction example` header...

**Comment by CaerusKaru** [comment] 2018-01-20 02:01
@parker-mike I need the _source_, not the rendered output, i.e. the IDE interface instead of just the public facing site.

**Comment by parker-mike** [comment] 2018-01-20 02:03
Oh, sorry, just copied the first url StackBlitz gave... here the link https://stackblitz.com/edit/angular-flex-layout-fxflex-grow-databind-problem

**Comment by CaerusKaru** [comment] 2018-01-20 02:09
Ok so the issue is that switching to `grow` _or_ `nogrow` doesn't clear the `flex-basis` (which right now is aliased for `max-width`). Thanks for catching this!

**Comment by CaerusKaru** [comment] 2018-12-15 05:44
I am _thrilled_ to announce that this issue has been fixed in the latest beta! I don't know exactly which PR did it, but it's been resolved 😄. Please let me know if you haven't observed this, but updating the StackBlitz gave the correct results for me!

**Closed by CaerusKaru** 2018-12-15 05:44 UTC
Labels: P1, bug
