### ISSUE TITLE
Module '"../node_modules/@angular/core/core"' has no exported member 'OpaqueToken'.

### ISSUE THREAD

**Issue by amar-muratovic** [angular/flex-layout#591] opened 2018-01-31 17:59 UTC
Dear all,

this is one of the errors that I have when I type in _ionic serve_  in CMD. I was trying a different kind of things to solve this but without success.

ERROR:
import { ModuleWithProviders, OpaqueToken } from '@angular/core';

ENVIROMENT:
Ionic Framework: 3.9.2
Ionic App Scripts: 3.1.8
Angular Core: 5.0.3
Angular Compiler CLI: 5.0.3
Node: 6.10.3
OS Platform: Windows 10
Navigator Platform: Win32
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

**Comment by CaerusKaru** [comment] 2018-01-31 18:46
Duplicate of #494

**Closed by CaerusKaru** 2018-01-31 18:46 UTC

**Comment by amar-muratovic** [comment] 2018-01-31 18:56
PROBLEM: import { ModuleWithProviders, OpaqueToken } from '@angular/core';

placed here... /node_modules/@ionic/cloud-angular/dist/es5/index.d.ts

"dependencies": {
    "@angular/common": "5.0.3",
    "@angular/compiler": "5.0.3",
    "@angular/compiler-cli": "5.0.3",
    "@angular/core": "5.0.3",
    "@angular/flex-layout": "^2.0.0-rc.1",
    "@angular/forms": "5.0.3",
    "@angular/http": "5.0.3",
    "@angular/platform-browser": "5.0.3",
    "@angular/platform-browser-dynamic": "5.0.3",
    "@ionic-native/core": "4.5.3",
    "@ionic-native/in-app-browser": "4.5.3",
    "@ionic-native/splash-screen": "4.5.3",
    "@ionic-native/status-bar": "4.5.3",
    "@ionic/cloud-angular": "^0.12.0",
    "@ionic/pro": "1.0.16",
    "@ionic/storage": "2.1.3",
    "@reactivex/rxjs": "^5.4.2",
    "dist": "^0.1.2",
    "es5": "^1.0.0",
    "ionic-angular": "3.9.2",
    "ionicons": "3.0.0",
    "rxjs": "^5.5.6",
    "sw-toolbox": "3.6.0",
    "websocket": "^1.0.25",
    "zone.js": "0.8.18"
  },

**Comment by CaerusKaru** [comment] 2018-01-31 18:57
Please review the linked issue for the solution. Again, this is a duplicate issue.

**Comment by amar-muratovic** [comment] 2018-01-31 18:59
Okay @CaerusKaru  but please I'm not stupid I'm just trying to get a solution. I was Googling for the solution but without success...

**Comment by CaerusKaru** [comment] 2018-01-31 19:01
Your problem is that you have the RC.1 version installed, which is solved by following the steps specified for solution in the linked issue. You need to install the `@latest` version, and make sure not to run `npm update` on the package.

**Comment by iftikharkhan89** [comment] 2018-03-28 10:36
I solved this by replacing  

> OpaqueToken

 with 

> InjectionToken

`import { InjectionToken } from '@angular/core';`

My Environment settings are 
Angular CLI: 1.7.3
Node: 9.8.0
OS: darwin x64
Angular: 5.2.9

**Comment by KogAtlas** [comment] 2018-09-05 16:15
Thanks @iftikharkhan89. This was _not_ a duplicate, at least not with the one that is linked.

**Comment by Mutondi** [comment] 2018-12-10 11:45
Thanks, @iftikharkhan89 you are a lifesaver.
