### ISSUE TITLE
Grid layout documentation is broken

### ISSUE THREAD

**Issue by atotalnoob** [angular/flex-layout#1289] opened 2020-09-04 18:28 UTC
# Bug Report

#### What is the expected behavior?
When visiting https://github.com/angular/flex-layout/wiki/Declarative-API-Overview I am able to click into and view details of the grid layout apis. 

#### What is the current behavior?
Visiting https://github.com/angular/flex-layout/wiki/Declarative-API-Overview and clicking any grid related link on that page returns you to the home page of the wiki.

#### What is the use-case or motivation for changing an existing behavior?
Being able to read the api, rather than figuring it out by trial and error

**Comment by CaerusKaru** [comment] 2020-09-04 18:38
Duplicate of #1026

**Closed by CaerusKaru** 2020-09-04 18:38 UTC
