### ISSUE TITLE
FlexLayout styles are getting added automatically when AOT complier ON not  JIT...

### ISSUE THREAD

**Issue by rmathi** [angular/flex-layout#1019] opened 2019-02-07 11:21 UTC
Hi All, In my application using Angular 7, Angular Material & typescript and **FlexLayout** are latest version. The problem is FlexLayout styles are getting added automatically when AOT compiler ON not  JIT compiler. When i turned off AOT compiler the styles are not added. Also tried to set flexlayout config `FlexLayoutModule.withConfig({addFlexToParent: false});` but it doesn't help.

So, could please explain anyone why its applying only when AOT ON not in JIT ? and how to remove the automatically added styles? 
Thanks in Advance.

**Comment by CaerusKaru** [comment] 2019-02-08 06:04
Please provide a minimal reproduction that we can investigate. This doesn't happen with our demo app.

**Comment by mackelito** [comment] 2019-02-08 06:23
@rmathi as a general rule.. use www.stackovweflow.com for questions.. if you have found a but and there is a template to fill out and follow when submitting a bug report then you should follow it :)

**Comment by florian-badaluma** [comment] 2019-02-08 12:33
Not sure if this is the right place to add my thoughts, but I experienced also an issue with AOT.
Although I used: 
`FlexLayoutModule.withConfig(
      { disableDefaultBps: true }
),`
there were still the default breakpoints besides my custom ones after building my project. 
Therefore I had to remove AOT to make it work as expected.

 _"@angular/flex-layout": "^7.0.0-beta.23"_

**Comment by rmathi** [comment] 2019-02-11 05:22
> f you have found a but and there is a template to fill out and follow when submitting a bug report then you should foll

@mackelito Sure.. I will update it as per the template.

**Comment by rmathi** [comment] 2019-02-11 05:26
> Not sure if this is the right place to add my thoughts, but I experienced also an issue with AOT.
> Although I used:
> `FlexLayoutModule.withConfig( { disableDefaultBps: true } ),`
> there were still the default breakpoints besides my custom ones after building my project.
> Therefore I had to remove AOT to make it work as expected.
> 
> _"@angular/flex-layout": "^7.0.0-beta.23"_

@florian-badaluma Thanks for the Information. Here i couldn't remove the AOT. 
I have fix the issues by making parent as Flexlayout  container but my question is why its happening only AOT not JIT and how to remove the automatically added styles?

**Comment by CaerusKaru** [comment] 2019-03-17 01:12
I'm going to close this issue since it's been over a month since I asked for a minimal reproduction and none was provided. If this is a genuine issue, we can reopen.

**Closed by CaerusKaru** 2019-03-17 01:12 UTC
Labels: needs:  demo
