### ISSUE TITLE
setting fxFlex="[value]" creates weird behaviour in row width

### ISSUE THREAD

**Issue by mattiLeBlanc** [angular/flex-layout#495] opened 2017-11-10 04:43 UTC
I am getting a bit confused after using AngularJS Material's flex layout directive for years.

I have a simple column with3 rows structure. 
```
        <div class="steps" fxLayout="column" >
            <div class="step" fxLayout="row" >
              <label>Step 1</label>
              <div>Select your business bank account</div>
            </div>
            <div class="step" fxLayout="row" >
              <label>Step 2</label>
              <div>Enter your bank login credentials and submit</div>
            </div>
            <div class="step" fxLayout="row">
              <label fxFlex="30">Step 3</label>
              <div>Finished! You’ll hear from us within 1 business day</div>
            </div>
          </div>
```
I want the `label` to have a fixed with and the row should just be full size.
However, as you can see:
![image](https://user-images.githubusercontent.com/5285035/32643150-70a1befc-c62d-11e7-8223-5931af58a4b3.png)
the flex 30 get's a `max-width` of 30% but the flex is set to `1 1 100%`. Shouldn't this be 30%?

Also, when I add the fxFlex 30 to the child it automatically adds layout `row` to the parent row. In the example I already set it to row. However, I can't seem to stretch that row to the width of its container, using fxFlex.

This concept used to work before in the `old` flex-layout.
I would do something like:

```
        <div class="steps" fxLayout="column" fxFlex>  //-> stretch the wrapper
            <div class="step" fxLayout="row" fxFlex> //-> stretch the row
              <label fxFlex="30">Step 3</label> //-> set col to 30
              <div>Finished! You’ll hear from us within 1 business day</div> //-> this col get's the rest
            </div>
          </div>
```
I can't get this to work with the latest flex-layout. Any thoughts?

**Comment by CaerusKaru** [comment] 2018-01-15 06:30
Can you create a StackBlitz demo for us? I think @ThomasBurleson is working on a potential fix for this, but it would help to have a reproducible demo.

**Comment by CaerusKaru** [comment] 2018-03-16 08:07
Moving this to the backlog until we get a demo to investigate.

**Comment by CaerusKaru** [comment] 2018-11-04 20:08
Closing this issue since no demo has been provided. If one is provided, we can reopen it.

**Closed by CaerusKaru** 2018-11-04 20:08 UTC
Labels: P1, needs:  demo
