### ISSUE TITLE
Unable to compile project after enabling ivy on angular v8

### ISSUE THREAD

**Issue by amrohit** [angular/flex-layout#1076] opened 2019-06-01 07:32 UTC
ERROR in ./node_modules/@angular/flex-layout/__ivy_ngcc__/esm2015/extended.js 133:578
Module parse failed: Unexpected token (133:578)
You may need an appropriate loader to handle this file type.
|     }
| }
> DefaultImgSrcDirective.ngDirectiveDef = ɵngcc0.ɵɵdefineDirective({ type: DefaultImgSrcDirective, selectors:
[["img", "src.xs", ""], ["img", "src.sm", ""], ["img", "src.md", ""], ["img", "src.lg", ""], ["img", "src.xl", ""], ["img", "src.lt-sm", ""], ["img", "src.lt-md", ""], ["img", "src.lt-lg", ""], ["img", "src.lt-xl", ""],
["img", "src.gt-xs", ""], ["img", "src.gt-sm", ""], ["img", "src.gt-md", ""], ["img", "src.gt-lg", ""]], factory: function DefaultImgSrcDirective_Factory(t) { return ɵDefaultImgSrcDirective_BaseFactory((t || DefaultImgSrcDirective)); }, inputs: { src.xs: "src.xs", src.sm: "src.sm", src.md: "src.md", src.lg: "src.lg", src.xl: "src.xl", "src.lt-sm": "src.lt-sm", "src.lt-md": "src.lt-md", "src.lt-lg": "src.lt-lg", "src.lt-xl": "src.lt-xl", "src.gt-xs": "src.gt-xs", "src.gt-sm": "src.gt-sm", "src.gt-md": "src.gt-md", "src.gt-lg": "src.gt-lg" }, features: [ɵngcc0.ɵɵInheritDefinitionFeature] });
| const ɵDefaultImgSrcDirective_BaseFactory = ɵngcc0.ɵɵgetInheritedFactory(DefaultImgSrcDirective);
| /*@__PURE__*/ ɵngcc0.ɵsetClassMetadata(DefaultImgSrcDirective, [{
ERROR in ./node_modules/@angular/flex-layout/__ivy_ngcc__/esm2015/flex.js 192:653
Module parse failed: Unexpected token (192:653)
You may need an appropriate loader to handle this file type.
|     }
| }
> DefaultLayoutDirective.ngDirectiveDef = ɵngcc0.ɵɵdefineDirective({ type: DefaultLayoutDirective, selectors:
[["", "fxLayout", ""], ["", "fxLayout.xs", ""], ["", "fxLayout.sm", ""], ["", "fxLayout.md", ""], ["", "fxLayout.lg", ""], ["", "fxLayout.xl", ""], ["", "fxLayout.lt-sm", ""], ["", "fxLayout.lt-md", ""], ["", "fxLayout.lt-lg", ""], ["", "fxLayout.lt-xl", ""], ["", "fxLayout.gt-xs", ""], ["", "fxLayout.gt-sm", ""], ["", "fxLayout.gt-md", ""], ["", "fxLayout.gt-lg", ""]], factory: function DefaultLayoutDirective_Factory(t) { return ɵDefaultLayoutDirective_BaseFactory((t || DefaultLayoutDirective)); }, inputs: { fxLayout: "fxLayout", fxLayout.xs:
"fxLayout.xs", fxLayout.sm: "fxLayout.sm", fxLayout.md: "fxLayout.md", fxLayout.lg: "fxLayout.lg", fxLayout.xl: "fxLayout.xl", "fxLayout.lt-sm": "fxLayout.lt-sm", "fxLayout.lt-md": "fxLayout.lt-md", "fxLayout.lt-lg": "fxLayout.lt-lg", "fxLayout.lt-xl": "fxLayout.lt-xl", "fxLayout.gt-xs": "fxLayout.gt-xs", "fxLayout.gt-sm": "fxLayout.gt-sm", "fxLayout.gt-md": "fxLayout.gt-md", "fxLayout.gt-lg": "fxLayout.gt-lg" }, features: [ɵngcc0.ɵɵInheritDefinitionFeature] });
| const ɵDefaultLayoutDirective_BaseFactory = ɵngcc0.ɵɵgetInheritedFactory(DefaultLayoutDirective);
| /*@__PURE__*/ ɵngcc0.ɵsetClassMetadata(DefaultLayoutDirective, [{
ERROR in ./node_modules/@angular/flex-layout/__ivy_ngcc__/esm2015/grid.js 92:719
Module parse failed: Unexpected token (92:719)
You may need an appropriate loader to handle this file type.
|     }
| }
> DefaultGridAlignDirective.ngDirectiveDef = ɵngcc0.ɵɵdefineDirective({ type: DefaultGridAlignDirective, selectors: [["", "gdGridAlign", ""], ["", "gdGridAlign.xs", ""], ["", "gdGridAlign.sm", ""], ["", "gdGridAlign.md", ""], ["", "gdGridAlign.lg", ""], ["", "gdGridAlign.xl", ""], ["", "gdGridAlign.lt-sm", ""], ["", "gdGridAlign.lt-md", ""], ["", "gdGridAlign.lt-lg", ""], ["", "gdGridAlign.lt-xl", ""], ["", "gdGridAlign.gt-xs", ""], ["", "gdGridAlign.gt-sm", ""], ["", "gdGridAlign.gt-md", ""], ["", "gdGridAlign.gt-lg", ""]], factory: function DefaultGridAlignDirective_Factory(t) { return ɵDefaultGridAlignDirective_BaseFactory((t || DefaultGridAlignDirective)); }, inputs: { gdGridAlign: "gdGridAlign", gdGridAlign.xs: "gdGridAlign.xs", gdGridAlign.sm: "gdGridAlign.sm", gdGridAlign.md: "gdGridAlign.md", gdGridAlign.lg: "gdGridAlign.lg", gdGridAlign.xl: "gdGridAlign.xl",
"gdGridAlign.lt-sm": "gdGridAlign.lt-sm", "gdGridAlign.lt-md": "gdGridAlign.lt-md", "gdGridAlign.lt-lg": "gdGridAlign.lt-lg", "gdGridAlign.lt-xl": "gdGridAlign.lt-xl", "gdGridAlign.gt-xs": "gdGridAlign.gt-xs", "gdGridAlign.gt-sm": "gdGridAlign.gt-sm", "gdGridAlign.gt-md": "gdGridAlign.gt-md", "gdGridAlign.gt-lg": "gdGridAlign.gt-lg" }, features: [ɵngcc0.ɵɵInheritDefinitionFeature] });
| const ɵDefaultGridAlignDirective_BaseFactory = ɵngcc0.ɵɵgetInheritedFactory(DefaultGridAlignDirective);
| /*@__PURE__*/ ɵngcc0.ɵsetClassMetadata(DefaultGridAlignDirective, [{
i ｢wdm｣: Failed to compile.

**Comment by CaerusKaru** [comment] 2019-06-02 22:01
Duplicate of #1072

**Closed by CaerusKaru** 2019-06-02 22:01 UTC

**Comment by stkrwilson** [comment] 2019-06-05 10:25
same here:
ERROR in ./node_modules/@angular/flex-layout/__ivy_ngcc__/esm2015/flex.js 192:653
Module parse failed: Unexpected token (133:578)
You may need an appropriate loader to handle this file type.
|     }
| }

**Comment by kschwidder** [comment] 2019-06-14 15:44
+1. Workaround to drop flex-layout is not an option for your developed application.
