### ISSUE TITLE
Angular 5.2.8 - Error during template compile of 'FlexLayoutServerModule' (nightly)

### ISSUE THREAD

**Issue by alvipeo** [angular/flex-layout#651] opened 2018-03-10 04:57 UTC
I've been using nightly builds for quite some time but today I upgraded to angular 5.2.8 and this started to show up:

>> ERROR in Error during template compile of 'FlexLayoutServerModule'
  Could not resolve @angular/platform-server relative to E:/Documents/repos/b-platform/node_modules/@angular/flex-layout/server/typings/index.d.ts. in 'SERVER_PROVIDERS'
    'SERVER_PROVIDERS' contains the error at ..\@angular\flex-layout\server\typings\index.ts(82,42).

I know it's nightly but can you please provide a solution for this as I have 2 projects that are now broken.
Thank you!

**Comment by CaerusKaru** [comment] 2018-03-10 04:58
Duplicate of https://github.com/angular/flex-layout/issues/646

**Closed by CaerusKaru** 2018-03-10 04:58 UTC

**Comment by CaerusKaru** [comment] 2018-03-10 05:02
It looks like this might be an issue with how we're exporting secondary entrypoints right now. This will probably be resolved in an upcoming release

**Comment by alvipeo** [comment] 2018-03-10 16:37
And when are this upcoming release is going to happen?

**Comment by CaerusKaru** [comment] 2018-03-10 17:03
No idea

**Comment by CaerusKaru** [comment] 2018-03-11 22:14
Tracking this in #646, will be fixed by #656
