### ISSUE TITLE
fxLayoutAlign="space-between center" - overlaps the last row in the alignment

### ISSUE THREAD

**Issue by MythriManjunath** [angular/flex-layout#286] opened 2017-05-15 09:01 UTC
I want to display cards in the center with two/three columns and multiple rows. The cards are displayed dynamically. I want to have equal space between each row of cards. I set this attribute fxLayoutAlign="space-between center" in my code. By refering this link https://tburleson-layouts-demos.firebaseapp.com/#/docs. It will not display correctly. There is no space between rows and the last row is not aligned properly with the column. Only the last row is not aligned vertically with the column. When I change the browser window size also the alignment is messed up. These are the versions I am using

Angular version - 2.4.10
 "@angular/material": "2.0.0-beta.2",
"@angular/flex-layout@2.0.0-beta.5"

**Comment by MythriManjunath** [comment] 2017-05-15 10:30
```
<div fxLayout="row" fxLayoutWrap fxLayoutGap="6rem" fxLayoutAlign="space-between center">
  <md-card  fxFlex.gt-md="40" fxFlex.md="50"  fxFlex.sm="40" fxFlex.xs="100" *ngFor="let data of myData" [style.background]="'lightBlue'">
    <md-card-header>
      <md-card-title>element</md-card-title>
    </md-card-header>
   
    <md-card-content>
			<h1>Main Content Data</h1>
      <p>
        Lorem Ipsum
      </p>
    </md-card-content>
  </md-card>
</div>
```

**Comment by anvial** [comment] 2017-05-17 21:39
+1

**Comment by ThomasBurleson** [comment] 2017-05-17 22:18
When using `fxLayout="row"`, the `fxLayoutGap` directive applies a **margin-right** gap.

General discussion and how-to questions should be posted to the community forum areas:

*  [Google Groups](https://groups.google.com/forum/#!forum/angular-flex-layout)
*  [Gitter Channel](https://gitter.im/angular/flex-layout)

Closing this issue as 'invalid'. Thank you.

**Closed by ThomasBurleson** 2017-05-17 22:18 UTC

**Comment by Raghav-Sao** [comment] 2017-07-17 14:02
so it's not a bug???

**Comment by mackelito** [comment] 2017-07-17 22:03
try 
`  <md-card  fxFlex.gt-md="calc(40%-6rem)" fxFlex.md="calc(50%-6rem)"  fxFlex.sm="calc(40%-6rem)" fxFlex.xs="calc(100%-6rem)" *ngFor="let data of myData" [style.background]="'lightBlue'">
`

Kind of hard with out a plunkr and not see it in action :)
