### ISSUE TITLE
FxShow/Hide Broke in beta.20 release

### ISSUE THREAD

**Issue by tommyc38** [angular/flex-layout#925] opened 2018-12-16 08:12 UTC
# Bug Report

#### What is the expected behavior?
fxShow fxHide along with their responsive counterparts should work.  They don't in beta.20 and beta.21 but do in beta.19

#### What is the current behavior?
they don't work

#### What are the steps to reproduce?
Providing a StackBlitz (or similar) is the *best* way to get the team to see your issue.

*  [StackBlitz starter](https://goo.gl/y38GUZ) using latest `npm` nightly release: 

#### What is the use-case or motivation for changing an existing behavior?
this is a critical directive

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 7.1.3
Material/Cdk: 7.1.3
OS: MacOS Mojave
TS: 3.1.6

**Comment by CaerusKaru** [comment] 2018-12-16 12:00
Duplicate of #915

**Closed by CaerusKaru** 2018-12-16 12:00 UTC
