### ISSUE TITLE
fxHide does not work when used together with fxLayout or fxLayoutAlign

### ISSUE THREAD

**Issue by jkang027** [angular/flex-layout#979] opened 2019-01-10 18:09 UTC
# Bug Report

#### What is the expected behavior?
fxHide, when used with a breakpoint, should work when used in conjunction with fxLayout or fxLayoutAlign.

#### What is the current behavior?
When fxHide, when used with a breakpoint, is used in conjunction with fxLayout or fxLayoutAlign, elements no longer hide on resizing the screen.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-z3t21q

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/flex-layout 7.0.0-beta.22

**Comment by CaerusKaru** [comment] 2019-01-10 18:42
Duplicate of https://github.com/angular/flex-layout/issues/945

**Closed by CaerusKaru** 2019-01-10 18:42 UTC
