### ISSUE TITLE
Angular Flex Layout is not working with Angular 7?

### ISSUE THREAD

**Issue by reddybashanaguru** [angular/flex-layout#1070] opened 2019-05-29 06:55 UTC
ERROR in node_modules/@angular/flex-layout/extended/typings/class/class.d.ts(9,19): error TS2305: Module '"D:/UIEduFront/uiedufront/node_modules/@angular/common/common"' has no exported member 'ɵNgClassImpl'.
node_modules/@angular/flex-layout/extended/typings/class/class.d.ts(9,33): error TS2305: Module '"D:/UIEduFront/uiedufront/node_modules/@angular/common/common"' has no exported member 'ɵNgClassR2Impl'.
node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(9,19): error TS2305: Module '"D:/UIEduFront/uiedufront/node_modules/@angular/common/common"' has no exported member 'ɵNgStyleImpl'.
node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(9,33): error TS2305: Module '"D:/UIEduFront/uiedufront/node_modules/@angular/common/common"' has no exported member 'ɵNgStyleR2Impl'.

--- Versions---

Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cdk                      7.3.7
@angular/cli                      7.3.9
@angular/flex-layout              8.0.0-beta.26
@angular/material                 7.3.7
@ngtools/webpack                  7.3.9
@schematics/angular               7.3.9
@schematics/update                0.13.9
rxjs                              6.5.2
typescript                        3.2.4
webpack                           4.29.0

**Comment by CaerusKaru** [comment] 2019-05-29 12:01
Duplicate of #1064

**Closed by CaerusKaru** 2019-05-29 12:01 UTC
