### ISSUE TITLE
docs: wiki links in right-side nav are broken

### ISSUE THREAD

**Issue by LauraKirby** [angular/flex-layout#663] opened 2018-03-14 00:06 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
issue 1: click, "Source Code", should be taken to the source code for the demo application
issue 2: click, "Browser Support",  should be taken to information about "Browser Support"

#### What is the current behavior?
issue 1: "404" 
issue 2: "You do not have permission to update this wiki."

#### What are the steps to reproduce?
Providing a StackBlitz (or similar) is the *best* way to get the team to see your issue.

* Visit [flex-layout wiki](https://github.com/angular/flex-layout/wiki)
* Click on "Source Code" 
* Click on "Browser Support" 

#### What is the use-case or motivation for changing an existing behavior?
- Would like to use flex-layout and want to learn more about how it is working / browser compatibility before blindly installing.

**Comment by CaerusKaru** [comment] 2018-03-14 00:07
Duplicate of #654

**Closed by CaerusKaru** 2018-03-14 00:07 UTC
