### ISSUE TITLE
Problem bind [(ngModel)] using material <md-radio-group> component with flexLayout

### ISSUE THREAD

**Issue by GustavoCostaW** [angular/flex-layout#322] opened 2017-06-22 01:12 UTC
Hey people,

I'm using 
Angular Material beta 7
Angular Flex Layout beta 8

I have a component with the following code snippet 

```html
{{question.answer}}
<md-radio-group [(ngModel)]="question.answer" name="question{{i}}">
               <div id="problem" *ngFor="let alternative of question.alternatives" fxLayout>
                  <md-radio-button [value]="alternative.id">
                    {{alternative.title}}
                  </md-radio-button>
                  <div>remove<div>
                </div>
</md-radio-group>
```

if the div#problem has `fxLayout` directive the  `[(ngModel)]="question.answer"` in md-radio-group doesn't bind when the component is started, see below behavior when div#problem does not have `fxLayout` directive:

![example2](https://s9.postimg.org/9foqqi3xb/Screen_Shot_2017-06-21_at_22.04.48.png)

But if I add `fxLayout` directive, the bind does not work when the component is started.

![example1](https://s9.postimg.org/rtz9uhg7z/Screen_Shot_2017-06-21_at_20.36.40.png)

Demo: http://plnkr.co/edit/k3xXPY?p=preview
Simulate the behavior when you remove `fxLayout` in `div#problem`

Is the directive blocking the Angular Material of changing css?

**Comment by ThomasBurleson** [comment] 2017-06-22 14:28
@GustavoCostaW - please provide a Plunkr demo or source code to reproduce this issue.

**Comment by GustavoCostaW** [comment] 2017-06-22 14:43
@ThomasBurleson done! Simulate the behavior when you remove `fxLayou`t in `div#problem`

http://plnkr.co/edit/k3xXPY?p=preview

**Comment by ThomasBurleson** [comment] 2017-06-22 15:23
@GustavoCostaW - this is not a @angular/flex-layout issue. 

Here is a [Plunkr Demo](http://plnkr.co/edit/7UhbLX?p=preview) without any fxLayout directives. Notice that by simply adding a `class="" to the radio button `div` parent then the selected button highlight at startup fails:

![screen shot 2017-06-22 at 10 20 41 am](https://user-images.githubusercontent.com/210413/27442051-ceac1136-5734-11e7-9b71-75157f38bd80.png)



This is some weird issue with @angular/material.

**Comment by ThomasBurleson** [comment] 2017-06-22 15:24
Closing as not an @angular/flex-layout issue. Please report this issue on the [@angular/material](github.com/angular/material/issues/new) repository.

**Comment by GustavoCostaW** [comment] 2017-06-22 17:40
Hey @ThomasBurleson, thank you for the reply! I will make this :-)

**Comment by ThomasBurleson** [comment] 2017-06-22 22:00
Reopening:

@ThomasBurleson could you take a look at this plunker?

http://plnkr.co/edit/sVbxtBHtaXS9mh9ZC4ns?p=preview

It distills the problem down to a bare minimum. You can see on line 94 of main.ts that importing FlexLayoutModule causes the issue.

**Comment by Splaktar** [comment] 2017-07-05 05:40
Could this be related to https://github.com/angular/flex-layout/issues/127?

**Comment by ThomasBurleson** [comment] 2017-08-10 00:58
This [Plunkr](http://plnkr.co/edit/ZU9o0KSihqbKlT6rBjs1?p=preview) with latest build of FlexLayoutModule and latest release of Material shows everything working properly. 

> Closing as not-an-issue.

**Comment by etiennecrb** [comment] 2017-08-11 15:03
Hello!
I'm sorry but for me, the Plunkr shows the bug: it works only when you remove the class OR you remove FlexLayoutModule.

Very weird bug!

**Comment by ThomasBurleson** [comment] 2017-08-11 15:36
@etiennecrb - indeed. I am inclined to think this is an `@angular/material2` bug. Still researching...

**Comment by etiennecrb** [comment] 2017-08-11 16:00
Adding `{ descendants: true }` in `@ContentChildren` of `MdRadioGroup` makes things work.
When FlexLayoutModule is in the project, it appends `ng-reflect-class-base` on the `<div>` with the `*ngFor` and the class attribute. I'm not sure why FlexLayout makes that happen neither how it makes `@ContentChildren` fail...

**Comment by ThomasBurleson** [comment] 2017-08-11 16:11
Oh that is interesting. 

> The Flex-API defers all class active to the Angular Core `ClassDirective`; not sure why the core directive adds `ng-reflect-class-base`.

Can you report these findings as an issue with RadioGroup on the @angular/material2 repos ?

**Comment by ThomasBurleson** [comment] 2017-08-11 16:12
Closing this as not-an-issue for Flex-Layout.

**Comment by epere4** [comment] 2017-08-31 14:47
Was any bug in @angular/material2 opened for this in the end?

**Comment by etiennecrb** [comment] 2017-08-31 14:58
No, I haven't opened an issue yet.

**Comment by ThomasBurleson** [comment] 2017-08-31 15:49
@epere4, @etiennecrb - This has been fixed with SHA 301b563f93; see  https://github.com/angular/flex-layout/blob/master/src/demo-app/app/docs-layout/layoutAlignment.demo.html#L22-L26.

The 2-way databinding with ngModel (aka bananas-in-a-box) with ngModel needed both `name` attributes and `form` parent. Standalone usages are deprecated.

> For some reason, this error never surfaced for us until now.

**Comment by ThomasBurleson** [comment] 2017-08-31 18:37
After discussions with Angular material team, we are reopening for further investigation.

**Comment by ThomasBurleson** [comment] 2017-08-31 20:48
Refs #394 - May be fixed with removal of `[class]` selector.

**Comment by ThomasBurleson** [comment] 2017-08-31 20:56
````html
      <md-radio-group [(ngModel)]="question.answer" style="height:200px" name="answer">
        <div *ngFor="let alternative of question.alternatives" id="problem">
          <md-radio-button [value]="alternative.id"> {{alternative.title}} </md-radio-button>
          <div>remove</div>
        </div>
      </md-radio-group>
```
creates 
<img width="703" alt="screen shot 2017-08-31 at 3 54 00 pm" src="https://user-images.githubusercontent.com/210413/29944919-cbf52786-8e64-11e7-8a1f-b6163a2c5c5c.png">

-----

```html
<md-radio-group [(ngModel)]="question.answer" style="height:200px" name="answer">
  <div id="problem" fxLayout *ngFor="let alternative of question.alternatives" >
    <md-radio-button [value]="alternative.id"> {{alternative.title}} </md-radio-button>
    <div>remove</div>
  </div>
</md-radio-group>
```

creates

<img width="761" alt="screen shot 2017-08-31 at 3 53 21 pm" src="https://user-images.githubusercontent.com/210413/29944961-f52bad64-8e64-11e7-967d-f304095606b2.png">

**Comment by CaerusKaru** [comment] 2018-03-16 08:52
Is this still an issue?

**Comment by CaerusKaru** [comment] 2018-03-20 07:40
Closing since this hasn't been updated in a while. We can re-open if a followup is provided confirming this is still an issue.

**Closed by CaerusKaru** 2018-03-20 07:40 UTC
Labels: P3: important, can be closed?, related: material2
