### ISSUE TITLE
Allow injecting default MediaQuery value in SSR

### ISSUE THREAD

**Issue by pavel-agarkov** [angular/flex-layout#1003] opened 2019-01-21 12:05 UTC
# Feature Request

#### What is the desired behavior?
It should be possible to provide a custom default value for the MediaQuery on the servers side for FlexLayoutServerModule to use. Right now it always uses 'sm'. At least it supposed to use it but actually in 7.0.0-beta.23 it instead uses 'all' and simultaneously applies all impossible rules...

#### What is the use-case or motivation for the desired behavior?
Last MediaQuery value from the client side can be stored in cookies and used next time on the server side. In most cases user would have the same window size as from the last visit. Especially if it was a mobile device. So we can safely use it on the server side to generate a proper view. `flex-layout` library should not take care of last MediaQuery value storage. Only the way to override its default one is necessary.

#### Is there anything else we should know?
As I've mentioned above - in 7.0.0-beta.23 MediaQuery defaults to 'all' instead of 'sm' on the server side.

**Comment by CaerusKaru** [comment] 2019-01-21 14:40
Duplicate of #991

**Closed by CaerusKaru** 2019-01-21 14:40 UTC

**Comment by pavel-agarkov** [comment] 2019-01-21 16:05
@CaerusKaru , I could not find changes in the wiki you've mentioned in https://github.com/angular/flex-layout/issues/991#issuecomment-454592149
Do I understand correctly that instead of
```ts
FlexLayoutModule.withConfig({serverBreakpoints: ['md']})
```
I will need to inject 
```ts
{ provide: LAYOUT_CONFIG, useValue: { serverBreakpoints: ['md'] } }
```
Also why are there two values in your example `serverBreakpoints: ['md', 'gt-sm']` 
Does that mean that I need to provide all breakpoint that are true right now 
like if it is 'md' then ['md', 'gt-xs', 'gt-sm', 'lt-lg', 'lt-xl']?
Thank you.

**Comment by CaerusKaru** [comment] 2019-01-21 16:07
To your last point, yes. This is done because we don't want to restrict user's choices, and also because we can't possibly predict all overlaps when custom breakpoints are involved.

This feature hasn't been released yet. It will be in the next release. This is a duplicate though because it has already been addressed and implemented.

**Comment by pavel-agarkov** [comment] 2019-01-21 16:15
1)
> To your last point, yes. This is done because we don't want to restrict user's choices, and also because we can't possibly predict all overlaps when custom breakpoints are involved.

Yes, that makes sense. Thank you.

2)
> This feature hasn't been released yet. It will be in the next release. This is a duplicate though because it has already been addressed and implemented.

Yes, I understand.

But what about the first part: will it be possible to inject LAYOUT_CONFIG? Otherwise it will be impossible (or very hard...) to configure dynamically for each request.

**Comment by CaerusKaru** [comment] 2019-01-21 16:17
Yes, you can do that instead of using the static method. The static method just aliases to providing that token value

**Comment by tesnep** [comment] 2019-05-19 23:37
Is this the correct way to configure this?

` { provide: LAYOUT_CONFIG, useValue: {ssrObserveBreakpoints: ['xs', 'gt-xs', 'sm', 'gt-sm', 'md', 'lt-md', 'gt-md', 'gt-lg', 'lg', 'lt-lg', 'lt-xl']}},`
