### ISSUE TITLE
Status of this project?

### ISSUE THREAD

**Issue by MicMicMon** [angular/flex-layout#1174] opened 2020-01-21 15:29 UTC
What is the status of this project?

Is there a plan to go out of beta?

[This page](https://medium.com/angular-in-depth/angular-flex-layout-flexbox-and-grid-layout-for-angular-component-6e7c24457b63) warns that it is still in beta, not necessarily good for production work (grid API).

What is the reality, and what to expect with Angular v9?

Thanks

**Comment by CaerusKaru** [comment] 2020-01-21 15:30
Duplicate of #835

**Closed by CaerusKaru** 2020-01-21 15:30 UTC
