### ISSUE TITLE
fxLayoutGap puts the gap on the wrong side when using row-reverse

### ISSUE THREAD

**Issue by adamdport** [angular/flex-layout#450] opened 2017-10-11 18:10 UTC
```
<div fxLayout="row-reverse" fxLayoutGap="20px">
  <div>Right (margin is put on the right side of this<div>
  <div>Left<div>
</div>
```

Obviously `fxLayoutGap` should put the margin inbetween the divs, which switches when using `row-reverse`.

**Comment by yantrab** [comment] 2017-10-29 07:38
The same problem with rtl direction.

**Comment by grapgrap** [comment] 2017-12-26 09:14
The same problem with colume-reverse and fxFlexOrder.
```
<div fxLayout.gt-sm="row" fxLayout.lt-md="column" fxLayoutGap=".5em">
    <div fxFlex.gt-sm="2 0 auto" fxFlexOrder.gt-sm="1" fxFlex.lt-md="1 1 auto" fxFlexOrder.lt-md="2" class="card">
      <p>Left, Down</p>
    </div>
    <div fxFlex.gt-sm="1 0 auto" fxFlexOrder.gt-sm="2" fxFlex.lt-md="1 1 auto" fxFlexOrder.lt-md="1">
      <p>Rigth, Up</p>
    </div>
  </div>
```

**Comment by CaerusKaru** [comment] 2018-01-20 09:08
For the record, as it currently stands, this is documented and expected behavior. From the docs:

> `fxLayoutGap` does not respond to reveresed flow directions

That being said, I do believe it's behavior we should support, but perhaps not in the upcoming release.

**Comment by CaerusKaru** [comment] 2018-03-16 08:56
This will be partially fixed in #667, and has been patched for RTL behavior. I'll try and fold in a fix for standard `fxLayoutGap` as part of beta.14 instead of beta.15 (since it's more in line with that release)

**Closed** 2018-03-20 19:12 UTC
Labels: P4: minor, enhancement, has pr
