### ISSUE TITLE
Docs. Replace ObservableMedia with MediaObserver.

### ISSUE THREAD

**Issue by ph55** [angular/flex-layout#1340] opened 2021-04-20 10:49 UTC
`ObservableMedia` is deprecated. Remove it from docs.
Had to figure it out via the issues:

https://github.com/angular/flex-layout/issues/989

**Comment by CaerusKaru** [comment] 2021-04-20 16:39
Duplicate of #1040

**Closed by CaerusKaru** 2021-04-20 16:39 UTC
