### ISSUE TITLE
Links to API not working

### ISSUE THREAD

**Issue by alexpeshev** [angular/flex-layout#1402] opened 2022-05-30 12:51 UTC
Hi,

I've just noticed that the links to the grid static api are not working. For example, trying to access `gdRows`  by going to `https://github.com/angular/flex-layout/wiki/gdRows-API` just goes back to `https://github.com/angular/flex-layout/wiki/` instead.

It looks like those pages are missing.

**Comment by CaerusKaru** [comment] 2022-05-30 19:52
Duplicate of #1026

**Closed by CaerusKaru** 2022-05-30 19:52 UTC
