### ISSUE TITLE
The hover circle on material md-icon button is off when using fx-show / hide

### ISSUE THREAD

**Issue by geelus** [angular/flex-layout#105] opened 2017-01-09 22:19 UTC
When using fx-show / hide in a md-icon-button, the hover circle is a few pixels off. Here's a screenshot:
![image](https://cloud.githubusercontent.com/assets/13104312/21785948/cd34151e-d715-11e6-8c4e-da68a79a647e.png)

**Comment by ThomasBurleson** [comment] 2017-01-10 00:00
Issues are considered invalid without a working Plunkr or CodePen demo. 

---- 

Also here are some important guidelines for investigating a Layout issue:

* The Layout API is case-sensitive
  *  `fxlayout` is not valid
  *  `fxLayout` is valid
*  If you cannot get Flex-Layout to work with an example, try to manually use CSS flexbox stylings. If that still does not work to achieve your goals, then Flex-Layout is <u>**not**</u> the issue.
*  If hand-crafted CSS resolves the issue, but Flex-Layout does not then we **definitely** have a bug in this repository.

---- 

#### Templates 

* [Plunkr Template](https://plnkr.co/edit/h8hzyoEyqdCXmTBA7DfK?p=info)
* [Plunkr Template with Material2](https://plnkr.co/edit/rkF70n7X4Yv8WmP4Thu5?p=preview)

**Comment by geelus** [comment] 2017-01-10 00:24
Never mind. Someone else will hopefully have enough time to do the plunker. I unfortunately don't.

**Comment by geelus** [comment] 2017-01-10 00:34
By the way, it happens when I show/hide OTHER icons that are on the very right side.

Hopefully I'll get some time to complete the plunker link later. Thanks anyway, you are always very fast.

**Comment by geelus** [comment] 2017-01-10 00:57
As much as i wanted to reproduce this on plunker, unfortunately I can't. You can check the plunker but it's working fine. I guess this is related to material not flexbox but in the meanwhile it only happens when i use flex-box :(
https://plnkr.co/edit/KBoQJTNqCzgeviEIsUTF?p=preview

**Comment by geelus** [comment] 2017-01-10 01:41
Here you are:
https://plnkr.co/edit/P7Faj908RgiY84Ih3ivQ?p=preview

Finally!

**Comment by ThomasBurleson** [comment] 2017-01-10 02:59
@geelus - wonderful. we will investigate.

**Comment by d3viant0ne** [comment] 2017-01-10 03:02
I actually just ran into this myself, looking into what's stepping on the circle now.

**Comment by geelus** [comment] 2017-01-10 06:21
I fixed it by wrapping my button in a div and then applying the fxShow/fxHide to the div.

**Comment by d3viant0ne** [comment] 2017-01-11 05:22
@geelus  - The difference between `md-icon-button` with / without fxShow is the height & width on `md-button-wrapper`

- Without `fxShow` height & width are set to `auto` ( in the demo that's 40x40 ) and the icon is properly aligned.

- With `fxShow` height & width are set to pixel values ( in the demo that's 23.9931x40 ) and the icon is left justified.

While wrapping the element in a `<div> ` is a viable workaround, we shouldn't be stepping on element styles :)

**Comment by ThomasBurleson** [comment] 2017-01-11 06:01
@d3viant0ne - fxShow/fxHide simply set the display to `none` or `flex`.
I am not sure how that would change the px values from `auto` to px values.

**Comment by d3viant0ne** [comment] 2017-01-11 06:17
@ThomasBurleson - Nor am I. Looking at the code, the problem isn't actually in fxShow as like you said, it doesn't do much. 

The above is less of a cause and more of an end result, still working on why we are ending up with the above when applying `fxShow`.

**Comment by ThomasBurleson** [comment] 2017-01-23 04:06
The fxHide and fxShow should not change the display mode to 'flex'. Instead the display mode (when not 'none') should be the default (=== 'block') or the explicitly assigned display mode for that element.

**Comment by ThomasBurleson** [comment] 2017-01-23 04:12
@geelus, @d3viant0ne - see PR #121.

**Comment by geelus** [comment] 2017-01-23 07:46
@ThomasBurleson It doesn't seem to have been fixed in beta 3 or at least doesn't work for me. Can you please have this plunker working?
https://plnkr.co/edit/P7Faj908RgiY84Ih3ivQ?p=preview

**Comment by ThomasBurleson** [comment] 2017-01-23 09:57
@geelus - please note that the fixes are in a Pull Request that have NOT been merged nor released: https://github.com/angular/flex-layout/issues/121

**Comment by geelus** [comment] 2017-01-23 10:26
@ThomasBurleson Thanks for clarification. So I'll check next version (beta 4)

**Closed** 2017-01-24 22:16 UTC
Labels: bug, has Pull Request
