### ISSUE TITLE
Please stop adding "-beta" to every release

### ISSUE THREAD

**Issue by DenysVuika** [angular/flex-layout#1282] opened 2020-07-06 06:35 UTC
# Feature Request

#### What is the desired behavior?

We would like to see a normal library versioning without mimicking the old gmail era and permanent beta suffixes.

#### What is the use-case or motivation for the desired behavior?

We have to explain to end developers and customers that flex beta is safe to use all of the time

**Comment by CaerusKaru** [comment] 2020-07-06 06:36
Duplicate of #835

**Closed by CaerusKaru** 2020-07-06 06:36 UTC
