### ISSUE TITLE
Release stable version vs beta

### ISSUE THREAD

**Issue by bond-** [angular/flex-layout#914] opened 2018-12-14 18:48 UTC
# Feature Request

#### What is the desired behavior?
Require a reliable stable version vs betas of different versions for use in an enterprise project

#### What is the use-case or motivation for the desired behavior?
It would be difficult to convince adding beta versions of software in an enterprise setting. The motivation behind using flex-layout is for using material design.

**Comment by CaerusKaru** [comment] 2018-12-14 19:01
Duplicate of #835

**Closed by CaerusKaru** 2018-12-14 19:01 UTC
