### ISSUE TITLE
7.0.0-beta.22: Cannot read property 'split' of undefined TS error

### ISSUE THREAD

**Issue by attilacsanyi** [angular/flex-layout#951] opened 2018-12-21 14:50 UTC
# Bug Report

#### What is the expected behavior?
Layout can change without any TS error in console

#### What is the current behavior?
```
ERROR TypeError: Cannot read property 'split' of undefined
    at DefaultLayoutAlignDirective.push../node_modules/@angular/flex-layout/esm5/flex.es5.js.LayoutAlignDirective.onLayoutChange (flex.es5.js:1546)
    at...
```

#### What are the steps to reproduce?
`<div fxFlex.gt-sm="40%" fxFlex.gt-md="30%"></div>`

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Material 7.2.0, Angular 7.1.4 TS 3.2.1

**Comment by CaerusKaru** [comment] 2018-12-21 14:54
Duplicate of #947

**Closed by CaerusKaru** 2018-12-21 14:54 UTC
