### ISSUE TITLE
AOT build throwing the error: Function calls are not supported in decorators but ‘FlexLayoutModule’ was called, when using withConfig options

### ISSUE THREAD

**Issue by hags033** [angular/flex-layout#778] opened 2018-06-12 20:35 UTC
# Bug Report

#### What is the expected behavior?
App should build in AOT when FlexLayoutModule.withConfig({addFlexToParent: false}) is added to the module.

#### What is the current behavior?
App fails to build in AOT with error:  Function calls are not supported in decorators but ‘FlexLayoutModule’ was called, when using withConfig options

#### What are the steps to reproduce?
include in Module: FlexLayoutModule.withConfig({addFlexToParent: false})

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.0.4, Material 6.2.1

#### Is there anything else we should know?
We have another module:     LocalStorageModule.withConfig({ prefix: '', storageType: 'localStorage' }) that builds fine.

**Comment by CaerusKaru** [comment] 2018-06-12 20:36
I've included it in our demo-app with no issue. Please provide either a StackBlitz or a minimal reproduction repository that demonstrates this behavior.

**Comment by hags033** [comment] 2018-06-12 20:56
I've also included it in your demo app, but unsure if it's building in AOT, we have another separate app, I added the same line to the app module, and still get this error: ERROR in Error during template compile of 'AppModule'
  Function calls are not supported in decorators but 'FlexLayoutModule' was called.
node_modules/@angular/flex-layout/typings/module.d.ts(12,37): error TS1183: An implementation cannot be declared in ambient contexts

**Comment by CaerusKaru** [comment] 2018-06-12 21:01
Without an actual reproduction, we cannot investigate this issue.

**Comment by TechRazor** [comment] 2018-06-13 17:22
@CaerusKaru, I'm facing the same issue when upgrading to the latest release and using the ".withConfig()" option. I have created a reproduction by using angular-cli to create a new project, then npm add the flex-layout and cdk dependencies, then import FlexLayoutModule.withConfig({ addFlexToParent: true }) to the app.module.ts imports. After this you only need to run "ng build --prod" to get the error. You can clone my repo to test it, https://github.com/TechRazor/flex-layout-demo

Also I only get the error with "ng build --prod" and no errors with dev build using "ng serve" or "ng build".

Thanks,
-James

**Comment by CaerusKaru** [comment] 2018-06-13 21:20
@hags033 @TechRazor Thank you for bringing this to my attention. I was finally able to replicate this, and thankfully the fix is pretty straight-forward. In case you're curious, it's caused by attempting to provide the default options if none are available eagerly in the static method instead of just setting them where they're used. The PR to fix this makes that change.

@ThomasBurleson is OOTO for the next few weeks, but you're welcome to pull the fix and build locally until we can get it merged.

**Comment by TechRazor** [comment] 2018-06-13 21:40
@CaerusKaru Thank you for the quick fix!

**Comment by simeyla** [comment] 2018-06-20 06:33
What's the workaround for now without pulling the fix?

Is there an alternative way to set config - such as with a custom breakpoints provider like we used to do? Can I still use that?

**Comment by simeyla** [comment] 2018-06-20 06:42
##Workaround

As a workaround you can provide the `FlexLayoutModule` like this:

```
imports: [
    BrowserModule,
    BrowserAnimationsModule,
    {
        ngModule: FlexLayoutModule,
        providers: [
            {
                provide: LAYOUT_CONFIG,
                useValue: {
                    addFlexToParent: true,
                    addOrientationBps: false,
                    disableDefaultBps: false,
                    disableVendorPrefixes: false,
                    serverLoaded: false,
                    useColumnBasisZero: true
                 }
            },
            {
                provide: BREAKPOINT,
                useValue: CUSTOM_BREAKPOINTS
            }
        ]
    },
```

These are the [default options](https://github.com/angular/flex-layout/blob/f01e55178859ad6c6a4cb18e8ad3ec88c5b87b56/src/lib/core/tokens/library-config.ts) for the config, so change here if you need to vary them.

I came up with this by basically extracting the implementation for [`withConfig()`](https://github.com/angular/flex-layout/blob/master/src/lib/module.ts). This will now work with AOT.

If you aren't using custom breakpoints then remove the provider for `BREAKPOINT`. If you're using serverLoaded then you need to add a provide for that.

**Closed** 2018-07-02 19:11 UTC
Labels: P0, bug, has pr

**Comment by rmathi** [comment] 2019-02-07 07:04
> @hags033 @TechRazor Thank you for bringing this to my attention. I was finally able to replicate this, and thankfully the fix is pretty straight-forward. In case you're curious, it's caused by attempting to provide the default options if none are available eagerly in the static method instead of just setting them where they're used. The PR to fix this makes that change.
> 
> @ThomasBurleson is OOTO for the next few weeks, but you're welcome to pull the fix and build locally until we can get it merged.

Hi. My doubt/question is..Why the "fxFlex directive " are getting added automatically when AOT compiler on not JIT ? could you anyone please  tell me that Why its happening only for AOT on not  JIT.. @hags033 @CaerusKaru @TechRazor

**Comment by rmathi** [comment] 2019-02-08 05:09
@Angular ....
Could please tell me that why you are deleting the post instead of providing solution for this ?

My question was, "Hi All, In my application using Angular 7, Angular Material & typescript and **FlexLayout** are latest version. The problem is FlexLayout styles are getting added automatically when AOT compiler ON not JIT compiler. When i turned off AOT compiler the styles are not added. Also tried to set flexlayout config `FlexLayoutModule.withConfig({addFlexToParent: false});` but it doesn't help.

So, could please explain anyone why its applying only when AOT ON not in JIT ? and how to remove the automatically added styles?
Thanks in Advance."..
