### ISSUE TITLE
[solved] Custom breakpoints not working after upgrading to Angular 8

### ISSUE THREAD

**Issue by Saied-Za** [angular/flex-layout#1073] opened 2019-05-29 20:13 UTC
# Bug Report
Hello. ngClass and ngStyle are not working when used with custom breakpoints after upgrading angular version from 7 to 8.

#### What is the expected behavior?
ngClass and ngStyle should be working ( when used with custom breakpoints ) as they are working in angular version 7

#### What is the current behavior?
an error is thrown when trying to use one of these directives with a custom defined breakpoint
error message : (No provider for NgClassImpl!)

#### What are the steps to reproduce?
minimal StackBlitz version: 
https://stackblitz.com/github/Saied-Za/Angular-FlexLayout

**Comment by CaerusKaru** [comment] 2019-05-30 04:34
I'm not seeing issues using the StackBlitz demo, are there any special reproduction steps?

**Comment by CaerusKaru** [comment] 2019-05-30 04:38
Ok, I know why this is happening, and it's very much due to a lack of documentation on our part.

When Angular v8 came out, they changed the internal API for `NgClass` and `NgStyle`, which Angular Layout extends. We patched this in our own directives, but we couldn't do this for the base directive that's extended for custom breakpoints. We _do_ export a provider for both classes to patch this behavior. To resolve this issue, do the following:

```ts
import {Directive} from '@angular/core';
import {LayoutNgClassImplProvider, ClassDirective} from '@angular/flex-layout';

@Directive({selector, inputs, providers: [LayoutNgClassImplProvider]})
export class MyCustomDirective extends ClassDirective {
  ...
}
```

**Comment by Saied-Za** [comment] 2019-05-30 06:42
Thanks for quick response.

**Comment by CaerusKaru** [comment] 2019-05-30 06:43
I’m going to keep this issue open for people with the same problem, at least until we find a way to document this.

**Comment by CristianPumaES6** [comment] 2019-06-06 01:54
Thanks for to keep this issue open!!

🗡  Estoy buscando trabajo :d para empezar a estudiar la carrera de ciencias de la computacion en la UTEC soy de peru egresado de la carrera de computacion informatica.
Me considero un buen developer, maquetador, manejo angular, react, python, java, un poco de arduino entre otras cosas soy autodidacta.

Me gusta la musica.

Codeo con estos ritmo https://www.youtube.com/watch?v=EGuGPJfHPjo

Tengo un certificado Area 51 , Developer en python.

Quiero mi titulo de cc y aprender ingles para algun dia trabajar en Google como developer.

https://www.linkedin.com/in/cristianpumaes6/
https://www.facebook.com/GrpAfro

Gracias por leer.
Saludos y exitos!

**Comment by Gajendrasinh** [comment] 2019-06-14 10:12
Hello

I am also getting some issue after migrate in angular 8.

$ ng build --prod

Date: 2019-06-14T10:05:33.026Z
Hash: be25203cc6b9bbfcd8aa
Time: 22540ms
chunk {0} runtime-es5.9c308a63d02029c20228.js (runtime) 1.41 kB [entry] [rendered]
chunk {1} main-es5.4af9b61479361f268d39.js (main) 128 bytes [initial] [rendered]
chunk {2} polyfills-es5.374878e7def8b1ff61fc.js (polyfills) 68 kB [initial] [rendered]
chunk {3} styles.defc9adae861d8a413d0.css (styles) 144 kB [initial] [rendered]
chunk {scripts} scripts.613511dc7eb70f096b79.js (scripts) 424 kB [entry] [rendered]

ERROR in Error during template compile of 'OpaqueToken'
  Function calls are not supported in decorators but 'makeDecorator' was called in 'Injectable'
    'Injectable' calls 'makeDecorator'.

**Comment by SerkanSipahi** [comment] 2019-07-01 09:50
I have the same issue!

**Comment by wlr** [comment] 2019-07-17 16:48
I have kind a same issue in Angular 8.
I use constructor(@Self ngClass:NgClass) as injection to manually set classes on the host component and run into the same runtime error (No provider for NgClassImpl). I implemented a custom directive as you advised, but same error.

What i did wrong? Thanks!

**Comment by levgaas** [comment] 2019-08-05 13:38
@wlr 

```
providers: [
  {
    provide: ɵNgClassImpl,
    useClass: ɵNgClassR2Impl,
  },
],
```

and then in component

```
constructor(@Self() @Optional() ngClassInstance: NgClass, ngClassDelegate: ɵNgClassImpl) {
  this._ngClass = ngClassInstance || new NgClass(ngClassDelegate);
}
```

**Comment by CaerusKaru** [comment] 2020-05-09 22:39
This patch has been removed in the recent versions of Angular and Angular Layout, so I'm closing this as not needed anymore.

**Closed by CaerusKaru** 2020-05-09 22:39 UTC
Labels: P2, docs
