### ISSUE TITLE
fxFlex flex-basis doesn't work like css flex flex-basis: sets max-with and min-width 

### ISSUE THREAD

**Issue by aleixsuau** [angular/flex-layout#625] opened 2018-02-19 10:26 UTC
#### Bug, feature request, or proposal:
fxFlex flex-basis doesn't work like css flex flex-basis: fxFlex is setting a max-with and min-width so the elements works like with a fixed size, it doesn't grow or shrink to fit the available space.

#### What is the expected behavior?
fxFlex flex-basis should work like flex flex-basis.

#### What is the current behavior?
fxFlex is setting a max-with and min-width so the element works like with a fixed size, it doesn't grow or shrink to fit the available space.

#### What are the steps to reproduce?
Here you can compare a fxFlex and css flex behaviours:
https://stackblitz.com/edit/flex-layout-issue?file=app%2Fapp.component.html

#### What is the use-case or motivation for changing an existing behavior?
It is not flexible nor intuitive.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/core 5.0.0 and @angular/flex-layout 2.0.0-beta.12

#### Is there anything else we should know?
Great work anyway, flexLayout is awesome :)

**Comment by CaerusKaru** [comment] 2018-02-19 18:14
Duplicate of #538

**Closed by CaerusKaru** 2018-02-19 18:14 UTC

**Comment by aleixsuau** [comment] 2018-04-26 09:05
Hi @CaerusKaru , 
I think this is not a duplicate of #538,  #538 is a feature/fix proposal and this is a bug report.

I saw that  #538 was closed, but this bug remains in the latest version.

Please take a look at the [stackblitz](https://stackblitz.com/edit/flex-layout-issue?file=app%2Fapp.component.html) and resize the window to see that fxFlex="1 1 250px" is not working like style="flex: 1 1 250px;". In fact fxFlex="1 1 250px" works like style="flex: 1 0 250px;", with 0 shrink.

I guess the cause is that fxFlex is setting a max-with and min-width so the element works like with a fixed size, it doesn't shrink to fit the available space.

Thanks!

**Comment by CaerusKaru** [comment] 2018-04-26 09:49
Then this is a duplicate of #689 and #438
