### ISSUE TITLE
Error in styles.d.ts

### ISSUE THREAD

**Issue by krbaio3** [angular/flex-layout#830] opened 2018-09-01 21:06 UTC
# Bug Report

#### What is the expected behavior?

Working

#### What is the current behavior?

When I install @angular/flex-layout in un new project with ng-cli
 ```bash
$: ng new angularFlex --style=scss
$: cd angularFlex
$: npm install -S @angular/flex-layout
```
and to add the dependecies into app.module.ts

```javascript
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppComponent } from './app.component';

import { FlexLayoutModule } from '@angular/flex-layout';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    FlexLayoutModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

and I run the project with 
```
$: npm start
```

The console throw this error:

```bash
ERROR in node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(72,67): error TS1144: '{' or ';' expected.
node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(74,5): error TS1128: Declaration or statement expected.
node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(74,33): error TS1005: ';' expected.
node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(74,39): error TS1109: Expression expected.
node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(79,5): error TS1128: Declaration or statement expected.
node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(80,1): error TS1128: Declaration or statement expected.

```
#### What are the steps to reproduce?

Create a new project with angular-cli and install the package @angular/flex-layout and add the dependencie into app.module.ts

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

| Description  | Version  |
|---|---|
| OS  | Ubuntu 16.04  |
| Node  | 10.9.0  |
| NPM  | 6.4.1  |

**Versions Angular-CLI and package.json**

Angular CLI: 6.1.5
Angular: 6.1.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

| Package | Version |
|---|---|
| @angular-devkit/architect | 0.7.5 |
| @angular-devkit/build-angular | 0.7.5 |
| @angular-devkit/build-optimizer | 0.7.5 |
| @angular-devkit/build-webpack |  0.7.5 |
| @angular-devkit/core | 0.7.5 |
| @angular-devkit/schematics | 0.7.5 |
| @angular/cli | 6.1.5 |
| @angular/flex-layout | 6.0.0-beta.18 |
| @ngtools/webpack | 6.1.5 | 
| @schematics/angular | 0.7.5 |
| @schematics/update | 0.7.5 |
| rxjs | 6.3.1 |
| typescript | 2.7.2 |
| webpack | 4.9.2 |

**Comment by CaerusKaru** [comment] 2018-09-01 21:07
Duplicate of #827. Either upgrade TypeScript to 2.9 or downgrade RxJS to 6.2

**Closed by CaerusKaru** 2018-09-01 21:07 UTC
