### ISSUE TITLE
Cannot read property 'createElement' of undefined MatchMedia

### ISSUE THREAD

**Issue by bostondevin** [angular/flex-layout#665] opened 2018-03-14 20:29 UTC
#### Bug, feature request, or proposal:

Getting errors when adding a simple flex layout component (any) to my app
```

<div fxLayout="row">
      <div fxFlex="33"> 
      </div>
      <div fxFlex="67"> 
      </div>
</div>

```

#### What is the expected behavior?

No errors

#### What is the current behavior?

Getting this error referring to the line where the fxFlex is:

TypeError: Cannot read property 'createElement' of undefined
    at MatchMedia._prepareQueryCSS (flex-layout.es5.js:1515)
    at MatchMedia.registerQuery (flex-layout.es5.js:1439)
    at MediaMonitor._registerBreakpoints (flex-layout.es5.js:1712)
    at new MediaMonitor (flex-layout.es5.js:1606)
    at MEDIA_MONITOR_PROVIDER_FACTORY (flex-layout.es5.js:6961)
    at _callFactory (core.js:10920)
    at _createProviderInstance$1 (core.js:10868)
    at resolveNgModuleDep (core.js:10850)
    at NgModuleRef_.get (core.js:12087)
    at resolveDep (core.js:12577)
MatchMedia._prepareQueryCSS @ flex-layout.es5.js:1526
MatchMedia.registerQuery @ flex-layout.es5.js:1439
MediaMonitor._registerBreakpoints @ flex-layout.es5.js:1712
MediaMonitor @ flex-layout.es5.js:1606
MEDIA_MONITOR_PROVIDER_FACTORY @ flex-layout.es5.js:6961
_callFactory @ core.js:10920
_createProviderInstance$1 @ core.js:10868
resolveNgModuleDep @ core.js:10850
NgModuleRef_.get @ core.js:12087
resolveDep @ core.js:12577
createClass @ core.js:12443
createDirectiveInstance @ core.js:12284
createViewNodes @ core.js:13742
callViewAction @ core.js:14176
execComponentViewsAction @ core.js:14085
createViewNodes @ core.js:13770
createRootView @ core.js:13631
callWithDebugContext @ core.js:15056
debugCreateRootView @ core.js:14339
ComponentFactory_.create @ core.js:11236
ComponentFactoryBoundToModule.create @ core.js:4023
ViewContainerRef_.createComponent @ core.js:11433
DynamicComponent.ngOnInit @ _base.ts:138
checkAndUpdateDirectiveInline @ core.js:12369
checkAndUpdateNodeInline @ core.js:13893
checkAndUpdateNode @ core.js:13836
debugCheckAndUpdateNode @ core.js:14729
debugCheckDirectivesFn @ core.js:14670
(anonymous) @ DndTree.ts.DndTree.html:34
debugUpdateDirectives @ core.js:14655
checkAndUpdateView @ core.js:13802
callViewAction @ core.js:14153
execEmbeddedViewsAction @ core.js:14111
checkAndUpdateView @ core.js:13803
callViewAction @ core.js:14153
execEmbeddedViewsAction @ core.js:14111
checkAndUpdateView @ core.js:13803
callViewAction @ core.js:14153
execEmbeddedViewsAction @ core.js:14111
checkAndUpdateView @ core.js:13803
callViewAction @ core.js:14153
execComponentViewsAction @ core.js:14085
checkAndUpdateView @ core.js:13808
callViewAction @ core.js:14153
execEmbeddedViewsAction @ core.js:14111
checkAndUpdateView @ core.js:13803
callViewAction @ core.js:14153
execEmbeddedViewsAction @ core.js:14111
checkAndUpdateView @ core.js:13803
callViewAction @ core.js:14153
execComponentViewsAction @ core.js:14085
checkAndUpdateView @ core.js:13808
callViewAction @ core.js:14153
execComponentViewsAction @ core.js:14085
checkAndUpdateView @ core.js:13808
callViewAction @ core.js:14153
execComponentViewsAction @ core.js:14085
checkAndUpdateView @ core.js:13808
callViewAction @ core.js:14153
execEmbeddedViewsAction @ core.js:14111
checkAndUpdateView @ core.js:13803
callViewAction @ core.js:14153
execComponentViewsAction @ core.js:14085
checkAndUpdateView @ core.js:13808
callWithDebugContext @ core.js:15056
debugCheckAndUpdateView @ core.js:14593
ViewRef_.detectChanges @ core.js:11577
(anonymous) @ core.js:5907
ApplicationRef.tick @ core.js:5907
(anonymous) @ core.js:5740
ZoneDelegate.invoke @ zone.js:388
onInvoke @ core.js:4749
ZoneDelegate.invoke @ zone.js:387
Zone.run @ zone.js:138
NgZone.run @ core.js:4566
next @ core.js:5740
schedulerFn @ core.js:4331
SafeSubscriber.__tryOrUnsub @ Subscriber.js:240
SafeSubscriber.next @ Subscriber.js:187
Subscriber._next @ Subscriber.js:128
Subscriber.next @ Subscriber.js:92
Subject.next @ Subject.js:56
EventEmitter.emit @ core.js:4311
checkStable @ core.js:4714
onLeave @ core.js:4793
onInvokeTask @ core.js:4743
ZoneDelegate.invokeTask @ zone.js:420
Zone.runTask @ zone.js:188
ZoneTask.invokeTask @ zone.js:496
invokeTask @ zone.js:1517
globalZoneAwareCallback @ zone.js:1543
XMLHttpRequest.send (async)
scheduleTask @ zone.js:2935
ZoneDelegate.scheduleTask @ zone.js:407
onScheduleTask @ zone.js:297
ZoneDelegate.scheduleTask @ zone.js:401
Zone.scheduleTask @ zone.js:232
Zone.scheduleMacroTask @ zone.js:255
scheduleMacroTaskWithCurrentZone @ zone.js:1092
(anonymous) @ zone.js:2967
proto.(anonymous function) @ zone.js:1372
(anonymous) @ http.js:1640
Observable._trySubscribe @ Observable.js:172
Observable.subscribe @ Observable.js:160
MapOperator.call @ map.js:57
Observable.subscribe @ Observable.js:157
MapOperator.call @ map.js:57
Observable.subscribe @ Observable.js:157
CatchOperator.call @ catchError.js:80
Observable.subscribe @ Observable.js:157
elemFunction @ ngx-restangular.js:396
wrapper @ lodash.js:4941
getFunction @ ngx-restangular.js:405
wrapper @ lodash.js:4941
AppService.get @ app.service.ts:726
AppBuilder.getTemplate @ builder.ts:204
(anonymous) @ builder.ts:164
wrappedComplete @ Subscriber.js:223
SafeSubscriber.__tryOrUnsub @ Subscriber.js:240
SafeSubscriber.complete @ Subscriber.js:225
Subscriber._complete @ Subscriber.js:135
Subscriber.complete @ Subscriber.js:117
Subscriber._complete @ Subscriber.js:135
Subscriber.complete @ Subscriber.js:117
Subject.complete @ Subject.js:84
resolvePromise @ ngx-restangular.js:145
okCallback @ ngx-restangular.js:302
SafeSubscriber.__tryOrUnsub @ Subscriber.js:240
SafeSubscriber.next @ Subscriber.js:187
Subscriber._next @ Subscriber.js:128
Subscriber.next @ Subscriber.js:92
Subscriber._next @ Subscriber.js:128
Subscriber.next @ Subscriber.js:92
MapSubscriber._next @ map.js:85
Subscriber.next @ Subscriber.js:92
MapSubscriber._next @ map.js:85
Subscriber.next @ Subscriber.js:92
onLoad @ http.js:1591
ZoneDelegate.invokeTask @ zone.js:421
onInvokeTask @ core.js:4740
ZoneDelegate.invokeTask @ zone.js:420
Zone.runTask @ zone.js:188
ZoneTask.invokeTask @ zone.js:496
invokeTask @ zone.js:1517
globalZoneAwareCallback @ zone.js:1543
XMLHttpRequest.send (async)
scheduleTask @ zone.js:2935
ZoneDelegate.scheduleTask @ zone.js:407
onScheduleTask @ zone.js:297
ZoneDelegate.scheduleTask @ zone.js:401
Zone.scheduleTask @ zone.js:232
Zone.scheduleMacroTask @ zone.js:255
scheduleMacroTaskWithCurrentZone @ zone.js:1092
(anonymous) @ zone.js:2967
proto.(anonymous function) @ zone.js:1372
(anonymous) @ http.js:1640
Observable._trySubscribe @ Observable.js:172
Observable.subscribe @ Observable.js:160
MapOperator.call @ map.js:57
Observable.subscribe @ Observable.js:157
MapOperator.call @ map.js:57
Observable.subscribe @ Observable.js:157
CatchOperator.call @ catchError.js:80
Observable.subscribe @ Observable.js:157
fetchFunction @ ngx-restangular.js:306
apply @ lodash.js:467
wrapper @ lodash.js:5329
AppService.get @ app.service.ts:728
AppBuilder.ngOnInit @ builder.ts:143
checkAndUpdateDirectiveInline @ core.js:12369
checkAndUpdateNodeInline @ core.js:13893
checkAndUpdateNode @ core.js:13836
debugCheckAndUpdateNode @ core.js:14729
debugCheckDirectivesFn @ core.js:14670
(anonymous) @ builder.ts.AppBuilder.html:14
debugUpdateDirectives @ core.js:14655
checkAndUpdateView @ core.js:13802
callViewAction @ core.js:14153
execEmbeddedViewsAction @ core.js:14111
checkAndUpdateView @ core.js:13803
callViewAction @ core.js:14153
execComponentViewsAction @ core.js:14085
checkAndUpdateView @ core.js:13808
callWithDebugContext @ core.js:15056
debugCheckAndUpdateView @ core.js:14593
ViewRef_.detectChanges @ core.js:11577
(anonymous) @ core.js:5907
ApplicationRef.tick @ core.js:5907
(anonymous) @ core.js:5740
ZoneDelegate.invoke @ zone.js:388
onInvoke @ core.js:4749
ZoneDelegate.invoke @ zone.js:387
Zone.run @ zone.js:138
NgZone.run @ core.js:4566
next @ core.js:5740
schedulerFn @ core.js:4331
SafeSubscriber.__tryOrUnsub @ Subscriber.js:240
SafeSubscriber.next @ Subscriber.js:187
Subscriber._next @ Subscriber.js:128
Subscriber.next @ Subscriber.js:92
Subject.next @ Subject.js:56
EventEmitter.emit @ core.js:4311
checkStable @ core.js:4714
onHasTask @ core.js:4762
ZoneDelegate.hasTask @ zone.js:441
ZoneDelegate._updateTaskCount @ zone.js:461
Zone._updateTaskCount @ zone.js:285
Zone.runTask @ zone.js:205
drainMicroTaskQueue @ zone.js:595
Promise.then (async)
scheduleMicroTask @ zone.js:578
ZoneDelegate.scheduleTask @ zone.js:410
onScheduleTask @ zone.js:297
ZoneDelegate.scheduleTask @ zone.js:401
Zone.scheduleTask @ zone.js:232
Zone.scheduleMicroTask @ zone.js:252
scheduleResolveOrReject @ zone.js:856
ZoneAwarePromise.then @ zone.js:946
RouterInitializer.appInitializer @ router.js:7338
ApplicationInitStatus.runInitializers @ core.js:3573
(anonymous) @ core.js:5500
_callAndReportToErrorHandler @ core.js:5679
(anonymous) @ core.js:5498
ZoneDelegate.invoke @ zone.js:388
onInvoke @ core.js:4749
ZoneDelegate.invoke @ zone.js:387
Zone.run @ zone.js:138
NgZone.run @ core.js:4566
PlatformRef.bootstrapModuleFactory @ core.js:5489
(anonymous) @ main.ts:20
./src/main.ts @ main.bundle.js:788
__webpack_require__ @ inline.bundle.js:55
0 @ main.bundle.js:796
__webpack_require__ @ inline.bundle.js:55
webpackJsonpCallback @ inline.bundle.js:26
(anonymous) @ main.bundle.js:1
HorizontalBox.ts.HorizontalBoxComponent.html:4 ERROR TypeError: Cannot read property 'subscribe' of undefined
    at new FlexDirective (flex-layout.es5.js:3255)
    at createClass (core.js:12449)
    at createDirectiveInstance (core.js:12284)
    at createViewNodes (core.js:13742)
    at callViewAction (core.js:14176)
    at execComponentViewsAction (core.js:14085)
    at createViewNodes (core.js:13770)
    at createRootView (core.js:13631)
    at callWithDebugContext (core.js:15056)
    at Object.debugCreateRootView [as createRootView] (core.js:14339)

#### What are the steps to reproduce?
Providing a StackBlitz (or similar) is the *best* way to get the team to see your issue.

latest npm, package is all latest:

"dependencies": {
    "@angular/animations": "^5.2.8",
    "@angular/cdk": "^5.2.4",
    "@angular/common": "^5.2.8",
    "@angular/compiler": "^5.2.8",
    "@angular/core": "^5.2.8",
    "@angular/flex-layout": "^5.0.0-beta.13",
    "@angular/forms": "^5.2.8",
    "@angular/http": "^5.2.8",
    "@angular/platform-browser": "^5.2.8",
    "@angular/platform-browser-dynamic": "^5.2.8",
    "@angular/platform-server": "^5.2.8",
    "@angular/router": "^5.2.8",
    "@angular/service-worker": "^5.2.8",
    "@ng-bootstrap/ng-bootstrap": "^1.0.1",
    "@ngx-translate/core": "^9.1.1",
    "@swimlane/ngx-datatable": "^11.2.0",
    "@swimlane/ngx-dnd": "^3.1.3",
    "@swimlane/ngx-ui": "^20.1.1",
    "@types/deep-diff": "0.0.31",
    "ack-angular-webcam": "^1.9.1",
    "angular-froala-wysiwyg": "^2.7.6",
    "angular-resizable-element": "^2.0.0",
    "angular2-hotkeys": "^2.0.4",
    "angular2-moment": "^1.8.0",
    "angular2-signaturepad": "^2.7.0",
    "angular2-uuid": "^1.1.1",
    "ap-angular2-fullcalendar": "^1.3.7",
    "aws-sdk": "^2.209.0",
    "bluebird": "^3.5.1",
    "body-parser": "^1.18.2",
    "bootstrap": "^4.0.0",
    "bootswatch": "^4.0.0",
    "codemirror": "^5.35.0",
    "core-js": "^2.5.3",
    "cors": "^2.8.4",
    "deep-diff": "0.3.8",
    "express": "^4.16.3",
    "express-cors": "0.0.3",
    "express-locale": "^1.0.4",
    "express-ntlm": "^2.2.4",
    "font-awesome": "^4.7.0",
    "fullcalendar": "^3.9.0",
    "icalevent": "^0.3.2",
    "jquery": "^3.3.1",
    "jwt-simple": "^0.5.1",
    "localStorage": "^1.0.3",
    "localforage": "^1.6.0",
    "lodash": "^4.17.5",
    "method-override": "^2.3.10",
    "moment": "^2.21.0",
    "mongoose": "^5.0.10",
    "mongoose-deep-populate": "^3.1.1",
    "mongoose-findorcreate": "^3.0.0",
    "mongoose-gen": "^2.1.1",
    "mongoose-i18n-localize": "^0.3.0",
    "msinghthakur": "^2.2.0",
    "multer": "^1.3.0",
    "multer-s3": "^2.7.0",
    "ng-contenteditable": "^1.0.5",
    "ng-socket-io": "^0.2.4",
    "ng2-file-upload": "^1.3.0",
    "ng2-toastr": "^4.1.2",
    "ng2-webstorage": "^2.0.0",
    "ngx-auth": "^3.0.0",
    "ngx-auth-social": "^3.0.0",
    "ngx-bootstrap": "^2.0.3",
    "ngx-color-picker": "^5.3.5",
    "ngx-parallax": "^3.0.0-rc.2",
    "ngx-restangular": "^2.1.0",
    "ngx-stripe": "^0.2.3",
    "ngx-webstorage": "^2.0.1",
    "nodemailer": "^4.6.3",
    "passport": "^0.4.0",
    "pattern-replace": "^0.1.2",
    "popper.js": "^1.14.1",
    "rxjs": "^5.5.7",
    "sendgrid": "^5.2.3",
    "shortid-36": "^0.1.2",
    "socket.io": "^2.0.4",
    "validator": "^9.4.1",
    "vcards-js": "^2.8.0",
    "wildcard-subdomains": "^1.1.0",
    "zone.js": "^0.8.20"
  },
  "devDependencies": {
    "@angular/cli": "^1.7.3",
    "@angular/compiler-cli": "^5.2.8",
    "@angular/language-service": "^5.2.8",
    "@biesbjerg/ngx-translate-extract": "^2.3.4",
    "@ngx-rocket/scripts": "^2.1.0",
    "@types/jasmine": "^2.8.6",
    "@types/jasminewd2": "^2.0.2",
    "@types/lodash": "^4.14.104",
    "@types/node": "^9.4.7",
    "codelyzer": "^4.2.1",
    "hads": "^1.6.1",
    "htmlhint": "^0.9.13",
    "https-proxy-agent": "^2.2.0",
    "jasmine-core": "~3.1.0",
    "jasmine-spec-reporter": "^4.1.0",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "^2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.4.2",
    "karma-jasmine": "^1.1.1",
    "karma-junit-reporter": "^1.2.0",
    "protractor": "^5.3.0",
    "puppeteer": "^1.1.1",
    "stylelint": "~9.1.3",
    "stylelint-config-recommended-scss": "~3.1.0",
    "stylelint-config-standard": "~18.2.0",
    "stylelint-scss": "~2.5.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1",
    "typescript": "^2.7.2",
    "webpack-bundle-analyzer": "^2.11.1"
  }

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Latest everything

**Comment by CaerusKaru** [comment] 2018-03-14 20:33
Can you provide a minimal reproduction? I'm not seeing this in any of our StackBlitz demos or the demo-app

**Comment by CaerusKaru** [comment] 2018-03-20 08:04
Closing since no demo was provided. If you provide a demo, we can re-open, but again I'm not seeing this in any of our sample apps or internal testing.

**Closed by CaerusKaru** 2018-03-20 08:04 UTC
Labels: needs:  demo
