### ISSUE TITLE
Get Error while using "calc" for fxFlex in IE 11

### ISSUE THREAD

**Issue by Apaltaratski** [angular/flex-layout#323] opened 2017-06-22 11:02 UTC
When I trying to use "calc" in 'fxFlex' I can see only unexpected error (problem reproduce in IE 11).
It seems that "flex-basis" cannot be created with "calc" (requires more investigation).

**Comment by ThomasBurleson** [comment] 2017-06-22 14:26
@Apaltaratski - without a plunker this is not a valid issue. Please provide a Plunkr demo.

**Comment by Apaltaratski** [comment] 2017-07-14 14:12
Have problems with plunker on IE11 ... 
Create static html file to show this case in IE11.
Attached file and screen


![17](https://user-images.githubusercontent.com/24694674/28215628-56c9e7da-68b7-11e7-94d0-a0c44ac5d026.png)
[flex-test-html-file.zip](https://github.com/angular/flex-layout/files/1148639/flex-test-html-file.zip)

**Comment by ThomasBurleson** [comment] 2017-07-16 12:22
Thx @Apaltaratski. We will investigate.

**Comment by ThomasBurleson** [comment] 2017-07-16 12:25
General discussion and how-to questions should be posted to the community forum areas:

*  [Google Groups](https://groups.google.com/forum/#!forum/angular-flex-layout)
*  [Gitter Channel](https://gitter.im/angular/flex-layout)

Closing this issue as 'invalid'. Thank you.

**Comment by martinmcwhorter** [comment] 2017-08-18 15:41
I am seeing an issue with the following code:

    <some-element 
        fxFlex="0 0 calc(16% - 10px)"
        fxFlex.lg="0 0 calc(25% - 10px)"
        fxFlex.md="0 0 calc(33% - 10px)"
        fxFlex.sm="0 0 calc(50% - 10px)"
        fxFlex.xs="100%"></some-element>

Only in IE11 I get the following error:

    "Error: Unspecified error.
        at DefaultDomRenderer2.prototype.setStyle (http://localhost:4200/vendor.bundle.js:111775:9)
        at BaseAnimationRenderer.prototype.setStyle (http://localhost:4200/vendor.bundle.js:113806:5)
        at DebugRenderer2.prototype.setStyle (http://localhost:4200/vendor.bundle.js:71963:5)
        ...

Angular 4.2.4
Flex-Layout 2.0.0-beta.8

If I remove the calc() the errors go away.

**Comment by ThomasBurleson** [comment] 2017-08-18 17:43
@martinmcwhorter - please install the nightly build a retest. See [NPM Install Nightly Build](https://github.com/angular/flex-layout/wiki/NPM-Installs#install-from-head).

> If you problem persists, I will reopen.

**Comment by martinmcwhorter** [comment] 2017-08-21 08:40
@ThomasBurleson 

I installed the nightly builds and retested. Issue still exists. 

Repro steps:

Use fxFlex with the calc function:

        fxFlex="0 0 calc(16% - 10px)"
        fxFlex.lg="0 0 calc(25% - 10px)"
        fxFlex.md="0 0 calc(33% - 10px)"
        fxFlex.sm="0 0 calc(50% - 10px)"

Stack trace:
```
ERROR Error: Unspecified error.
   "ERROR"
   {
      [functions]: ,
      __proto__: { },
      description: "Unspecified error.",
      message: "Unspecified error.",
      name: "Error",
      ngDebugContext: {
         [functions]: ,
         __proto__: { },
         component: { },
         componentRenderElement: { },
         context: {
            [functions]: ,
            __proto__: { },
            bank: { }
         },
         elDef: { },
         elOrCompView: { },
         elView: { },
         injector: { },
         nodeDef: { },
         nodeIndex: 1,
         providerTokens: [ ],
         references: { },
         renderNode: { },
         view: { }
      },
      number: -2147467259,
      stack: "Error: Unspecified error.
   at DefaultDomRenderer2.prototype.setStyle (http://localhost:4200/vendor.bundle.js:110096:9)
   at BaseAnimationRenderer.prototype.setStyle (http://localhost:4200/vendor.bundle.js:112127:5)
   at DebugRenderer2.prototype.setStyle (http://localhost:4200/vendor.bundle.js:71951:5)
   at Anonymous function (http://localhost:4200/vendor.bundle.js:73181:9)
   at applyMultiValueStyleToElement (http://localhost:4200/vendor.bundle.js:73177:1)
   at applyStyleToElement (http://localhost:4200/vendor.bundle.js:73168:1)
   at BaseFxDirective.prototype._applyStyleToElement (http://localhost:4200/vendor.bundle.js:73431:5)
   at FlexDirective.prototype._updateStyle (http://localhost:4200/vendor.bundle.js:74701:5)
   at FlexDirective.prototype.ngOnChanges (http://localhost:4200/vendor.bundle.js:74673:9)
   at checkAndUpdateDirectiveInline (http://localhost:4200/vendor.bundle.js:69087:5)"
   }

ERROR CONTEXT [object Object]
   "ERROR CONTEXT"
   {
      [functions]: ,
      __proto__: { },
      component: { },
      componentRenderElement: { },
      context: { },
      elDef: { },
      elOrCompView: { },
      elView: { },
      injector: { },
      nodeDef: { },
      nodeIndex: 1,
      providerTokens: [ ],
      references: { },
      renderNode: { },
      view: { }
   }

ERROR Error: Unspecified error.
   "ERROR"
   {
      [functions]: ,
      __proto__: { },
      description: "Unspecified error.",
      message: "Unspecified error.",
      name: "Error",
      ngDebugContext: { },
      number: -2147467259,
      stack: "Error: Unspecified error.
   at DefaultDomRenderer2.prototype.setStyle (http://localhost:4200/vendor.bundle.js:110096:9)
   at BaseAnimationRenderer.prototype.setStyle (http://localhost:4200/vendor.bundle.js:112127:5)
   at DebugRenderer2.prototype.setStyle (http://localhost:4200/vendor.bundle.js:71951:5)
   at Anonymous function (http://localhost:4200/vendor.bundle.js:73181:9)
   at applyMultiValueStyleToElement (http://localhost:4200/vendor.bundle.js:73177:1)
   at applyStyleToElement (http://localhost:4200/vendor.bundle.js:73168:1)
   at BaseFxDirective.prototype._applyStyleToElement (http://localhost:4200/vendor.bundle.js:73431:5)
   at FlexDirective.prototype._updateStyle (http://localhost:4200/vendor.bundle.js:74701:5)
   at FlexDirective.prototype.ngOnChanges (http://localhost:4200/vendor.bundle.js:74673:9)
   at checkAndUpdateDirectiveInline (http://localhost:4200/vendor.bundle.js:69087:5)"
   }

ERROR CONTEXT [object Object]
   "ERROR CONTEXT"
   {
      [functions]: ,
      __proto__: { },
      component: { },
      componentRenderElement: { },
      context: { },
      elDef: { },
      elOrCompView: { },
      elView: { },
      injector: { },
      nodeDef: { },
      nodeIndex: 1,
      providerTokens: [ ],
      references: { },
      renderNode: { },
      view: { }
   }

ERROR Error: Unspecified error.
   "ERROR"
   {
      [functions]: ,
      __proto__: { },
      description: "Unspecified error.",
      message: "Unspecified error.",
      name: "Error",
      ngDebugContext: { },
      number: -2147467259,
      stack: "Error: Unspecified error.
   at DefaultDomRenderer2.prototype.setStyle (http://localhost:4200/vendor.bundle.js:110096:9)
   at BaseAnimationRenderer.prototype.setStyle (http://localhost:4200/vendor.bundle.js:112127:5)
   at DebugRenderer2.prototype.setStyle (http://localhost:4200/vendor.bundle.js:71951:5)
   at Anonymous function (http://localhost:4200/vendor.bundle.js:73181:9)
   at applyMultiValueStyleToElement (http://localhost:4200/vendor.bundle.js:73177:1)
   at applyStyleToElement (http://localhost:4200/vendor.bundle.js:73168:1)
   at BaseFxDirective.prototype._applyStyleToElement (http://localhost:4200/vendor.bundle.js:73431:5)
   at FlexDirective.prototype._updateStyle (http://localhost:4200/vendor.bundle.js:74701:5)
   at FlexDirective.prototype.ngOnChanges (http://localhost:4200/vendor.bundle.js:74673:9)
   at checkAndUpdateDirectiveInline (http://localhost:4200/vendor.bundle.js:69087:5)"
   }

ERROR CONTEXT [object Object]
   "ERROR CONTEXT"
   {
      [functions]: ,
      __proto__: { },
      component: { },
      componentRenderElement: { },
      context: { },
      elDef: { },
      elOrCompView: { },
      elView: { },
      injector: { },
      nodeDef: { },
      nodeIndex: 1,
      providerTokens: [ ],
      references: { },
      renderNode: { },
      view: { }
   }

ERROR Error: Unspecified error.
   "ERROR"
   {
      [functions]: ,
      __proto__: { },
      description: "Unspecified error.",
      message: "Unspecified error.",
      name: "Error",
      ngDebugContext: { },
      number: -2147467259,
      stack: "Error: Unspecified error.
   at DefaultDomRenderer2.prototype.setStyle (http://localhost:4200/vendor.bundle.js:110096:9)
   at BaseAnimationRenderer.prototype.setStyle (http://localhost:4200/vendor.bundle.js:112127:5)
   at DebugRenderer2.prototype.setStyle (http://localhost:4200/vendor.bundle.js:71951:5)
   at Anonymous function (http://localhost:4200/vendor.bundle.js:73181:9)
   at applyMultiValueStyleToElement (http://localhost:4200/vendor.bundle.js:73177:1)
   at applyStyleToElement (http://localhost:4200/vendor.bundle.js:73168:1)
   at BaseFxDirective.prototype._applyStyleToElement (http://localhost:4200/vendor.bundle.js:73431:5)
   at FlexDirective.prototype._updateStyle (http://localhost:4200/vendor.bundle.js:74701:5)
   at FlexDirective.prototype.ngOnChanges (http://localhost:4200/vendor.bundle.js:74673:9)
   at checkAndUpdateDirectiveInline (http://localhost:4200/vendor.bundle.js:69087:5)"
   }

ERROR CONTEXT [object Object]
   "ERROR CONTEXT"
   {
      [functions]: ,
      __proto__: { },
      component: { },
      componentRenderElement: { },
      context: { },
      elDef: { },
      elOrCompView: { },
      elView: { },
      injector: { },
      nodeDef: { },
      nodeIndex: 1,
      providerTokens: [ ],
      references: { },
      renderNode: { },
      view: { }
   }

ERROR Error: Unspecified error.
   "ERROR"
   {
      [functions]: ,
      __proto__: { },
      description: "Unspecified error.",
      message: "Unspecified error.",
      name: "Error",
      ngDebugContext: { },
      number: -2147467259,
      stack: "Error: Unspecified error.
   at DefaultDomRenderer2.prototype.setStyle (http://localhost:4200/vendor.bundle.js:110096:9)
   at BaseAnimationRenderer.prototype.setStyle (http://localhost:4200/vendor.bundle.js:112127:5)
   at DebugRenderer2.prototype.setStyle (http://localhost:4200/vendor.bundle.js:71951:5)
   at Anonymous function (http://localhost:4200/vendor.bundle.js:73181:9)
   at applyMultiValueStyleToElement (http://localhost:4200/vendor.bundle.js:73177:1)
   at applyStyleToElement (http://localhost:4200/vendor.bundle.js:73168:1)
   at BaseFxDirective.prototype._applyStyleToElement (http://localhost:4200/vendor.bundle.js:73431:5)
   at FlexDirective.prototype._updateStyle (http://localhost:4200/vendor.bundle.js:74701:5)
   at FlexDirective.prototype.ngOnChanges (http://localhost:4200/vendor.bundle.js:74673:9)
   at checkAndUpdateDirectiveInline (http://localhost:4200/vendor.bundle.js:69087:5)"
   }

ERROR CONTEXT [object Object]
   "ERROR CONTEXT"
   {
      [functions]: ,
      __proto__: { },
      component: { },
      componentRenderElement: { },
      context: { },
      elDef: { },
      elOrCompView: { },
      elView: { },
      injector: { },
      nodeDef: { },
      nodeIndex: 1,
      providerTokens: [ ],
      references: { },
      renderNode: { },
      view: { }
   }
```

**Comment by ctaepper** [comment] 2017-08-24 09:17
This is definatly an error, which prevents IE11 from rendering the site properly. How does this get flagged only "minor" ???

**Comment by merlosy** [comment] 2017-08-31 09:52
My app is broken on IE because of that...
Please fix it asap! :/

**Comment by kvitozev** [comment] 2017-09-04 08:24
@ThomasBurleson, the issue is related with usage of shorthand syntax for `flex` in IE.

If all flex-box properties are explicitly provided, it works fine.

For example, this one will fail:

fxFlex="0 0 calc(100%-14px)"

But, if there's a way to specify all properties explicitly, e.g:

fxShrink="0"
fxGrow="0"
fxBasis="calc(100%-14px)"

...it will works! 

I saw that there are `fxShrink` and `fxGrow` properties, but `fxBasis` is missing. 

Is it hidden somewhere, or it's not implemented yet? If it's not, I'd be happy to create a pull request for it.

**Comment by Apaltaratski** [comment] 2017-09-04 13:25
@kvitozev as I sad 14 of July, it is work as you sad. 

Also this problem can be resolved like 
**Change from**
```scss
flex: 1 0 calc(100% - 14px);
``` 
**To**
```scss
flex: 1 0 auto;
width: calc(100% - 14px);
```
Note: width/height, required to identify by flex-direction

**Comment by kvitozev** [comment] 2017-09-04 13:32
Thx! I totally missed that statement. 

I'll give it a try.

**Comment by pcwa-ahendricks** [comment] 2017-09-06 18:11
@kvitozev workaround by using fxGrow, fxShrink, and fxFlex with _Basis Only_ works for me.  Thanks.

**Comment by BondiGeek** [comment] 2017-09-06 21:02
Definitely a problem with how ng-Flexlayout is dealing with fxFlex="calc(100% -65px)" attributes in IE11.

The above works fine in Chrome, FF and Edge

In IE11 my Angular app will not even load if it comes across that syntax.

Remove the fxFlex (whenever calc is being used) and replace with a class the implements the same calc statement and it fixes IE11.

For now I have done just that and removed all calc statements inside fxFlex attributes.

**Comment by Apaltaratski** [comment] 2017-09-13 06:50
@BondiGeek  yes, and this will means that you have two realization of layout one in html and one in scss/css. 
As a result one question, why I need this "flex-layout" lib, if I can have some layout realization in scss file too. Also it will be difficult to remove this code (scss/css) and it will complicate bug fixing in my application.

**Comment by Karankang007** [comment] 2017-10-16 17:09
Here is the plunker for this issue:
https://plnkr.co/edit/bHj05fY5uLZhP5vqM1hK?p=preview

**Comment by ThomasBurleson** [comment] 2017-10-25 22:14
This is working without any errors using the latest code on HEAD. See the [StackBlitz demo](https://stackblitz.com/edit/fxlayout-using-calc?file=app/test.component.ts).

<img width="1371" alt="screen shot 2017-10-25 at 3 13 28 pm" src="https://user-images.githubusercontent.com/210413/32025992-1afd2ac4-b997-11e7-8790-d8b38dcdebb4.png">

> Using this Demo, are you seeing any errors in IE? Is so, which version of IE?

**Comment by ThomasBurleson** [comment] 2017-10-25 22:21
Please note that now the shorthand notation `fxFlex="calc(20% - 20px)" be use CSS injection using individual properties:

```css
   flex-grow: 1;
   flex-shrink: 1;
   flex-basis: 'calc(20% - 20px);
```

And you could use this: 

```css
flex: 1 1 auto;
width: "calc(20% - 20px)";
```

But this is a CSS workaround, I realize. So let's see if we can have an IE workaround in Beta.11

**Comment by ThomasBurleson** [comment] 2017-10-30 15:08
@Apaltaratski - does the issue in IE still manifest using the above StackBlitz demo ?

> I do not have IE locally available for testing.

**Comment by Apaltaratski** [comment] 2017-10-30 15:44
@ThomasBurleson currently not able to test IE with new version. Sorry for that

**Comment by ctaepper** [comment] 2017-10-30 16:33
@ThomasBurleson 
the stackblitz doesn't work, because the IE11 polyfills are not included... i forked the app and uncommented the polyfills. however, i still get the following error:
```
Unhandled promise rejection Error: Object doesn't support property or method 'includes'
  Instantiating https://fxlayout-using-calc-jebt11.stackblitz.io/tmp/appfiles/app/test.component.css
  Loading https://fxlayout-using-calc-jebt11.stackblitz.io/tmp/appfiles/app/test.component.ts
  Loading https://fxlayout-using-calc-jebt11.stackblitz.io/tmp/appfiles/app/app.module.ts
  Loading https://fxlayout-using-calc-jebt11.stackblitz.io/tmp/appfiles/main.ts
  Loading blitzapp
   "Unhandled promise rejection"
   {
      [functions]: ,
      __proto__: { },
      description: "Object doesn't support property or method 'includes'
  Instantiating https://fxlayout-using-calc-jebt11.stackblitz.io/tmp/appfiles/app/test.component.css
  Loading https://fxlayout-using-calc-jebt11.stackblitz.io/tmp/appfiles/app/test.component.ts
  Loading https://fxlayout-using-calc-jebt11.stackblitz.io/tmp/appfiles/app/app.module.ts
  Loading https://fxlayout-using-calc-jebt11.stackblitz.io/tmp/appfiles/main.ts
  Loading blitzapp",
      message: "Object doesn't support property or method 'includes'
  Instantiating https://fxlayout-using-calc-jebt11.stackblitz.io/tmp/appfiles/app/test.component.css
  Loading https://fxlayout-using-calc-jebt11.stackblitz.io/tmp/appfiles/app/test.component.ts
  Loading https://fxlayout-using-calc-jebt11.stackblitz.io/tmp/appfiles/app/app.module.ts
  Loading https://fxlayout-using-calc-jebt11.stackblitz.io/tmp/appfiles/main.ts
  Loading blitzapp",
      name: "Error",
      originalErr: { },
      stack: "TypeError: Object doesn't support property or method 'includes'
   at t (https://static.stackblitz.com/assets/engineblock-f9292fe449d1c267cfe07daba26eef8e7fe1dea0fafe8e87ef4a9d3c208119f8.js:2:17121)
   at a.translate (https://static.stackblitz.com/assets/engineblock-f9292fe449d1c267cfe07daba26eef8e7fe1dea0fafe8e87ef4a9d3c208119f8.js:2:18508)
   at Anonymous function (https://static.stackblitz.com/assets/engineblock-f9292fe449d1c267cfe07daba26eef8e7fe1dea0fafe8e87ef4a9d3c208119f8.js:1:31530)
   at Anonymous function (https://static.stackblitz.com/assets/packs/common-dd572ff19aaab7783e4a.js:1:32045)
   at Anonymous function (https://static.stackblitz.com/assets/packs/common-dd572ff19aaab7783e4a.js:1:31917)
   at a (https://static.stackblitz.com/assets/packs/common-dd572ff19aaab7783e4a.js:1:21188)"
   }
```

**Closed** 2018-03-09 22:52 UTC
Labels: IE Bug, P1: urgent, has pr
