### ISSUE TITLE
Link to gdColumns API in wiki is dead

### ISSUE THREAD

**Issue by takahser** [angular/flex-layout#1099] opened 2019-07-15 08:12 UTC
# Bug Report

#### What is the expected behavior?

The [gdColumns API link](https://github.com/angular/flex-layout/wiki/gdColumns-API) shouldn't be dead.

#### What is the current behavior?

The [gdColumns API link](https://github.com/angular/flex-layout/wiki/gdColumns-API) is dead.

The following wiki pages contain this dead link:

- https://github.com/angular/flex-layout/wiki/API-Documentation
- https://github.com/angular/flex-layout/wiki/Declarative-API-Overview

**Comment by 4val0v** [comment] 2019-07-19 22:19
there is no API instructions for `Grid` directives
all links related to the `Grid` - redirect to /wiki

**Comment by CaerusKaru** [comment] 2019-07-20 15:36
Duplicate of #1026

**Closed by CaerusKaru** 2019-07-20 15:36 UTC
