### ISSUE TITLE
fxLayoutGap on fxShow not applied

### ISSUE THREAD

**Issue by anwalkers** [angular/flex-layout#725] opened 2018-04-27 20:18 UTC
#### Bug, feature request, or proposal:

fxLayoutGap is not getting applied correctly when fxHide/Show displays a element.

#### What is the expected behavior?

Align with example in material.io specification. See video under "Full-width vs Centered" grids

https://material.io/guidelines/layout/responsive-ui.html#responsive-ui-grid

#### What is the current behavior?

See stackblitz below.

#### What are the steps to reproduce?

https://stackblitz.com/edit/angular-material-flex-layout-ipl

1. Resize the rendered layout small enough for tiles 8 and 9 to disappear
2. Resize the rendered layout large enough for tiles 8 and 9 to reappear

fxLayoutGap is not applied correctly

#### What is the use-case or motivation for changing an existing behavior?

Match the material.io spec

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Only tried stackblitz in Chrome

#### Is there anything else we should know?

There is one other issue I can't find an elegant solution to. Tiles 8 and 9 are set to 75% and 25% but they don't line up with the gutters. Not sure if there is an elegant solution to this on your end or mine...

**Comment by tmburnell** [comment] 2018-05-04 18:25
Is this the same as: https://github.com/angular/flex-layout/issues/606

**Comment by CaerusKaru** [comment] 2018-05-04 18:33
Duplicate of #606

**Closed by CaerusKaru** 2018-05-04 18:33 UTC
