### ISSUE TITLE
Multiple Compilation Errors using flex-layout version 6.0.0-beta.18

### ISSUE THREAD

**Issue by Soundwubz** [angular/flex-layout#870] opened 2018-10-23 16:22 UTC
# Bug Report

#### What is the expected behavior?
To compile the application

#### What is the current behavior?
CLI throws following error when trying to compile:

`ERROR in node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(72,67): error TS1144: '{' or ';' expected.
node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(74,5): error TS1128: Declaration or statement expected.
node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(74,33): error TS1005: ';' expected.
node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(74,39): error TS1109: Expression expected.
node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(79,5): error TS1128: Declaration or statement expected.
node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(80,1): error TS1128: Declaration or statement expected.`

#### What are the steps to reproduce?
Import FlexLayoutModule in app.module.ts

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular Version 6
Angular Material Version 6.4.7
Windows 10
TypeScript Version 3.1.3

#### Is there anything else we should know?
I'm a beginner in Angular, and I've searched around to try to find other issues or forum posts that have the same problem, but to no avail. I have also tried multiple other beta versions of Flex-Layout version 6, and the currently available version of Flex-Layout version 7.

**Comment by CaerusKaru** [comment] 2018-10-23 16:36
Duplicate of #843

**Closed by CaerusKaru** 2018-10-23 16:36 UTC
