### ISSUE TITLE
Problem With API Documentation

### ISSUE THREAD

**Issue by Bshutt** [angular/flex-layout#1267] opened 2020-06-03 05:41 UTC
When trying to access the API documentation sections for css-grid directives all links are redirected to the home page of the Wiki Documentation. GitHub displays a banner saying "you do not have permission to update this wiki". All links for Flexbox directives work fine.

**Comment by CaerusKaru** [comment] 2020-06-03 05:42
Duplicate of #1026

**Closed by CaerusKaru** 2020-06-03 05:42 UTC
