### ISSUE TITLE
 has no exported member 'ɵNgClassImpl'.

### ISSUE THREAD

**Issue by knroy** [angular/flex-layout#1269] opened 2020-06-12 00:34 UTC
Hi there,

I have issues on build:

```
ERROR in ./node_modules/@ecs/datatable/node_modules/@angular/flex-layout/__ivy_ngcc__/esm2015/extended.js 218:257-269
"export 'ɵNgClassImpl' was not found in '@angular/common'
ERROR in ./node_modules/@ecs/datatable/node_modules/@angular/flex-layout/__ivy_ngcc__/esm2015/extended.js 225:12-24
"export 'ɵNgClassImpl' was not found in '@angular/common'
ERROR in ./node_modules/@ecs/datatable/node_modules/@angular/flex-layout/__ivy_ngcc__/esm2015/extended.js 234:130-142
"export 'ɵNgClassImpl' was not found in '@angular/common'
ERROR in ./node_modules/@ecs/datatable/node_modules/@angular/flex-layout/__ivy_ngcc__/esm2015/extended.js 257:13-25
"export 'ɵNgClassImpl' was not found in '@angular/common'
ERROR in ./node_modules/@ecs/datatable/node_modules/@angular/flex-layout/__ivy_ngcc__/esm2015/extended.js 258:14-28
"export 'ɵNgClassR2Impl' was not found in '@angular/common'
ERROR in ./node_modules/@ecs/datatable/node_modules/@angular/flex-layout/__ivy_ngcc__/esm2015/extended.js 743:257-269
"export 'ɵNgStyleImpl' was not found in '@angular/common'
ERROR in ./node_modules/@ecs/datatable/node_modules/@angular/flex-layout/__ivy_ngcc__/esm2015/extended.js 750:12-24
"export 'ɵNgStyleImpl' was not found in '@angular/common'
ERROR in ./node_modules/@ecs/datatable/node_modules/@angular/flex-layout/__ivy_ngcc__/esm2015/extended.js 759:130-142
"export 'ɵNgStyleImpl' was not found in '@angular/common'
ERROR in ./node_modules/@ecs/datatable/node_modules/@angular/flex-layout/__ivy_ngcc__/esm2015/extended.js 789:13-25
"export 'ɵNgStyleImpl' was not found in '@angular/common'
ERROR in ./node_modules/@ecs/datatable/node_modules/@angular/flex-layout/__ivy_ngcc__/esm2015/extended.js 790:14-28
"export 'ɵNgStyleR2Impl' was not found in '@angular/common'
    
    ERROR in node_modules/@ecs/datatable/node_modules/@angular/flex-layout/extended/typings/class/class.d.ts:9:19 - error TS2305: Module '"../../../../../../../../@angular/common/common"' has no exported member 'ɵNgClassImpl'.
    
    9 import { NgClass, ɵNgClassImpl, ɵNgClassR2Impl } from '@angular/common';
                        ~~~~~~~~~~~~
    node_modules/@ecs/datatable/node_modules/@angular/flex-layout/extended/typings/class/class.d.ts:9:33 - error TS2305: Module '"../../../../../../../../@angular/common/common"' has no exported member 'ɵNgClassR2Impl'.
    
    9 import { NgClass, ɵNgClassImpl, ɵNgClassR2Impl } from '@angular/common';
                                      ~~~~~~~~~~~~~~
    node_modules/@ecs/datatable/node_modules/@angular/flex-layout/extended/typings/style/style.d.ts:9:19 - error TS2305: Module '"../../../../../../../../@angular/common/common"' has no exported member 'NgStyleImpl'.
    
    9 import { NgStyle, NgStyleImpl, NgStyleR2Impl } from '@angular/common';
                        ~~~~~~~~~~~
    node_modules/@ecs/datatable/node_modules/@angular/flex-layout/extended/typings/style/style.d.ts:9:32 - error TS2305: Module '"../../../../../../../../@angular/common/common"' has no exported member 'NgStyleR2Impl'.
    
    9 import { NgStyle, NgStyleImpl, NgStyleR2Impl } from '@angular/common';
                                     ~~~~~~~~~~~~~
    node_modules/@ecs/datatable/node_modules/@angular/flex-layout/extended/typings/style/style.d.ts:18:25 - error TS2304: Cannot find name 'ɵNgStyleImpl'.
    
    18     protected delegate: ɵNgStyleImpl;
                               ~~~~~~~~~~~~
    node_modules/@ecs/datatable/node_modules/@angular/flex-layout/extended/typings/style/style.d.ts:24:97 - error TS2304: Cannot find name 'ɵNgStyleImpl'.
    
    24     constructor(elementRef: ElementRef, styler: StyleUtils, marshal: MediaMarshaller, delegate: ɵNgStyleImpl, sanitizer: DomSanitizer, ngStyleInstance: NgStyle, serverLoaded: boolean, platformId: Object);
                                                                                                       ~~~~~~~~~~~~
```

```
"dependencies": {
    "@agm/core": "^1.1.0",
    "@angular-material-extensions/google-maps-autocomplete": "^3.2.1",
    "@angular/animations": "~9.1.11",
    "@angular/common": "~9.1.11",
    "@angular/compiler": "~9.1.11",
    "@angular/core": "~9.1.11",
    "@angular/flex-layout": "^9.0.0-beta.29",
    "@angular/forms": "~9.1.11",
    "@angular/google-maps": "^9.2.4",
    "@angular/material": "^9.2.4",
    "@angular/material-moment-adapter": "^9.2.4",
    "@angular/platform-browser": "~9.1.11",
    "@angular/platform-browser-dynamic": "~9.1.11",
    "@angular/router": "~9.1.11",
    "@auth0/angular-jwt": "^4.2.0",
    "@ckeditor/ckeditor5-angular": "^1.2.3",
    "@ecs/core": "^1.0.39",
    "@ecs/datatable": "0.0.4",
    "@ecs/icons": "0.0.10",
    "@fortawesome/fontawesome-free": "^5.13.0",
    "@mat-datetimepicker/core": "^4.1.0",
    "@mat-datetimepicker/moment": "^4.1.0",
    "@types/googlemaps": "^3.39.6",
    "bootstrap": "^4.5.0",
    "classlist.js": "^1.1.20150312",
    "firebase": "^7.15.1",
    "hammerjs": "^2.0.8",
    "jquery": "^3.5.1",
    "lodash": "^4.17.15",
    "ngx-material-timepicker": "^5.5.3",
    "primeng": "^9.1.0",
    "quill": "^1.3.7",
    "rxjs": "~6.5.5",
    "rxjs-compat": "^6.5.5",
    "tslib": "^2.0.0",
    "uuid": "^8.1.0",
    "zone.js": "~0.10.3"
  },
```

tried to switching `"@angular/flex-layout": "^9.0.0-beta.30"` and `"@angular/flex-layout": "^9.0.0-beta.31"` but no luck.

**Comment by CaerusKaru** [comment] 2020-06-12 00:36
Duplicate of #1061

**Closed by CaerusKaru** 2020-06-12 00:36 UTC
