### ISSUE TITLE
Flex-layout Beta Versions

### ISSUE THREAD

**Issue by rdollin** [angular/flex-layout#1364] opened 2021-09-15 15:16 UTC
Hi,

We are planning to use angular/flex-layout along with Google Material UI. When we were searching for a stable version, we observed all releases are beta versions. 
https://www.npmjs.com/package/@angular/flex-layout?activeTab=versions

It would be great if someone from the forum can help to evaluate the stability and security aspect of this package or suggest an alternate package if someone is using it.

**Comment by CaerusKaru** [comment] 2021-09-15 17:17
This is not a forum.

Duplicate of #835

**Closed by CaerusKaru** 2021-09-15 17:17 UTC

**Comment by mackelito** [comment] 2021-09-15 18:22
I have been using this lib in several projects for several years and would recommend it any time of day! 👍
