### ISSUE TITLE
@angular/flex-layout@2.0.0-beta.12 requires a peer of @angular/common@~5.1.0 but none is installed.

### ISSUE THREAD

**Issue by sujithtomy** [angular/flex-layout#622] opened 2018-02-18 03:13 UTC
#### What is the expected behavior?
Expect to support latest @angular version 5.2.5.

#### What is the current behavior?
npm install failed

#### What are the steps to reproduce?
Providing a StackBlitz (or similar) is the *best* way to get the team to see your issue.

*  [StackBlitz starter](https://goo.gl/y38GUZ) using latest `npm` nightly release:

**Comment by CaerusKaru** [comment] 2018-02-18 03:14
Duplicate of #620

**Closed by CaerusKaru** 2018-02-18 03:14 UTC
