### ISSUE TITLE
Broken Source Code Link in Documentation Wiki

### ISSUE THREAD

**Issue by netlander** [angular/flex-layout#661] opened 2018-03-13 17:10 UTC
#### Bug, feature request, or proposal:
Documentation fix.

#### What is the expected behavior?
Link should work?

#### What is the current behavior?
Broken source code link:

[Source Code](https://github.com/angular/flex-layout/blob/master/src/demo-app/demo-app-module.ts)

Source code link found at the bottom of this page: [https://github.com/angular/flex-layout](url), in the **Demos** section.

**Comment by CaerusKaru** [comment] 2018-03-13 17:27
Duplicate of #654

**Closed by CaerusKaru** 2018-03-13 17:27 UTC
