### ISSUE TITLE
Split module throws Typescript errors

### ISSUE THREAD

**Issue by petef19** [angular/flex-layout#1317] opened 2020-12-22 07:08 UTC
# Bug Report

#### What is the expected behavior?
include module TS error free

#### What is the current behavior?
split module throws TS errors

```
(1) /split/split-handle.directive.ts:25:71 - error TS2345: Argument of type 'OperatorFunction<MouseEvent, { x: number; y: number; }>' is not assignable to parameter of type 'OperatorFunction<unknown, { x: number; y: number; }>'.

(2) /split/split-handle.directive.ts:27:7 - error TS2345: Argument of type 'MonoTypeOperatorFunction<Event>' is not assignable to parameter of type 'OperatorFunction<Event, MouseEvent>'.

(3) /split/split.directive.ts:26:55 - error TS2564: Property 'handle' has no initializer and is not definitely assigned in the constructor.

(4) /split/split.directive.ts:27:40 - error TS2564: Property 'areas' has no initializer and is not definitely assigned in the constructor.

(5) /split.directive.ts:29:11 - error TS2564: Property 'watcher' has no initializer and is not definitely assigned in the constructor.
```

#### What are the steps to reproduce?
include the split module from the demo-app into the app

#### What is the use-case or motivation for changing an existing behavior?
TS errors break Ng build

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular CLI: 11.0.3
Node: 12.18.0
OS: win32 x64
typescript: 4.0.5

**Comment by CaerusKaru** [comment] 2020-12-22 07:10
I'm unable to reproduce this on macOS. I'll leave this here in case someone with Windows can investigate, but I don't see this seeing direct action in the near future.

**Comment by petef19** [comment] 2020-12-22 07:14
well those are standard TS errors, so you're saying on OSX none of these occur ? 

that'd be very odd, TS is OS agnostic AFAIK.

unfortunately I can't directly test the included demo-app because of the build errors, see #1316

**Comment by CaerusKaru** [comment] 2020-12-22 07:17
With every release, in addition to automated testing, I run the demo-app and go through every page and test every component. Additionally, after your first issue was opened, I ran the demo-app myself on a fresh install and did this testing again without issue.

**Comment by DuncanFaulkner** [comment] 2020-12-22 19:22
I upgraded from version 10 to 11 (latest version of angular and Flex-Layout/Material) today and I've had no issues upgrading and Flex-Layout is working as expected.
Running this on Ubuntu 18.04

**Comment by petef19** [comment] 2020-12-22 22:04
> I upgraded from version 10 to 11 (latest version of angular and Flex-Layout/Material) today and I've had no issues upgrading and Flex-Layout is working as expected.
> Running this on Ubuntu 18.04

well, this bug report is specifically for the SPLIT module, not flex-layout in general, which works here as well...

**Comment by CaerusKaru** [comment] 2021-09-15 17:24
I'm going to close this, since we don't officially support the split directive as part of the library, and it's working as expected for us. I would check your tsconfig settings to see how they align to our demo app. They may be too restrictive.

**Closed by CaerusKaru** 2021-09-15 17:24 UTC
