### ISSUE TITLE
Flex Layout adding css properties when using fxFlex

### ISSUE THREAD

**Issue by guilhermebentomarques** [angular/flex-layout#1319] opened 2021-02-02 12:18 UTC
# Bug Report

#### What is the expected behavior?

I expect that the child component without the css properties.

#### What is the current behavior?

The child component has 3 css properties added by the FlexLayout

```
flex-direction: row;
box-sizing: border-box;
display: flex;
```

#### What are the steps to reproduce?

If you inspect the <app-child> you can see the elements

https://stackblitz.com/edit/angular-9-material-starter-egchnu?file=src/app/child.component.html

![image](https://user-images.githubusercontent.com/10928446/106599479-05dc1d80-6551-11eb-9651-6e845a45e653.png)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

```
"dependencies": {
    "@angular/animations": "^8.0.0",
    "@angular/cdk": "^8.0.0",
    "@angular/common": "^8.0.0",
    "@angular/compiler": "^8.0.0",
    "@angular/core": "^8.0.0",
    "@angular/flex-layout": "^8.0.0-beta.27",
    "@angular/forms": "^8.0.0",
    "@angular/http": "^6.0.3",
    "@angular/material": "^8.0.0",
    "@angular/material-moment-adapter": "^8.0.0",
    "@angular/platform-browser": "^8.0.0",
    "@angular/platform-browser-dynamic": "^8.0.0",
    "@angular/router": "^8.0.0",
    "core-js": "^3.6.4",
    "moment": "^2.24.0",
    "rxjs": "^6.5.4",
    "tslib": "^1.11.1",
    "zone.js": "^0.10.3"
  },
```

#### Is there anything else we should know?

There is a workaround to fix this.. Is import the module with the below config. But when I build the solution to production, using **ng build --prod** the withConfig doesn't work. Is there any way to fix this issue in Aot Mode?

```
 FlexLayoutModule.withConfig({
      addFlexToParent: false,
    }),
```

**Comment by guilhermebentomarques** [comment] 2021-02-19 20:44
Any news about this?

**Comment by etwillbefine** [comment] 2021-03-24 17:22
Similar issue here. For me this was caused by an invalid use of fxLayout.

Invalid use:
```
<section fxLayout="column" fxFlex.gt-sm="row wrap" fxLayoutGap="25px grid">
```

Corrected use:
```
<section fxLayout="column" fxLayout.gt-sm="row wrap" fxLayoutGap="25px grid">
```

I guess the use of `fxFlex` without a parent `fxLayout` caused flex-layout to automatically append mandatory styles to the parent component. In your case I cant see a parent `fxLayout` as well (overall the example use of fxFlex is a bit confusing to me)

Imo it would be better to see `fxFlex` not working as expected (or an error) instead of trying to figure out why a parent component suddenly gets additional styles.

**Comment by liesahead** [comment] 2021-04-02 11:16
Ohh, I've been searching for issue in my code and it seems that `fxFlex` on child modifies styles of parent elements sometimes. It wasn't like that before. What's happening?

**Comment by CaerusKaru** [comment] 2021-09-15 17:29
Ok to be clear here: what you're describing isn't an issue and the workaround isn't a workaround. This is all expected behavior, and has been for at least a year. To allow ease-of-entry to the framework for users, which is a tenet of this library's charter, `fxFlex` adds basic flex-related CSS to its parent if `fxLayout` is not present. This is because new users may not realize the relationship between those two directives (or CSS hierarchy), and just want their flexbox to initialize. This is all documented behavior, and has been the case since day one of this library. Disabling this functionality was introduced about a year ago to allow users to customize how these directives interact. If you are saying the disable functionality is broken, that's an entirely different issue than the issue title, and we would need a minimal reproduction to investigate using the latest versions.

The reproduction given here uses v8, which we haven't supported for more than a year. If it is upgraded to v12, we can investigate further.

**Comment by CaerusKaru** [comment] 2021-12-23 09:06
Closing with lack of reply.

**Closed by CaerusKaru** 2021-12-23 09:06 UTC
Labels: needs:  demo, can be closed?
