### ISSUE TITLE
Update for angular v14 🥹😇

### ISSUE THREAD

**Issue by maximedupre** [angular/flex-layout#1404] opened 2022-06-02 18:35 UTC
Currently when running `npx ng update @angular/cdk`

> Package "@angular/flex-layout" has an incompatible peer dependency to "@angular/cdk" (requires "^13.0.0", would install "14.0.0").

**Comment by ianvink** [comment] 2022-06-03 23:52
thank you for all your hard work.

**Comment by csname1910** [comment] 2022-06-06 01:40
Just add to package.json:

  "overrides": {    
    "@angular/flex-layout": {
      "@angular/cdk": "^14.0.0",
      "@angular/common": "^14.0.0",
      "@angular/core": "^14.0.0",
      "@angular/platform-browser": "^14.0.0"
    }
  },

**Comment by crh225** [comment] 2022-06-06 14:41
https://github.com/angular/flex-layout/pull/1405
PR is out there. build is timing out

**Comment by AlonsoK28** [comment] 2022-06-09 18:51
When try to install on Angular 14

```javascript
PS D:\Documents\dev\project> ng add @angular/flex-layout --force
ℹ Using package manager: npm
⚠ Unable to find compatible package. Using 'latest' tag.
⚠ Package has unmet peer dependencies. Adding the package may not succeed.

The package @angular/flex-layout@13.0.0-beta.38 will be installed and executed.
Would you like to proceed? Yes
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: xadani-admin@0.0.0
npm ERR! Found: @angular/cdk@14.0.1
npm ERR! node_modules/@angular/cdk
npm ERR!   @angular/cdk@"^14.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/cdk@"^13.0.0" from @angular/flex-layout@13.0.0-beta.38
npm ERR! node_modules/@angular/flex-layout
npm ERR!   @angular/flex-layout@"13.0.0-beta.38" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\Alons\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Alons\AppData\Local\npm-cache\_logs\2022-06-09T18_49_17_715Z-debug-0.log
✖ Packages installation failed, see above.
```

**Comment by Tyler-V** [comment] 2022-06-10 14:02
Can only be installed with npm i --force right now on the latest Angular version

**Comment by kasir-barati** [comment] 2022-06-18 12:31
PLEASE FIX THIS ISSUE:

```cmd
$ ng add @angular/flex-layout @angular/cdk
ℹ Using package manager: pnpm
⚠ Unable to find compatible package. Using 'latest' tag.
⚠ Package has unmet peer dependencies. Adding the package may not succeed.

The package @angular/flex-layout@13.0.0-beta.38 will be installed and executed.
Would you like to proceed? Yes
✔ Packages successfully installed.
Package "@angular/flex-layout" was found but does not support schematics.
$ pnpm add @angular/flex-layout @angular/cdk
Already up-to-date
Progress: resolved 543, reused 523, downloaded 0, added 0, done
 WARN  Issues with peer dependencies found
.
└─┬ @angular/flex-layout
  ├── ✕ unmet peer @angular/cdk@^13.0.0: found 14.0.2
  ├── ✕ unmet peer @angular/core@^13.0.0: found 14.0.1
  ├── ✕ unmet peer @angular/common@^13.0.0: found 14.0.1
  └── ✕ unmet peer @angular/platform-browser@^13.0.0: found 14.0.1
$ pnpm add @angular/flex-layout @angular/cdk --force
 WARN  using --force I sure hope you know what you are doing
 WARN  deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated
Packages: +867
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 866, reused 846, downloaded 20, added 867, done
node_modules/.pnpm/nice-napi@1.0.2/node_modules/nice-napi: Running install script, done in 364ms
node_modules/.pnpm/esbuild@0.14.38/node_modules/esbuild: Running postinstall script, done in 178ms
 WARN  Issues with peer dependencies found
.
└─┬ @angular/flex-layout
  ├── ✕ unmet peer @angular/cdk@^13.0.0: found 14.0.2
  ├── ✕ unmet peer @angular/core@^13.0.0: found 14.0.1
  ├── ✕ unmet peer @angular/common@^13.0.0: found 14.0.1
  └── ✕ unmet peer @angular/platform-browser@^13.0.0: found 14.0.1
```

And just `@angular/flex-layout` is installed. `@angular/cdk` is not.

**Comment by vernes** [comment] 2022-06-22 08:19
Any update on this? I can confirm that forcing install seems to work just fine in my case.

**Comment by Sebastian-G** [comment] 2022-06-22 08:36
Seems like the most promising PR is https://github.com/angular/flex-layout/pull/1409 but it didn't pass the pipe 😭

**Comment by brianpooe** [comment] 2022-06-25 20:05
Facing the same issue, any update on this?

**Comment by chamikasandamal** [comment] 2022-06-27 17:35
Please fix the PR check for this

**Comment by CaerusKaru** [comment] 2022-06-29 03:26
Hi all, I've posted an update in #1409, but essentially we're waiting to either disable that CI check or to reach a conclusion in our investigation of the issue. Whichever comes first will lead to the PR being merged and us cutting a new release. I apologize for the wait thus far, this release has come at a tough time logistically for me, but I assure you we will get this merged and cut a new release as soon as possible.

**Closed** 2022-06-30 16:47 UTC
Labels: has pr, P0

**Comment by ianvink** [comment] 2022-06-30 16:49
there is no way you read my CV.

**Comment by TRupesh07** [comment] 2022-07-30 05:06
can anyone please look into this . I am getting this error after installation of npm i -s @angular/flex-layout @angular/cdk amd imported flexlayout to app.module.ts and imported mediaObserver in app.componenet.ts.
Here is the error.

ERROR in ./node_modules/@angular/flex-layout/fesm2015/angular-flex-layout.mjs 66:0-27
Can't import the named export 'ɵɵngDeclareClassMetadata' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/@angular/flex-layout/fesm2015/angular-flex-layout.mjs 63:24-45
Can't import the named export 'ɵɵngDeclareFactory' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/@angular/flex-layout/fesm2015/angular-flex-layout.mjs 65:24-46
Can't import the named export 'ɵɵngDeclareInjector' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/@angular/flex-layout/fesm2015/angular-flex-layout.mjs 64:24-46
Can't import the named export 'ɵɵngDeclareNgModule' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/@angular/flex-layout/fesm2015/angular-flex-layout.mjs
Module not found: Error: Can't resolve '@angular/flex-layout/core' in 'C:\Macersoft\LearnRupesh\Admindashboard\node_modules\@angular\flex-layout\fesm2015'
ERROR in ./node_modules/@angular/flex-layout/fesm2015/angular-flex-layout.mjs
Module not found: Error: Can't resolve '@angular/flex-layout/extended' in 'C:\Macersoft\LearnRupesh\Admindashboard\node_modules\@angular\flex-layout\fesm2015'
ERROR in ./node_modules/@angular/flex-layout/fesm2015/angular-flex-layout.mjs
Module not found: Error: Can't resolve '@angular/flex-layout/flex' in 'C:\Macersoft\LearnRupesh\Admindashboard\node_modules\@angular\flex-layout\fesm2015'
ERROR in ./node_modules/@angular/flex-layout/fesm2015/angular-flex-layout.mjs
Module not found: Error: Can't resolve '@angular/flex-layout/grid' in 'C:\Macersoft\LearnRupesh\Admindashboard\node_modules\@angular\flex-layout\fesm2015'
    
    ERROR in node_modules/@angular/flex-layout/core/module.d.ts:8:21 - error TS2694: Namespace '"C:/Macersoft/LearnRupesh/Admindashboard/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.        
    
    8     static ɵfac: i0.ɵɵFactoryDeclaration<CoreModule, never>;
                          ~~~~~~~~~~~~~~~~~~~~
    node_modules/@angular/flex-layout/core/module.d.ts:9:21 - error TS2694: Namespace '"C:/Macersoft/LearnRupesh/Admindashboard/node_modules/@angular/core/core"' has no exported member 'ɵɵNgModuleDeclaration'.
    
    9     static ɵmod: i0.ɵɵNgModuleDeclaration<CoreModule, never, never, never>;
                          ~~~~~~~~~~~~~~~~~~~~~
    node_modules/@angular/flex-layout/core/module.d.ts:10:21 - error TS2694: Namespace '"C:/Macersoft/LearnRupesh/Admindashboard/node_modules/@angular/core/core"' has no exported member 'ɵɵInjectorDeclaration'.
    
    10     static ɵinj: i0.ɵɵInjectorDeclaration<CoreModule>;
                           ~~~~~~~~~~~~~~~~~~~~~
    node_modules/@angular/flex-layout/core/stylesheet-map/stylesheet-map.d.ts:22:21 - error TS2694: Namespace '"C:/Macersoft/LearnRupesh/Admindashboard/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.
    
    22     static ɵfac: i0.ɵɵFactoryDeclaration<StylesheetMap, never>;
                           ~~~~~~~~~~~~~~~~~~~~
    node_modules/@angular/flex-layout/core/stylesheet-map/stylesheet-map.d.ts:23:22 - error TS2694: Namespace '"C:/Macersoft/LearnRupesh/Admindashboard/node_modules/@angular/core/core"' has no exported member 'ɵɵInjectableDeclaration'.

**Comment by michaelfaith** [comment] 2022-07-30 12:29
Since this issue has already been resolved and released, you may have more success by opening a new issue (and providing a reproduction repo).  Just a suggestion.
