### ISSUE TITLE
ERROR in node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(72,67)

### ISSUE THREAD

**Issue by mayras** [angular/flex-layout#831] opened 2018-09-02 05:17 UTC
6.0.0-beta.17 worked normally, 6.0.0-beta.18 has next:

ERROR in node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(72,67): error TS1144: '{' or ';' expected.
node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(74,5): error TS1128: Declaration or statement expected.
node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(74,33): error TS1005: ';' expected.
node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(74,39): error TS1109: Expression expected.
node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(79,5): error TS1128: Declaration or statement expected.
node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(80,1): error TS1128: Declaration or statement expected.

**Comment by Doom100500** [comment] 2018-09-02 08:53
Workaround for today:
@angular/flexLayout - rollback to 6.0.0-beta.16
rxjs - rollback to 6.2.2

**Comment by ranst91** [comment] 2018-09-02 16:44
Use typescript version 2.9.1 and up to resolve

**Comment by nripoli4810** [comment] 2018-09-02 18:33
I've been having the same issue since flexLayout beta 18 was released - upgrading typescript from 2.7.2 to 2.9.2 resolved it for me.

**Comment by AnthonyNahas** [comment] 2018-09-02 21:06
I was facing the same issue and I tried these two options and they work!
1. @Doom100500 rollback to flexlayout beta 17 did the job
2. @ranst91 @nripoli4810 updating typescript to version 2.9.2 solved the problem 💯

**Comment by Doom100500** [comment] 2018-09-03 09:01
Just checked with the brand new project created with angular-cli ver 6.1.5
1. ng new... gives typescript ~2.7.2 in package.json
2. replaced typescript version in package.json to ^2.9.2
3. install and setup angular/flex-layout
4. build failed, cannot find modules of @angular/cdk
5. npm i --save @angulal/cdk
6. build working...

Seems that this is a bug in angular cli...

**Comment by CaerusKaru** [comment] 2018-09-04 04:45
Duplicate of #827

**Closed by CaerusKaru** 2018-09-04 04:45 UTC

**Comment by mariamtsartsidze** [comment] 2018-09-06 19:04
How should I rollback rxjs to 6.2.2? I've got 6.3.2. npm install -g rxjs@6.2.2 doesn't change it. Can't find the appropriate command to uninstall and reinstall it. Also one more question, should I do it globally, locally or both ways?

**Comment by Yaseen-Nadaf** [comment] 2018-09-07 10:33
These is my package.json configuration:

"dependencies": {
    "@angular/animations": "^6.0.7",
    "@angular/cdk": "^6.3.3",
    "@angular/common": "^6.0.0",
    "@angular/compiler": "^6.0.0",
    "@angular/core": "^6.0.0",
    "@angular/flex-layout": "^6.0.0-beta.16",
    "@angular/forms": "^6.0.0",
    "@angular/http": "^6.0.0",
    "@angular/platform-browser": "^6.0.0",
    "@angular/platform-browser-dynamic": "^6.0.0",
    "@angular/platform-server": "^6.0.0",
    "@angular/router": "^6.0.0",
    "@nguniversal/common": "^6.0.0",
    "@nguniversal/express-engine": "^6.0.0",
    "@nguniversal/module-map-ngfactory-loader": "^6.0.0",
    "core-js": "^2.4.1",
    "d3": "^5.5.0",
    "d3-array": "^1.2.1",
    "d3-collection": "^1.0.4",
    "d3-color": "^1.2.0",
    "d3-format": "^1.3.0",
    "d3-interpolate": "^1.2.0",
    "d3-scale": "^2.1.0",
    "d3-time": "^1.0.8",
    "d3-time-format": "^2.1.1",
    "d3-tip": "^0.9.1",
    "ngx-json-viewer": "^2.3.0",
    "font-awesome": "^4.7.0",
    "jquery": "^3.3.1",
    "primeicons": "^1.0.0-beta.9",
    "primeng": "^6.0.0",
    "rxjs": "6.0.0",
    "zone.js": "^0.8.26",
    "save-svg-as-png": "^1.4.5"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "0.6.0",
    "@angular/cli": "6.0.0",
    "@angular/compiler-cli": "6.0.0",
    "@angular/language-service": "6.0.0",
    "@types/node": "^8.0.30",
    "codelyzer": "^4.0.2",
    "cpy-cli": "^1.0.1",
    "express": "^4.15.2",
    "http-server": "^0.10.0",
    "pre-commit": "^1.2.2",
    "reflect-metadata": "^0.1.10",
    "ts-loader": "^4.2.0",
    "tslint": "^5.7.0",
    "typescript": "~2.7.2",
    "webpack-cli": "^2.0.14"
  }


I am having same issue with flex layout when I am trying to do server side rendering build, tried to update to beta.17 and 18 -> same errors, typescript to 2.9.2 -> error saying typescript version should be >=2.7.2 <2.8.2, rxjs to 6.2.2, tried evrything but still its failing.

**Comment by Yaseen-Nadaf** [comment] 2018-09-07 11:44
I just run these commands and it solved.

1. ng update @angular/cli
2. ng update @angular/core
3. update @angular/flex-layout version to "^6.0.0-beta.18"
4. npm install
5. npm run build:ssr

**Comment by Eholl80** [comment] 2018-09-10 09:59
I did point 1 to point 4 and it solves the issue !!! Thanks Yaseen

**Comment by k0nstantink** [comment] 2018-09-13 10:04
Thank you, Yaseen-Nadaf. This worked for me.

**Comment by tjbernard** [comment] 2018-09-14 08:55
Thank very very much @Yaseen-Nadaf. It worked!

**Comment by alo** [comment] 2018-09-14 17:06
worked for me too! thanks @Yaseen-Nadaf !

**Comment by SlimAidar** [comment] 2018-09-18 22:08
is this won't affect my project in the future?

**Comment by Yaseen-Nadaf** [comment] 2018-09-19 06:07
> is this won't affect my project in the future?

Actually as I am unaware of which version you are using currently, I would say that if your angular version is less than 6 then it may affect a little because of some breaking changes. You have to take care of it or code according to new changes.

**Comment by industrioustudy** [comment] 2018-09-28 15:33
did as Yaseen-Nadaf:
1. ng update @angular/cli
2. ng update @angular/core
3. **ng** update @angular/flex-layout version to "^6.0.0-beta.18"
4.  npm install

it works for me.
Thanks,

**Comment by whitewaves** [comment] 2018-10-03 14:46
@industrioustudy what version of angular?

Did not work for

**Comment by mikenap** [comment] 2018-10-05 22:07
> Use typescript version 2.9.1 and up to resolve
> edit: 2.9.2 also works, be sure not to go 3.0, or it will interrupt the angular-cli

This did the trick for me. Updating typescript to 2.9.2 for flex-layout ^6.0.0-beta.18.

**Comment by FryannM** [comment] 2018-11-18 23:42
> I just ran these commands and it solved.
> 
> 1. ng update @angular/cli
> 2. ng update @angular/core
> 3. update @angular/flex-layout version to "^6.0.0-beta.18"
> 4. npm install
> 5. npm run build:ssr

**Comment by FryannM** [comment] 2018-11-18 23:43
Thanks Man its work for me Too

**Comment by jpelton-stroud** [comment] 2018-12-16 18:17
> Use typescript version 2.9.1 and up to resolve
> edit: 2.9.2 also works, be sure not to go 3.0, or it will interrupt the angular-cli

Whelp, I can tell ya it does _not_ work w/ the following:

Angular CLI: 7.1.3
Node: 8.14.0
OS: linux x64
Angular: 7.1.3
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.11.3
@angular-devkit/build-angular     0.11.3
@angular-devkit/build-optimizer   0.11.3
@angular-devkit/build-webpack     0.11.3
@angular-devkit/core              7.1.3
@angular-devkit/schematics        7.1.3
@angular/flex-layout              7.0.0-beta.21
@ngtools/webpack                  7.1.3
@schematics/angular               7.1.3
@schematics/update                0.11.3
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.23.1
