### ISSUE TITLE
import of FlexLayoutModule

### ISSUE THREAD

**Issue by tmburnell** [angular/flex-layout#178] opened 2017-02-10 18:36 UTC
Today I updated my Flex-Layout to beta.5 and the app fails to even load due to FlexLayoutModule calling a lambda function.  After some research I saw we should not use forRoot anymore.  So I removed it.  

Then I ran into an issue where FlexLayoutModule is undefined when trying to import it. 

I have found if i point my import to : "@angular/flex-layout/flexbox" 
that it works fine, but if i use the high level import it fails. 

This could be related to [#175](https://github.com/angular/flex-layout/issues/175)

**Comment by tmburnell** [comment] 2017-02-10 19:08
#174

**Comment by ThomasBurleson** [comment] 2017-02-10 21:41
console.warn('FlexLayoutModule.forRoot() has been deprecated and is no longer needed.');

**Comment by tmburnell** [comment] 2017-02-13 13:07
Just to confirm the understanding ... if i used this I was getting an error because FlexLayoutModule was undefined
`import { MaterialModule }   from "@angular/material";
import { FlexLayoutModule } from "@angular/flex-layout";


@NgModule({
    imports: [
        MaterialModule.forRoot(),
        FlexLayoutModule
    ]
`

However if i used this it worked correctly. 
`import { MaterialModule }   from "@angular/material";
import { FlexLayoutModule } from "@angular/flex-layout/flexbox";


@NgModule({
    imports: [
        MaterialModule.forRoot(),
        FlexLayoutModule
    ]
`

However my understanding was that I should be able to leave my path for my input the same.  And I am not sure the ticket #176 resolves this issue or not.

**Comment by pigeonvictor** [comment] 2017-02-22 20:50
Same issue for me, had to change `from "@angular/flex-layout"` to `from "@angular/flex-layout/flexbox"` in order to make it work.

**Comment by ThomasBurleson** [comment] 2017-02-22 23:58
@p

**Comment by ThomasBurleson** [comment] 2017-02-23 00:02
@tmburnell, @pigeonvictor  - can you zip your project (without the node_modules) and send to me via email (ThomasBurleson@Gmail.com). I am unable to reproduce this issue.

**Comment by tmburnell** [comment] 2017-02-23 14:44
Building an example: with the newest material and flex-layout ... it works.
I noticed that material just removed forRoot also (in the last few days). 

But it does seem to work fine now.

**Comment by ThomasBurleson** [comment] 2017-02-27 17:51
Closing as no longer valid.

**Closed by ThomasBurleson** 2017-02-27 17:51 UTC
Labels: bug, needs:  demo
