### ISSUE TITLE
Compatibility with Angular ^5.1

### ISSUE THREAD

**Issue by odahcam** [angular/flex-layout#554] opened 2018-01-08 12:57 UTC
#### Bug, feature request, or proposal:
bug/feature

#### What is the expected behavior?
> In Angular 5 OpaqueToken will be removed. The replacement is to use InjectToken instead.

https://github.com/PillowPillow/ng2-webstorage/issues/61#issue-257506481

#### What is the current behavior?
OpaqueToken is being used in `./node_modules/@angular/flex-layout/media-query/breakpoints/break-points.js`.

#### What is the use-case or motivation for changing an existing behavior?
Incompatibility with new Angular versions.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/core@5.1.3
@angular/flex-layout@2.0.0-rc.1

#### Is there anything else we should know?
@angular/flex-layout@2.0.0-beta.12 does not have this problem.
  
Both `yarn upgrade` and `npm update` installs version `2.0.0-rc.1` over `2.0.0-beta.12` when executed.

**Comment by CaerusKaru** [comment] 2018-01-08 14:09
Duplicate of #494

**Closed by CaerusKaru** 2018-01-08 14:09 UTC
