### ISSUE TITLE
Angular CLI + @angular/flex-layout unrecognized

### ISSUE THREAD

**Issue by christophechevalier** [angular/flex-layout#80] opened 2017-01-03 13:20 UTC
**Hi !**
Happy New Year !!

I use on my project "angular-cli", "angular material2" and "angular flex layout". I thought I had imported
Correctly "angular flex layout" but I do not think it works on my app. Still, I have applied the implementation tips of the lib.

So I wanted to test the same code on a plunker :
[Example Test](https://plnkr.co/edit/04lYo3zkVTkGHZqPirst?p=preview)

And as you can see, it works.
So I have a problem with the recognition of the bookstore which in my opinion is not recognized by my app.

**In app.module.ts :**

```js
// angular modules
...
import { FormsModule } from '@angular/forms';
// angular-material2 modules
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { FormsModule } from '@angular/forms';
import { MaterialModule } from '@angular/material';

// angular flex-layout module
import { FlexLayoutModule } from '@angular/flex-layout';


@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    // material design
    MaterialModule.forRoot(),

    // flex layout
    FlexLayoutModule.forRoot(),
  ] ...
```

In package.json :

```json
  "dependencies": {
    "@angular/common": "2.3.0",
    "@angular/compiler": "2.3.0",
    "@angular/core": "2.3.0",
    "@angular/flex-layout": "2.0.0-beta.1",
    "@angular/forms": "2.3.0",
    "@angular/http": "2.3.0",
    "@angular/material": "2.0.0-beta.1",
    "@angular/platform-browser": "2.3.0",
    "@angular/platform-browser-dynamic": "2.3.0",
...
```

In my explorer : 

![selection_021](https://cloud.githubusercontent.com/assets/7148846/21608858/546a7ac0-d1bf-11e6-87a3-d63c8b4314d5.png)

Do you have a solution to my problem?
Thank you for your help.

**Comment by aviramga** [comment] 2017-01-03 14:22
+1 

having the same issue... angular-cli 1.0.0-beta.24

**Comment by d3viant0ne** [comment] 2017-01-03 15:21
@christophechevalier - What version of the cli are you using out of curiosity?

**Comment by christophechevalier** [comment] 2017-01-03 15:30
@d3viant0ne  - I use angular-cli version : 1.0.0-beta.21

**Comment by christophechevalier** [comment] 2017-01-03 15:34
@d3viant0ne 
![selection_022](https://cloud.githubusercontent.com/assets/7148846/21612651/639d469a-d1d2-11e6-9558-69e006559bdf.png)

**Comment by d3viant0ne** [comment] 2017-01-03 15:42
@christophechevalier - Right out of the gate, I have personally had issues pretty much any time I have had a version mismatch between what angular version the cli supports & what the project is using.

In your case, beta.21 of the cli was released with Angular 2.2.1.

Secondly, flex-layout beta.1 is published with Angular 2.4.0 which in my experience also doesn't play well with libs published with older versions of Angular, i.e 2.2.1 / 2.3.

For the sake of saving a bit of time, I'm going to spin up a new demo project on the current cli release and see if I run into integration issues with Flex-Layout / Material2 and we can go from there.

If the project in question is public, pointing me in that direction would certainly expedite troubleshooting this.

**Comment by christophechevalier** [comment] 2017-01-03 16:18
**Good idea.**
 For my part, I work on a complex project of my company. 
I could give you the link to our repository but I doubt it would be relevant because it would be complicated. 

I am currently working on the refactor using angular flex layout throughout the application. So I'll do a commit tmp and see if by updating all lib @angular except angular-cli, if it works ..

I keep you informed.

**Comment by christophechevalier** [comment] 2017-01-03 16:38
I have updated the angular libraries but nothing changed :( 

```json
  "dependencies": {
    "@angular/common": "2.4.1",
    "@angular/compiler": "2.4.1",
    "@angular/core": "2.4.1",
    "@angular/flex-layout": "2.0.0-beta.1",
    "@angular/forms": "2.4.1",
    "@angular/http": "2.4.1",
    "@angular/material": "2.0.0-beta.1",
    "@angular/platform-browser": "2.4.1",
    "@angular/platform-browser-dynamic": "2.4.1",
    "@angular/router": "3.4.1",
...
  },
  "devDependencies": {
    "@angular/compiler-cli": "2.4.1",
    "angular-cli": "1.0.0-beta.21",
...
  }
```

**Comment by d3viant0ne** [comment] 2017-01-03 16:41
@christophechevalier - Yeah, the gap between what we can do OSS and what is applicable to the projects we are building professionally is hard to bridge. There is a big difference between something with an `app.component` and something with 100 components, i'm in the same boat.

As this little endeavor would also be beneficial to me professionally, i'm happy to give you write access to my little cli playground and then adding a level or real world complexity in an attempt to recreate the issue.

Short of being able to dig through code or a bunch of stack traces, the above is the only path I can think of that has a remote chance of highlighting whatever the issue is.

**Comment by ThomasBurleson** [comment] 2017-01-03 16:48
@christophechevalier - Let me summarize to confirm my understanding:

1.   you installed `@angular/flex-layout` and
2.  you are trying to use the Angular CLI with `ng serve`
3.  but the Flex-Layout directives are not working?

Please provide a snapshot of the dev console where you are seeing errors.
Please provide the HTML for any single view which has a Flex-Layout issue.

> The question is whether you are using the API incorrectly or the Flex-Layout AOT + Angular CLI is causing some issue.

**Comment by christophechevalier** [comment] 2017-01-03 22:08
@ThomasBurleson 1-2-3 👍 

None of the items available in the library from "Angular Flex Layout" seemed to work.
No error in my console either.
The HTML of my view is the same that my Plunker : 

[Example](https://plnkr.co/edit/04lYo3zkVTkGHZqPirst?p=preview)

I followed the installation instructions carefully. My module exists. 
But when I try to use an attribute of type fxFlex or other, it has no effect.
For me, I think it's a version problem with Angular CLI.

But which one ❓ 

If I see anything that can help, I would post information on this issue.

**Comment by ThomasBurleson** [comment] 2017-01-03 23:43
Closing until more information is provided; unable to resolve issue without more information.

**Comment by christophechevalier** [comment] 2017-01-04 08:54
@ThomasBurleson 
The flex-layout module is correctly installed.
![selection_024](https://cloud.githubusercontent.com/assets/7148846/21636440/0aa94f3e-d263-11e6-8e9d-c0085ec0a15f.png)

My import is ok. 

Which side could I look for :question:

**Comment by aviramga** [comment] 2017-01-04 09:06
Exact same issues for me as well.... @ThomasBurleson what type of more information is needed?
No errors in the console for me as well.... and even copying and pasting samples from the docs doesn't seem to work....

**Comment by christophechevalier** [comment] 2017-01-04 10:36
I can give you the instructions to follow if you want to test our application on your machine and see my problem.

1. Begin by cloning the project : 
`git clone git@gitlab.com:victornoel/petals-cockpit.git`
2. Next, go to the root frontend of project : 
`cd ... petals-cockpit/frontend/`
3. Install all modules : 
`yarn`
4. Go to the branch : 
`git checkout front/implement-angular-material-layout-flex`
5. Then, running app : 
`ng serve`
6. On browser (chromium or firefox) enter url : 
`http://localhost:4200/`
7. Enter login & password authentication : 

> Username: admin
> Password: admin

8. Select Workspace
9. On the sidenav left, click on the button (import a bus)
 
Currently, my colleague works on a refactor of the whole application in order to simplify it to the maximum and to be compatible with "angular-cli": "1.0.0-beta.24". We have had problems with this version on the current application.
For information, the flex layout works perfectly on the current refactor application with the beta24 version of Angular CLI.

**Comment by ThomasBurleson** [comment] 2017-01-04 13:18
@d3viant0ne - would you mind investigating the Flex-Layout issue(s) with their legacy version ?

**Comment by christophechevalier** [comment] 2017-01-04 13:29
@ThomasBurleson 

May be, it's working in progress :+1: 

[Investigating for the flex-layout issue(s)](https://github.com/d3viant0ne/material-flex-cli)

**Comment by ThomasBurleson** [comment] 2017-01-04 15:16
I tested with a fresh project using WebPack beta24 and FlexLayout. All works great.

> Closing here as not-a-FlexLayout issue.

**Closed by ThomasBurleson** 2017-01-04 15:16 UTC
Labels: in-progress

**Comment by d3viant0ne** [comment] 2017-01-04 16:55
As opposed to creating a new project, last night I moved a larger work project that has already been updated to use the flex-layout library into the angular-cli beta.24 and much like @ThomasBurleson everything works as expected. More so that I had expected to be honest.

My gut still tells me that in your case, it's going to be related to versioning across the core libs that require angular at their core but without digging into code, I really don't know what else to do. Without log output or code, everybody is just guessing.

**Comment by machship-mm** [comment] 2017-01-12 22:50
I am still experiencing this issue. Could you please let me know what you believe the fix to be?

**Comment by maxime1992** [comment] 2017-01-24 07:55
@machship-mm are you using yarn ? Maybe try to : 
- 1 - yarn upgrade
- 2 - remove the `yarn.lock` file
- 3 - run `yarn`

not sure that 2 and 3 are required tho :

> yarn upgrade
This command updates all dependencies to their latest version based on the version range specified in the package.json file. The yarn.lock file will be recreated as well.
