### ISSUE TITLE
Broken documentation links

### ISSUE THREAD

**Issue by azflin** [angular/flex-layout#1301] opened 2020-10-23 15:23 UTC
There are broken documentation links that redirect back to the wiki homepage, ie https://github.com/angular/flex-layout/wiki/gdColumns-API. In fact I cannot find any documentation on gdColumns except for a small description in https://github.com/angular/flex-layout/wiki/API-Documentation.

**Comment by CaerusKaru** [comment] 2020-10-23 17:32
Duplicate of #1026

**Closed by CaerusKaru** 2020-10-23 17:32 UTC
