### ISSUE TITLE
Version 10.0.0-beta.32, "ng serve" error Compiling @angular/cdk/stepper : es2015 as esm2015

### ISSUE THREAD

**Issue by khaldi-yass** [angular/flex-layout#1279] opened 2020-06-20 18:09 UTC
# Bug Report
After adding flex layout to angular project, you can no longer run the application because of a compile error.
#### What is the expected behavior?
```shell
> ng serve
Compiling @angular/flex-layout/core : es2015 as esm2015
Compiling @angular/flex-layout/extended : es2015 as esm2015
Compiling @angular/flex-layout/flex : es2015 as esm2015
Compiling @angular/flex-layout/grid : es2015 as esm2015
Compiling @angular/flex-layout : es2015 as esm2015

chunk {main} main.js, main.js.map (main) 84.7 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 141 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 324 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 4.81 MB [initial] [rendered]
Date: 2020-06-20T11:14:28.151Z - Hash: 10c46459d8930710b24a - Time: 24262ms
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
: Compiled successfully.
```

#### What is the current behavior?
```shell
>ng serve
Compiling @angular/cdk/platform : es2015 as esm2015
Compiling @angular/flex-layout/core : es2015 as esm2015
Compiling @angular/cdk/collections : es2015 as esm2015
Compiling @angular/cdk/bidi : es2015 as esm2015
Compiling @angular/cdk/keycodes : es2015 as esm2015
Compiling @angular/cdk/observers : es2015 as esm2015
Compiling @angular/cdk/portal : es2015 as esm2015
Compiling @angular/cdk/clipboard : es2015 as esm2015
Compiling @angular/cdk/layout : es2015 as esm2015
Compiling @angular/cdk/text-field : es2015 as esm2015
Compiling @angular/cdk/scrolling : es2015 as esm2015
Compiling @angular/flex-layout/extended : es2015 as esm2015
Compiling @angular/flex-layout/flex : es2015 as esm2015
Compiling @angular/flex-layout/grid : es2015 as esm2015
Compiling @angular/cdk/accordion : es2015 as esm2015
Compiling @angular/cdk/a11y : es2015 as esm2015
Compiling @angular/cdk/table : es2015 as esm2015
Compiling @angular/flex-layout : es2015 as esm2015
Compiling @angular/cdk/drag-drop : es2015 as esm2015
Compiling @angular/cdk/overlay : es2015 as esm2015
Compiling @angular/cdk/tree : es2015 as esm2015
Compiling @angular/cdk/stepper : es2015 as esm2015
Error: Error on worker #1: Error: No typings declaration can be found for the referenced NgModule class in static withConfig(configOptions,
        // tslint:disable-next-line:max-line-length
        breakpoints = []) {
            return {
                ngModule: FlexLayoutModule,
                providers: configOptions.serverLoaded ?
                    [
                        { provide: LAYOUT_CONFIG, useValue: Object.assign(Object.assign({}, DEFAULT_CONFIG), configOptions) },
                        { provide: BREAKPOINT, useValue: breakpoints, multi: true },
                        { provide: SERVER_TOKEN, useValue: true },
                    ] : [
                    { provide: LAYOUT_CONFIG, useValue: Object.assign(Object.assign({}, DEFAULT_CONFIG), configOptions) },
                    { provide: BREAKPOINT, useValue: breakpoints, multi: true },
                ]
            };
        }.
    at ModuleWithProvidersAnalyzer.resolveNgModuleReference ($projectdir\node_modules\@angular\compiler-cli\ngcc\src\analysis\module_with_providers_analyzer.js:178:23)
    at ModuleWithProvidersAnalyzer.getDtsModuleWithProvidersFunction ($projectdir\node_modules\@angular\compiler-cli\ngcc\src\analysis\module_with_providers_analyzer.js:165
:33)
    at $projectdir\node_modules\@angular\compiler-cli\ngcc\src\analysis\module_with_providers_analyzer.js:46:43
    at Array.forEach (<anonymous>)
    at $projectdir\node_modules\@angular\compiler-cli\ngcc\src\analysis\module_with_providers_analyzer.js:39:28
    at Array.forEach (<anonymous>)
    at ModuleWithProvidersAnalyzer.analyzeProgram ($projectdir\node_modules\@angular\compiler-cli\ngcc\src\analysis\module_with_providers_analyzer.js:37:23)
    at Transformer.analyzeProgram ($projectdir\node_modules\@angular\compiler-cli\ngcc\src\packages\transformer.js:132:45)
    at Transformer.transform ($projectdir\node_modules\@angular\compiler-cli\ngcc\src\packages\transformer.js:75:27)
    at $projectdir\node_modules\@angular\compiler-cli\ngcc\src\execution\create_compile_function.js:48:42
    at ClusterMaster.onWorkerMessage ($projectdir\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:194:27)
    at $projectdir\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:54:95
    at ClusterMaster.<anonymous> ($projectdir\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:292:57)
    at step ($projectdir\node_modules\tslib\tslib.js:141:27)
    at Object.next ($projectdir\node_modules\tslib\tslib.js:122:57)
    at $projectdir\node_modules\tslib\tslib.js:115:75
    at new Promise (<anonymous>)
    at Object.__awaiter ($projectdir\node_modules\tslib\tslib.js:111:16)
    at EventEmitter.<anonymous> ($projectdir\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:286:32)
    at EventEmitter.emit (events.js:310:20)
An unhandled exception occurred: NGCC failed.
See "%appData%\Local\Temp\ng-pkfWFI\angular-errors.log" for further details.
```

#### What are the steps to reproduce?

1. Create a new angular project.
2. Add angular flex layout latest version `10.0.0-beta.32`.
3. ng serve.
4. Compile error.

#### Is there anything else we should know?
my `package.json` file:
```json
{
  "name": "usemefortest",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~9.1.7",
    "@angular/cdk": "^9.2.4",
    "@angular/common": "~9.1.7",
    "@angular/compiler": "~9.1.7",
    "@angular/core": "~9.1.7",
    "@angular/flex-layout": "^10.0.0-beta.32",
    "@angular/forms": "~9.1.7",
    "@angular/material": "^9.2.4",
    "@angular/platform-browser": "~9.1.7",
    "@angular/platform-browser-dynamic": "~9.1.7",
    "@angular/router": "~9.1.7",
    "rxjs": "~6.5.4",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.901.6",
    "@angular/cli": "~9.1.6",
    "@angular/compiler-cli": "~9.1.7",
    "@types/node": "^12.11.1",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~3.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "~5.4.3",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.8.3"
  }
}
```

If i downgrade my version to : ` "@angular/flex-layout": "^9.0.0-beta.31"` it works seamlessly.

Is there a conflict with the versions of other packages?

**Comment by CaerusKaru** [comment] 2020-06-20 18:10
Duplicate of #1274

**Closed by CaerusKaru** 2020-06-20 18:10 UTC
