### ISSUE TITLE
Margin with fxLayoutWrap and fxLayoutGap

### ISSUE THREAD

**Issue by clement-hollander** [angular/flex-layout#347] opened 2017-07-24 14:43 UTC
Hi,

When using responsive API, resizing the screen keeps a margin right on the element wrapped

```html
<div fxLayout="row wrap" 
     fxLayoutAlign="start stretch" 
     fxLayoutGap="20px">

    <div  fxFlex="calc(20% - 20px)" 
          fxFlex.lt-md="0 0 calc(33.33% - 20px)">
        1
    </div>
    <div  fxFlex="calc(20% - 20px)" 
          fxFlex.lt-md="0 0 calc(33.33% - 20px)" >
        2 
    </div>
    <div  fxFlex="calc(20% - 20px)" 
          fxFlex.lt-md="0 0 calc(33.33% - 20px)" >
        3
    </div>
    <div  fxFlex="calc(20% - 20px)" 
          fxFlex.lt-md="0 0 calc(33.33% - 20px)" >
        4
    </div>
    <div fxFlex="calc(20% - 20px)" 
         fxFlex.lt-md="0 0 calc(33.33% - 20px)" >
        5
    </div>
    
</div>
```

![screen shot 2017-07-24 at 10 40 31](https://user-images.githubusercontent.com/1830906/28528876-fc156fd2-705c-11e7-82a3-b62a2f1c6d4b.png)

![screen shot 2017-07-24 at 10 40 21](https://user-images.githubusercontent.com/1830906/28528877-fcbd0c7e-705c-11e7-8c69-2a8c37596885.png)

**Comment by ThomasBurleson** [comment] 2017-08-07 14:33
@clement-hollander - I do not understand what you are trying to do. Can you clarify and provide a snapshot of the **intended** layout ?

**Comment by ThomasBurleson** [comment] 2017-08-09 14:46
This appears to be a duplicate of https://github.com/angular/flex-layout/issues/363.

> See response there.

**Closed by ThomasBurleson** 2017-08-09 14:46 UTC
Labels: duplicate, P4: minor, question
