### ISSUE TITLE
flex-layout pulls Error while Compile Error Angular

### ISSUE THREAD

**Issue by rpvsen** [angular/flex-layout#840] opened 2018-09-14 03:58 UTC
# Bug Report

flex-layout pulls error while run.

#### What is the current behavior?
ERROR in node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(72,67): error TS1144: '{' or ';' expected.
node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(74,5): error TS1128: Declaration or statement expected.
node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(74,33): error TS1005: ';' expected.
node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(74,39): error TS1109: Expression expected.
node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(79,5): error TS1128: Declaration or statement expected.
node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(80,1): error TS1128: Declaration or statement expected.

#### Package.json

 "dependencies": {
        "@angular/animations": "^6.1.7",
        "@angular/cdk": "^6.4.7",
        "@angular/common": "^6.0.3",
        "@angular/compiler": "^6.0.3",
        "@angular/core": "^6.0.3",
        "@angular/flex-layout": "^6.0.0-beta.18",
        "@angular/forms": "^6.0.3",
        "@angular/http": "^6.0.3",
        "@angular/material": "^6.4.7",
        "@angular/platform-browser": "^6.0.3",
        "@angular/platform-browser-dynamic": "^6.0.3",
        "@angular/router": "^6.0.3",
        "core-js": "^2.5.4",
        "flex-layout-rxjs-fix": "^5.0.0-beta.14",
        "hammerjs": "^2.0.8",
        "rxjs": "^6.3.2",
        "rxjs-compat": "^6.3.2",
        "zone.js": "^0.8.26"
    }

**Comment by CaerusKaru** [comment] 2018-09-14 05:52
Duplicate of #827. Either upgrade TypeScript to 2.9 or downgrade RxJS to 6.2

**Closed by CaerusKaru** 2018-09-14 05:52 UTC
