### ISSUE TITLE
IE11/Edge is not rendering the value of max-height: ;

### ISSUE THREAD

**Issue by mcwebdev** [angular/flex-layout#380] opened 2017-08-16 19:47 UTC
IE is not rendering the value of `max-height:;` which is causing the styles to not be computed inline.

![image](https://user-images.githubusercontent.com/14930146/29382143-8be43320-8280-11e7-8701-a0ca23505aed.png)

Chrome is not registering the max-height property value pair, and is computing the styles inline.

![image](https://user-images.githubusercontent.com/14930146/29382295-fa64dbf6-8280-11e7-9970-0b8e35c590f7.png)

* IE still seems to be rendering the flex width somehow on window.load. Resizing the browser window does not update the flex directives. [.xs, .sm, ...]. Widths remain set from initial state. 

* Inline styles are computed on standardized elements. `<div>...</div>`

* Inline styles are **not** computed on custom selectors `<my-custom-selector>...</my-custom-selector>`

**Comment by ThomasBurleson** [comment] 2017-08-16 23:00
@mcwebdev - We need to know which version of flex-layout you are using... and we need a plunkr demo to reproduce this. 

> Our [online demos](https://tburleson-layouts-demos.firebaseapp.com/#/docs) [updated with nightly build] are using `max-width` correctly.

**Comment by bastienlemaitre** [comment] 2018-02-12 11:24
Any new ?

**Comment by CaerusKaru** [comment] 2018-02-12 17:41
@bastienlemaitre There hasn't been a demo provided for this, so we have nothing to investigate. If you can provide a demo, we can look into this.

**Comment by CaerusKaru** [comment] 2018-02-25 23:52
Closing since no demo was provided. We can reopen if a StackBlitz demo is prepared.

**Closed by CaerusKaru** 2018-02-25 23:52 UTC
Labels: IE Bug, P3: important, needs:  demo
