### ISSUE TITLE
ERROR in node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(72,67): error TS1144: '{' or ';' expected.

### ISSUE THREAD

**Issue by SlimAidar** [angular/flex-layout#843] opened 2018-09-18 22:01 UTC
# Bug Report

#### What are the steps to reproduce?
Providing a StackBlitz (or similar) is the *best* way to get the team to see your issue.

*  [StackBlitz starter](https://goo.gl/y38GUZ) using latest `npm` nightly release:

**Comment by CaerusKaru** [comment] 2018-09-18 22:02
Duplicate of #831

**Closed by CaerusKaru** 2018-09-18 22:02 UTC
