### ISSUE TITLE
ngClass changes incorrectly when printing

### ISSUE THREAD

**Issue by JustACodeMonkey** [angular/flex-layout#1201] opened 2020-02-13 17:37 UTC
# Bug Report
On elements with ngClass, the media observers misbehave when printing. For example, if I have...

`<p class="text-left" ngClass.lt-sm="text-center">Some text here</p>`

...When I press Ctrl + P to print the page, then return, the text is centered (even though the screen size is still 1920px).

#### What is the expected behavior?
ngClass.lt-sm should be removed when printing is complete

#### What is the current behavior?
ngClass.lt-sm remains applied

#### What are the steps to reproduce?
*  [StackBlitz example](https://stackblitz.com/edit/angular-flex-layout-print-bug) 

#### What is the use-case or motivation for changing an existing behavior?
The screen looks incorrect when printing completes

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
I have tested in the latest Angular 8 and 9 releases with FlexLayout 8.0.0-beta.27 and 9.0.0-beta.29 respectively.

**Comment by alex-vg** [comment] 2020-04-03 13:45
I think the activatedBreakpoints are not properly restored in [stopPrinting()](https://github.com/angular/flex-layout/blob/8302998d88aa93c557c4fefd5ebab4b48cc90e2a/src/lib/core/media-marshaller/print-hook.ts#L174)

**Comment by alex-vg** [comment] 2020-04-03 14:36
My little dirty hack until this gets resolved....
```
export class CommonMaterialModule {
  lastValue;

  public constructor (
    iconFactory: InnogyIconsService,
    m: MediaMarshaller,
  ) {
    iconFactory.registerIcons();

    // hack until resolve: https://github.com/angular/flex-layout/issues/1201
    // @ts-ignore
    m.subject.subscribe((x) => {
      // @ts-ignore
      if (m.activatedBreakpoints.filter((b) => b.alias === 'print').length === 0) {
        // @ts-ignore
        this.lastValue = [...m.activatedBreakpoints];
      } else {
        // @ts-ignore
        m.activatedBreakpoints = [...this.lastValue];
        // @ts-ignore
        m.hook.collectActivations = () => {};
        // @ts-ignore
        m.hook.deactivations = [...this.lastValue];
      }
    });
  }

}

```

CommonMaterialModule is my only module that imports (and re-exports) FlexLayoutModule.

**Comment by PsyStorm25** [comment] 2020-05-20 16:36
@alex-vg thank you, your temporary fix works for me.
Seems this bug is a duplicate of #1228 (or the opposite).

**Comment by lambertwen** [comment] 2020-05-22 15:46
@alex-vg much appreciated! this fix did the trick.

**Comment by oneclickwebstudio** [comment] 2020-07-15 19:31
I'm using `"@angular/flex-layout": "^10.0.0-beta.32"` and the problem is still exists in todays. 
@alex-vg Could you show more detailed example please. Can't get your solution

**Comment by jnfaerch** [comment] 2020-11-12 08:40
Just chiming in as this bug is still present. Thx to @alex-vg for the temporary fix 👍

**Comment by FloNeu** [comment] 2021-03-04 13:07
Hello! Also ran into this bug - and was searching for hours - any reason this isn't resolved yet - the hack, did solf the issue for now!

**Comment by tyeety** [comment] 2021-03-17 10:48
Same bug here. I'm using ^11.0.0-beta.33 facing this error. even if I use `*ngIf` to remove elements before calling `window.print`, all elements use `fxFlex.sm` value.

**Comment by FloNeu** [comment] 2021-03-17 11:01
@tyeety  use the fix from @alex-vg - it restores the correct breakpoints after the print-window closes

**Comment by tyeety** [comment] 2021-03-17 11:15
Yes, Thank you @FloNeu and many thanks to @alex-vg for the solution. I imported this module in my root module and problem fixed for the entire solution. Hope to see that the problem is fixed in the very next version

**Comment by borox2k** [comment] 2021-04-27 15:31
@alex-vg thanks, your workaround still works 2021 angular 11
gracias

**Comment by Amirroracle** [comment] 2021-05-07 14:50
The issue with @alex-vg 's solution is that it restores the breakpoint but I found that the print preview is now broken instead.

**Comment by alex-vg** [comment] 2021-05-07 16:38
> The issue with @alex-vg 's solution is that it restores the breakpoint but I found that the print preview is now broken instead.

Which breakpoints are active when printing?
In case you want to set the print breakpoints: https://github.com/angular/flex-layout/blob/master/docs/documentation/BreakPoints.md

The workaround just restores breakpoints, it does not write print breakpoints on print-begin.

**Comment by rdanielst** [comment] 2021-05-20 14:02
Thank you very much @alex-vg !!!!!

**Comment by mopcweb** [comment] 2021-06-02 09:35
"@angular/flex-layout": "11.0.0-beta.33" - problem still exists

**Comment by dhammond371** [comment] 2021-12-14 15:42
Problem still exists

**Closed** 2021-12-29 06:55 UTC
Labels: bug, in-progress, has pr, P0, print

**Comment by CaerusKaru** [comment] 2021-12-29 06:57
First of all, thank you so much to @alex-vg for the patch that helped users while we tracked this issue. Contributions like this are invaluable and greatly appreciated by the entire team.

Now, the issue at hand, it turns out the root cause was a lot simpler than I thought it was going to be, and was just an issue of array reference assignment. In essence, we _were_ restoring breakpoints correctly, but then immediately _unassigning_ them. This led to the outcome all of you were seeing during print, which was obviously less than optimal. We've patched this in #1379, which has landed in the nightly release for those who'd like to try it out and report back. If not, it'll be in the next minor/major release.

Thank you all for your patience, and again, thank you @alex-vg.

**Comment by CaerusKaru** [comment] 2021-12-29 08:21
Ok quick followup here; my solution worked about half-way. The other half involved incorporating much of what @alex-vg's solution put forth. They were correct that our accumulation routine was not working, and that a better method is to just capture the breakpoints before the event and restore them after. Unfortunately, this went against the intention of the accumulator in the first place (we essentially had that approach to begin with); we support beforeprint and afterprint events as well for browsers that have quirky print behaviors. Therefore, in #1380, I have adapted this approach so that it works in both instances. This should close out the issue, and in testing with the docs site I think we're in the clear.

**Comment by Sergiobop** [comment] 2022-01-28 19:06
@CaerusKaru Thank you! Can we have a minor release with the patch?

**Comment by CaerusKaru** [comment] 2022-01-28 21:40
Patch release 13.0.0-beta.37 cut. Please let us know it you have any further issues.
