### ISSUE TITLE
MatchMediaObservable : Upgrade from 2.0.0-beta.1 to 2.0.0-beta.3

### ISSUE THREAD

**Issue by maxime1992** [angular/flex-layout#125] opened 2017-01-23 07:06 UTC
I tried to upgrade from 2.0.0-beta.1 to 2.0.0-beta.3 and it now breaks saying that :
`EXCEPTION: Uncaught (in promise): Error: Error in :0:0 caused by: this.media$.map is not a function TypeError: this.media$.map is not a function`

My code :

```js
constructor(@Inject(MatchMediaObservable) public media$) { }

this.media$
  .map((change: MediaChange) => { ... });
```
I looked in release notes and changelog but couldn't find anything about breaking change.

**Comment by ThomasBurleson** [comment] 2017-01-23 09:56
@maxime1992 - we will investigate. Thank you.

**Comment by ThomasBurleson** [comment] 2017-01-24 03:47
This works using the following in `package.json`:

```json
  "dependencies": {
    "@angular/flex-layout": "^2.0.0-beta.3",
}
```

**Comment by maxime1992** [comment] 2017-01-25 16:03
@ThomasBurleson I tried to do that but I still have the same error.

**Comment by ThomasBurleson** [comment] 2017-01-25 17:53
Are you importing the rxjs map operator?

**Comment by ThomasBurleson** [comment] 2017-01-25 17:53
Are you importing the rxjs map operator?

**Comment by maxime1992** [comment] 2017-01-25 19:55
Here's what I import : 

```
// statics
import 'rxjs/add/observable/throw';
// operators
import 'rxjs/add/operator/catch';
import 'rxjs/add/operator/delay';
import 'rxjs/add/operator/debounceTime';
import 'rxjs/add/operator/distinctUntilChanged';
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/let';
import 'rxjs/add/operator/switchMap';
import 'rxjs/add/operator/toPromise';
import 'rxjs/add/operator/withLatestFrom';
import 'rxjs/add/operator/combineLatest';

// observables
import 'rxjs/add/observable/empty';
```

So yes I do have `map` operator.

**Comment by ThomasBurleson** [comment] 2017-01-25 20:07
@maxime1992 - It is almost impossible to support issues with Plunkrs that our team can use to reproduce the issue. Unless you have a Plunkr that demonstrates this problem, I will be forced to close this issue.

> Plunkrs and source are critical to fast resolutions.

**Comment by ThomasBurleson** [comment] 2017-01-25 20:30
@maxime1992 - My apologies sir. The issue is within flex-layout: MatchMediaObservable is not a real observable. It is a **wrapper** around the observable because we expose a `isActive(<alias>)` method also. 

>This means the RxJS operators will NOT work because the reference is not a *real* observable.


I think the API for **MatchMediaObservable** needs to some work.

**Comment by ThomasBurleson** [comment] 2017-01-25 20:31
This will be fixed within the next 1-2 days. Thank you.

**Comment by ThomasBurleson** [comment] 2017-01-25 20:55
@maxime1992 - see https://github.com/angular/flex-layout/pull/133

**Comment by maxime1992** [comment] 2017-01-25 21:14
@ThomasBurleson I usually try to help as much as I can by giving a Plunkr but as I really thought it was no big deal I didn't provide one this time.

No problem, thank **you** for being so reactive :smile: 

Cheers :beers:

**Closed** 2017-01-26 22:30 UTC
Labels: bug, has Pull Request, in-progress
