### ISSUE TITLE
NPM Warning Message

### ISSUE THREAD

**Issue by ghaddon** [angular/flex-layout#502] opened 2017-11-13 21:56 UTC
#### Bug:

Getting the following NPM warning message:

npm WARN @angular/flex-layout@2.0.0-beta.10-4905443 requires a peer of @angular/core@~4.4.4 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/flex-layout@2.0.0-beta.10-4905443 requires a peer of @angular/common@~4.4.4 but none is installed. You must install peer dependencies yourself.

#### What is the expected behavior?

Would expect no warnings.

#### What is the current behavior?

Angular/flex-layout seems to work.

#### What are the steps to reproduce?
Just update any NPM package.

#### What is the use-case or motivation for changing an existing behavior?

Would like to see a more meaningful error after each NPM update.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular CLI: 1.5.0
Node: 8.9.0
OS: win32 x64
Angular: 5.0.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.0.0-rc0
@angular/cli: 1.5.0
@angular/flex-layout: 2.0.0-beta.10-4905443
@angular/material: 5.0.0-rc0
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.0
typescript: 2.4.2
webpack: 3.8.1

#### Is there anything else we should know?

Nothing

**Comment by jotatoledo** [comment] 2017-11-14 07:59
duplicate of #494

**Comment by ThomasBurleson** [comment] 2017-12-14 22:35
Fixed with today's 2.0.0-beta.12 release. See SHA 62457a5972 and [CHANGELOG](https://github.com/angular/flex-layout/blob/master/CHANGELOG.md)

**Closed by ThomasBurleson** 2017-12-14 22:35 UTC
Labels: build, P1 - Urgent
