### ISSUE TITLE
Flex-layout doesn't work properly with SSR and lazy modules

### ISSUE THREAD

**Issue by atmman9001** [angular/flex-layout#657] opened 2018-03-12 14:58 UTC
#### Bug, feature request, or proposal:

Flex-layout adds empty stylesheets during server side rendering for lazy modules.

#### What is the expected behavior?
CSS shouldn't be empty.

#### Reproduction repo

[https://github.com/atmman9001/universal-starter/](https://github.com/atmman9001/universal-starter/) **flex-layout-issue** branch

#### What are the steps to reproduce?

1. pull the repo
2. checkout to **flex-layout-issue** branch
3. npm i
4. **npm run build:ssr && npm run serve:ssr**
5. Go to [http://localhost:4000/lazy](http://localhost:4000/lazy)
6. Check *style.flex-layout-ssr* contains just `{}` - [Example screenshot](http://prntscr.com/iq562x)

**Comment by CaerusKaru** [comment] 2018-03-12 15:03
Confirmed as an issue, likely because the lazy module is pulling in the browser providers instead of the server providers.

Will try to get a fix in this week, but @ThomasBurleson is currently away, so it might take a little longer to get it merged.

**Comment by atmman9001** [comment] 2018-03-12 15:05
@CaerusKaru - Thanks for the quick reply.

**Comment by stephengardner** [comment] 2018-03-12 20:19
Phew glad I found this issue.  This is huge since Angular best-practices is really to lazy-load every module.  All of my pages therefore have a flash of improperly-styled content.  Looking forward to a fix as this is sort of a big deal

**Comment by CaerusKaru** [comment] 2018-03-12 20:47
@stephengardner I agree, and this is my top priority as of this morning. Unfortunately our DI setup for this library is a little muddled. As I mentioned in #373, this will be completely resolved when v6 arrives, but until then, and regardless, I'm working on a fix for 5.x

**Comment by stephengardner** [comment] 2018-03-12 20:50
@CaerusKaru fantastic! Knowing it's a known issue and in-progress is all the news I need.  Looking forward to it

**Comment by CaerusKaru** [comment] 2018-03-12 21:14
@stephengardner @atmman9001 Ok I've got the fix working, it's in PR #659. Unfortunately, this likely won't get merged until @ThomasBurleson gets back sometime next week. If necessary you can build it from the remote branch until then

**Comment by stephengardner** [comment] 2018-03-13 02:57
Thanks @CaerusKaru!

**Comment by atmman9001** [comment] 2018-03-13 08:23
Great thanks @CaerusKaru!

**Closed** 2018-03-13 19:03 UTC
Labels: P1: urgent, bug, has pr, ssr
