### ISSUE TITLE
Missing https://github.com/angular/flex-layout/wiki/fxFlexAlign-API

### ISSUE THREAD

**Issue by mackelito** [angular/flex-layout#335] opened 2017-07-06 09:30 UTC
link on https://github.com/angular/flex-layout/wiki/API-Documentation to fxFlexAlign docs is not working.. it redirects to https://github.com/angular/flex-layout/wiki

**Comment by ThomasBurleson** [comment] 2017-07-11 14:14
Duplicate of #334

**Closed by ThomasBurleson** 2017-07-11 14:14 UTC
