### ISSUE TITLE
Compilation error in flex-offset.d.ts

### ISSUE THREAD

**Issue by pueaau** [angular/flex-layout#941] opened 2018-12-19 12:06 UTC
# Bug Report

#### What is the expected behavior?
A clean compile.

#### What is the current behavior?
Compilation fails with an error that seems to be entirely within flex-layout.
ERROR in node_modules/@angular/flex-layout/flex/typings/flex-offset/flex-offset.d.ts(18,9): error TS2411: Property ''margin-top'' of type 'undefined' is not assignable to string index type 'string'.

#### What are the steps to reproduce?
Since no error in my code is given I'd expect you to get this with any flex-layout project when you call 'ng serve'.

#### What is the use-case or motivation for changing an existing behavior?
I'm not going to spell out why I would like a error-free compile.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Linux
typescript 3.1.6
@angular/core@7.1.4
@angular/material@7.2.0
@angular/cli@7.1.3
@angular/flex-layout@7.0.0-beta.21

#### Is there anything else we should know?
No compilation error with
@angular/flex-layout@7.0.0-beta.19

**Comment by CaerusKaru** [comment] 2018-12-19 13:38
Duplicate of #928

**Closed by CaerusKaru** 2018-12-19 13:38 UTC
