### ISSUE TITLE
Compile error with fullTemplateTypeCheck and strictInjectionParameters

### ISSUE THREAD

**Issue by GlauberF** [angular/flex-layout#1105] opened 2019-07-24 12:16 UTC
## Environment

Angular CLI: 8.1.2
Node: 10.15.3
OS: linux x64
Angular: 8.1.2
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.801.2
@angular-devkit/build-angular      0.801.2
@angular-devkit/build-optimizer    0.801.2
@angular-devkit/build-webpack      0.801.2
@angular-devkit/core               8.1.2
@angular-devkit/schematics         8.1.2
@angular/cdk                       8.1.1
@angular/flex-layout               8.0.0-beta.26
@angular/material                  8.1.1
@angular/material-moment-adapter   8.1.1
@ngtools/webpack                   8.1.2
@schematics/angular                8.1.2
@schematics/update                 0.801.2
rxjs                               6.5.2
typescript                         3.4.5
webpack                            4.35.2

## tsconfig.json
`
"angularCompilerOptions": {
        "fullTemplateTypeCheck": true,
        "strictInjectionParameters": true
    }
`

## Bug
When running the command to build or start, generates the error of the text and image below.

```
ERROR in node_modules/@angular/flex-layout/extended/typings/class/class.d.ts:30:23 - error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).

30     static ngBaseDef: ɵngcc0.ɵɵBaseDef;
                         ~~~~~~~~~~~~~~~~
node_modules/@angular/flex-layout/extended/typings/img-src/img-src.d.ts:38:23 - error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).

38     static ngBaseDef: ɵngcc0.ɵɵBaseDef;
                         ~~~~~~~~~~~~~~~~
node_modules/@angular/flex-layout/flex/typings/flex/flex.d.ts:50:23 - error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).

50     static ngBaseDef: ɵngcc0.ɵɵBaseDef;
                         ~~~~~~~~~~~~~~~~
node_modules/@angular/flex-layout/grid/typings/align-columns/align-columns.d.ts:28:23 - error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).

28     static ngBaseDef: ɵngcc0.ɵɵBaseDef;
                         ~~~~~~~~~~~~~~~~
node_modules/@angular/flex-layout/grid/typings/align-rows/align-rows.d.ts:28:23 - error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).

28     static ngBaseDef: ɵngcc0.ɵɵBaseDef;
                         ~~~~~~~~~~~~~~~~
node_modules/@angular/flex-layout/grid/typings/areas/areas.d.ts:31:23 - error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).

31     static ngBaseDef: ɵngcc0.ɵɵBaseDef;
                         ~~~~~~~~~~~~~~~~
node_modules/@angular/flex-layout/grid/typings/auto/auto.d.ts:31:23 - error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).

31     static ngBaseDef: ɵngcc0.ɵɵBaseDef;
                         ~~~~~~~~~~~~~~~~
node_modules/@angular/flex-layout/grid/typings/columns/columns.d.ts:32:23 - error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).

32     static ngBaseDef: ɵngcc0.ɵɵBaseDef;
                         ~~~~~~~~~~~~~~~~
node_modules/@angular/flex-layout/grid/typings/gap/gap.d.ts:31:23 - error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).

31     static ngBaseDef: ɵngcc0.ɵɵBaseDef;
                         ~~~~~~~~~~~~~~~~
node_modules/@angular/flex-layout/grid/typings/rows/rows.d.ts:32:23 - error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).

32     static ngBaseDef: ɵngcc0.ɵɵBaseDef;
                         ~~~~~~~~~~~~~~~~
node_modules/@angular/material/menu/typings/menu.d.ts:166:23 - error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).

166     static ngBaseDef: ɵngcc0.ɵɵBaseDef;
```

![Captura de Tela_selecionar área_20190724093442](https://user-images.githubusercontent.com/11314585/61793830-4607ff00-adf6-11e9-814c-b6bc86f3fb55.png)

**Comment by thejeff77** [comment] 2019-07-25 14:08
Also seeing this with angular 8.1.0

Angular CLI: 8.1.0
Node: 12.1.0
OS: Windows 10 17134.885
Angular: 8.1.0

```
ERROR in node_modules/@angular/material/menu/typings/menu.d.ts:166:23 - error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).

166     static ngBaseDef: ɵngcc0.ɵɵBaseDef;
```

Any suggestions on workarounds would be appreciated

**Comment by CaerusKaru** [comment] 2019-07-25 14:17
Fixed by https://github.com/angular/angular/pull/31210

**Comment by CaerusKaru** [comment] 2019-07-25 14:18
To try it now, please use v8.2.0-next.X

**Closed by CaerusKaru** 2019-07-25 14:17 UTC

**Comment by thejeff77** [comment] 2019-07-25 14:31
For which dependencies?

```
> npm install
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @angular/cdk@8.2.0-next.X
```

**Comment by thejeff77** [comment] 2019-07-25 14:52
Just tried this - and it failed. 

```
    "@schematics/angular": "8.2.0-next.1",
    "@angular-devkit/schematics-cli": "^0.801.2",
    "@angular/animations": "8.1.1",
    "@angular/cdk": "8.1.1",
    "@angular/common": "8.1.1",
    "@angular/compiler": "8.1.1",
    "@angular/core": "8.1.1",
    "@angular/forms": "8.1.1",
    "@angular/material": "8.1.1",
    "@angular/platform-browser": "8.1.1",
    "@angular/platform-browser-dynamic": "8.1.1",
    "@angular/router": "8.1.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "0.802.0-next.1",
    "@angular/cli": "8.2.0-next.1",
    "@angular/compiler-cli": "8.1.1",
    "@angular/language-service": "8.1.1"
  }
```

Error:
```

ERROR in node_modules/@angular/material/menu/typings/menu.d.ts:166:23 - error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).

166     static ngBaseDef: ɵngcc0.ɵɵBaseDef;
```

**Comment by CaerusKaru** [comment] 2019-07-25 15:28
This is not a CLI issue. The PR I linked is in the angular/angular repository, so you’ll need to install the 8.2 version of those packages (core, common, etc)

**Comment by thejeff77** [comment] 2019-07-25 15:51
@CaerusKaru thank you for your timely feedback. Let me know if there is a better place to put this discussion, also the below is the best I could find for all packages - for a lot of these I did not see a next.X version - am I missing something?

Build error:
```
ERROR in node_modules/@angular/material/menu/typings/menu.d.ts:169:22 - error TS-996002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class

169 export declare class MatMenu extends _MatMenuBase {
```
```

  "dependencies": {
    "@schematics/angular": "8.2.0-next.1",
    "@angular-devkit/schematics-cli": "^0.801.2",
    "@angular/animations": "8.1.1",
    "@angular/cdk": "8.1.1",
    "@angular/common": "8.2.0-next.2",
    "@angular/compiler": "8.2.0-next.2",
    "@angular/core": "8.2.0-next.2",
    "@angular/forms": "8.1.1",
    "@angular/material": "8.1.1",
    "@angular/platform-browser": "8.1.1",
    "@angular/platform-browser-dynamic": "8.1.1",
    "@angular/upgrade": "8.2.0-next.2",
    "@angular/router": "8.1.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "0.802.0-next.1",
    "@angular/cli": "8.2.0-next.1",
    "@angular/compiler-cli": "8.2.0-next.1",
    "@angular/language-service": "8.2.0-next.1"
  }
```

Thank you for any additional information

**Comment by avoliva** [comment] 2019-07-30 22:04
Looks like the issue is in material and there's no next version for that one.
