### ISSUE TITLE
[SSR] Buttons not styled 

### ISSUE THREAD

**Issue by marcinkunert** [angular/flex-layout#647] opened 2018-03-08 14:33 UTC
#### Bug, feature request, or proposal:
Buttons are not styled when rendered on server side.

#### What is the expected behavior?
Buttons should be rendered exactly like on client side

#### What is the current behavior?
SSR button:
![image](https://user-images.githubusercontent.com/2963232/37156195-b6bb46fa-22e5-11e8-81f1-16231383893d.png)
Browser button:
![image](https://user-images.githubusercontent.com/2963232/37156223-c83778e0-22e5-11e8-9ecf-9f3cad8945da.png)

I've included `FlexLayoutServerModule` to `AppServerModule`. Is there something else I have to do to get the desired behavior?

**Comment by sylvaindumont** [comment] 2018-03-08 14:41
@marcinkunert  if you use material, buttons not styled in ssr most likely come from https://github.com/angular/material2/issues/9865 and should be fixed when https://github.com/angular/material2/pull/9771 will be merged and released

**Comment by CaerusKaru** [comment] 2018-03-08 14:44
Duplicate of https://github.com/angular/material2/issues/9865

**Closed by CaerusKaru** 2018-03-08 14:44 UTC
