### ISSUE TITLE
Not working with Angular 9

### ISSUE THREAD

**Issue by MoroccanGeek** [angular/flex-layout#1276] opened 2020-06-17 19:22 UTC
# Bug Report

FlexLayout V10.0.0-beta.32 is not working with angular V9.0.7

To solve this, i had to move to Flexlayout V9.0.0-beta.31

#### version of Angular affected:
I'm using Angular v9.0.7

**Comment by CaerusKaru** [comment] 2020-06-17 19:42
Duplicate of #1274

**Closed by CaerusKaru** 2020-06-17 19:42 UTC
