### ISSUE TITLE
@angular/flex-layout compatibility issues with @angular/core @angular/common packages

### ISSUE THREAD

**Issue by gitfortee** [angular/flex-layout#630] opened 2018-02-25 15:59 UTC
#### What is current behavior?

Getting package version conflicts resulting in UNMET PEER DEPENDENCY & npm warn 

See details below.

#### What are the steps to reproduce?
Issued an npm-check-updates command 

```
>ncu -u -a 

>npm install 
```

and then: 

1. Trying to install the latest version of @angular/flex-layout

```
>npm install --save @angular/flex-layout
+-- UNMET PEER DEPENDENCY @angular/common@5.2.6
+-- UNMET PEER DEPENDENCY @angular/core@5.2.6 

npm WARN @angular/flex-layout@2.0.0-beta.12 requires a peer of @angular/core@~5.1.0 but none was installed.
npm WARN @angular/flex-layout@2.0.0-beta.12 requires a peer of @angular/common@~5.1.0 but none was installed
```

2. Trying to install a downgraded version of @angular/flex-layout

```
>npm install --save @angular/flex-layout@2.0.0-beta.10-4905443
+-- UNMET PEER DEPENDENCY @angular/common@5.2.6
+-- UNMET PEER DEPENDENCY @angular/core@5.2.6 

npm WARN @angular/flex-layout@2.0.0-beta.10-4905443 requires a peer of @angular/core@~4.4.4 but none was installed.
npm WARN @angular/flex-layout@2.0.0-beta.10-4905443 requires a peer of @angular/common@~4.4.4 but none was installed. 
```

Versions I have for @angular/core & @angular/common as follows: 

```
"@angular/common": "^5.2.6",
"@angular/core": "^5.2.6",
```

My package.json: 

```
"dependencies": {
    "@angular/animations": "^5.2.6",
    "@angular/cdk": "^5.2.2",
    "@angular/common": "^5.2.6",
    "@angular/compiler": "^5.2.6",
    "@angular/core": "^5.2.6",
    "@angular/forms": "^5.2.6",
    "@angular/http": "^5.2.6",
    "@angular/material": "^5.2.2",
    "@angular/platform-browser": "^5.2.6",
    "@angular/platform-browser-dynamic": "^5.2.6",
    "@angular/router": "^5.2.6",
    "@progress/kendo-angular-buttons": "^3.0.3",
    "@progress/kendo-angular-charts": "^2.0.2",
    "@progress/kendo-angular-dateinputs": "^2.1.1",
    "@progress/kendo-angular-dropdowns": "^2.0.2",
    "@progress/kendo-angular-excel-export": "^1.0.6",
    "@progress/kendo-angular-grid": "^2.1.0",
    "@progress/kendo-angular-inputs": "^2.1.1",
    "@progress/kendo-angular-intl": "^1.3.1",
    "@progress/kendo-angular-l10n": "^1.0.6",
    "@progress/kendo-angular-ripple": "^0.2.3",
    "@progress/kendo-data-query": "^1.2.0",
    "@progress/kendo-drawing": "^1.5.1",
    "@progress/kendo-theme-default": "^2.48.1",
    "angular-font-awesome": "^3.1.2",
    "core-js": "^2.5.3",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.8",
    "jwt-decode": "^2.2.0",
    "rxjs": "^5.5.6",
    "zone.js": "^0.8.20"
  },
  "devDependencies": {
    "@angular/cli": "^1.7.1",
    "@angular/compiler-cli": "^5.2.6",
    "@angular/language-service": "^5.2.6",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~9.4.6",
    "codelyzer": "~4.1.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.4.1",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.3.0",
    "ts-node": "~5.0.0",
    "tslint": "~5.9.1",
    "typescript": "~2.6.2"
  }
```

**Comment by jotatoledo** [comment] 2018-02-25 18:51
Next release should update the `peerDependencies` of the package.

**Comment by CaerusKaru** [comment] 2018-02-25 18:58
Duplicate of #622

**Closed by CaerusKaru** 2018-02-25 18:59 UTC
