### ISSUE TITLE
Add support for ng-add

### ISSUE THREAD

**Issue by abbassiddiqi** [angular/flex-layout#886] opened 2018-11-13 15:48 UTC
# Feature Request

#### What is the desired behavior?
We should be able to install flex-layout via angular-cli.
```
ng add @angular/flex-layout
```

#### What is the use-case or motivation for the desired behavior?
The @angular/cli suggest this:
> The package that you are trying to add does not support schematics. You can try using a different version of the package or contact the package author to add ng-add support.

#### Is there anything else we should know?

You guys are awesome. :-)

**Comment by CaerusKaru** [comment] 2018-11-13 15:59
Duplicate of #707

**Closed by CaerusKaru** 2018-11-13 15:59 UTC
