### ISSUE TITLE
Docs links broken on gd container APIs (?)

### ISSUE THREAD

**Issue by ChuckIrvine** [angular/flex-layout#1155] opened 2019-11-25 15:59 UTC
From: https://github.com/angular/flex-layout/wiki/Declarative-API-Overview
Click on: "gdAreas"
Am taken to: https://github.com/angular/flex-layout/wiki which is the home page.

All of the gd* links seem likewise broken.

**Comment by CaerusKaru** [comment] 2019-11-25 16:05
Duplicate of #1026

**Closed by CaerusKaru** 2019-11-25 16:05 UTC
