### ISSUE TITLE
fxShow does not seem to work with custom breakpoints

### ISSUE THREAD

**Issue by Mufasa** [angular/flex-layout#758] opened 2018-06-04 14:58 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Custom breakpoints should respect **fxShow** and **fxHide**

#### What is the current behavior?
Only **fxHide** works

#### What are the steps to reproduce?
https://stackblitz.com/edit/flexlayout-h9m1hc

The behaviour can be observed by changing the width of the rendered page. As you reduce the width the header at the top will change to **MobilePortrait**. At this point I expect this section of my HTML (within **app.component.html**) to be displayed:
```
<section 
    fxHide 
    fxShow.mobile.portrait="true"> 
  fxShow.mobile.portrait
</section>
```
However, all my sections which hide their content by default and only show when the specific media query matches do not seem to be working.

The opposite seems to work - i.e all sections that are shown by default but only hidden when the specific media query matches work as expected.

#### What is the use-case or motivation for changing an existing behavior?
I want to be able to use my custom breakpoint directives for both showing and hiding certain elements on the page.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.0.3
Material 6.2.0
macOS High Sierra v10.13.4
Chrome Version 66.0.3359.181 (Official Build) (64-bit)

#### Is there anything else we should know?
I don't think so

**Comment by CaerusKaru** [comment] 2018-12-01 15:34
@Mufasa can you see if this has been patched as of the latest nightly build?

**Comment by asnaseer-resilient** [comment] 2018-12-01 21:39
@CaerusKaru I just tried updating my stackblitz to the latest angular components and it still fails as described in this issue. The latest version I am using are:
Angular 7.1.0
Material 7.1.0
flex-layout 7.0.0-beta.19

**Comment by CaerusKaru** [comment] 2018-12-01 21:45
You need to switch to the nightly builds of Angular, which is on angular/flex-layout-builds

**Comment by asnaseer-resilient** [comment] 2018-12-01 22:31
@CaerusKaru Thanks, I tried that and it does indeed install the dependency now. However, I now see this error displayed in the browser:
Error in /~/src/app/custom-show-hide.directive.ts (7:9)
Object prototype may only be an Object or null: undefined

The console shows these stack traces:
```
Unhandled Promise rejection: Object prototype may only be an Object or null: undefined ; Zone: <root> ; Task: null ; Value: TypeError: Object prototype may only be an Object or null: undefined
    at setPrototypeOf (<anonymous>)
    at __extends (custom-show-hide.directive.ts:7)
    at eval (custom-show-hide.directive.ts:28)
    at Object.eval (custom-show-hide.directive.ts:265)
    at eval (custom-show-hide.directive.ts:268)
    at eval (custom-show-hide.directive.ts:269)
    at eval (<anonymous>)
    at Qt (webcontainer.8e8160f5301340f0d8a.js:15)
    at webcontainer.8e8160f5301340f0d8a.js:15
    at U (webcontainer.8e8160f5301340f0d8a.js:15) TypeError: Object prototype may only be an Object or null: undefined
    at setPrototypeOf (<anonymous>)
    at __extends (https://flexlayout-h9m1hc.stackblitz.io/~/src/app/custom-show-hide.directive.ts:7:9)
    at eval (https://flexlayout-h9m1hc.stackblitz.io/~/src/app/custom-show-hide.directive.ts:28:5)
    at Object.eval (https://flexlayout-h9m1hc.stackblitz.io/~/src/app/custom-show-hide.directive.ts:265:2)
    at eval (https://flexlayout-h9m1hc.stackblitz.io/~/src/app/custom-show-hide.directive.ts:268:4)
    at eval (https://flexlayout-h9m1hc.stackblitz.io/~/src/app/custom-show-hide.directive.ts:269:3)
    at eval (<anonymous>)
    at Qt (https://c.staticblitz.com/d/webcontainer.8e8160f5301340f0d8a.js:15:30145)
    at https://c.staticblitz.com/d/webcontainer.8e8160f5301340f0d8a.js:15:38799
    at U (https://c.staticblitz.com/d/webcontainer.8e8160f5301340f0d8a.js:15:13565)
api.onUnhandledError @ zone.js:665
```

```
TypeError: Object prototype may only be an Object or null: undefined
    at setPrototypeOf (<anonymous>)
    at __extends (custom-show-hide.directive.ts:7)
    at eval (custom-show-hide.directive.ts:28)
    at Object.eval (custom-show-hide.directive.ts:265)
    at eval (custom-show-hide.directive.ts:268)
    at eval (custom-show-hide.directive.ts:269)
    at eval (<anonymous>)
    at Qt (webcontainer.8e8160f5301340f0d8a.js:15)
    at webcontainer.8e8160f5301340f0d8a.js:15
    at U (webcontainer.8e8160f5301340f0d8a.js:15)
```

**Comment by CaerusKaru** [comment] 2018-12-01 22:32
I'm not sure what the issue is, but it could be somewhere else in the app. Could you try replicating it in a repo instead?

**Comment by asnaseer-resilient** [comment] 2018-12-01 22:41
@CaerusKaru I deleted the flex-layout dependency and then added it back into stackblitz. Now it seems to be ok but still exhibits the error described in this issue.

**Comment by CaerusKaru** [comment] 2018-12-01 22:42
Please save your version so that I can see it (my link still shows beta 19 as a dep)

**Comment by asnaseer-resilient** [comment] 2018-12-01 22:44
I did save it, my stackblitz package.json shows this for flex-layout:

 "@angular/flex-layout": "https://github.com/angular/flex-layout-builds",

**Comment by CaerusKaru** [comment] 2018-12-01 22:45
I'm using this link: https://stackblitz.com/edit/flexlayout-h9m1hc. On a hard refresh it still shows beta 19 as the dep version

**Comment by asnaseer-resilient** [comment] 2018-12-01 22:48
That is exactly the same as the one I am using. I also performed a hard refresh and this is what it shows in the `package.json` file:
```
{
  "name": "flexlayout-h9m1hc",
  "version": "0.0.0",
  "private": true,
  "dependencies": {
    "@angular-devkit/build-angular": "0.11.0",
    "@angular/animations": "7.1.1",
    "@angular/cdk": "7.1.0",
    "@angular/cli": "7.1.0",
    "@angular/common": "7.1.1",
    "@angular/compiler": "7.1.1",
    "@angular/core": "7.1.1",
    "@angular/flex-layout": "https://github.com/angular/flex-layout-builds",
    "@angular/forms": "7.1.1",
    "@angular/material": "7.1.0",
    "@angular/platform-browser": "7.1.1",
    "@angular/platform-browser-dynamic": "7.1.1",
    "@angular/router": "7.1.1",
    "core-js": "2.5.7",
    "hammerjs": "2.0.8",
    "rxjs": "6.3.3",
    "rxjs-compat": "6.3.3",
    "zone.js": "0.8.26"
  },
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.10.0",
    "@angular/cli": "~7.0.2",
    "@angular/compiler-cli": "~7.0.0",
    "@angular/language-service": "~7.0.0",
    "@types/node": "~8.9.4",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.1.1"
  }
}
```

I don't understand why you don't see this as well?

**Comment by CaerusKaru** [comment] 2018-12-01 22:49
Now I see it, checking again. Thanks for clearing that up :+1:

**Comment by CaerusKaru** [comment] 2018-12-01 23:07
Ok so I don't know why, but StackBlitz is not actually installing the nightly build. It says it is in the package.json, but when I try to import the new `MediaObserver`, it can't find it, and it also says the `VERSION` (aka `import {VERSION} from '@angular/flex-layout'; console.log(VERSION.full);`) === `7.0.0-beta.19`. If it were on the nightly, it should say `7.0.0-beta.19-1205588`

**Comment by Mufasa** [comment] 2018-12-02 18:11
I tried creating a local project using angular CLI to recreate the stackblitz one. I first created it by installing the @angular/flex-layout latest repo from npm. However, this gave me an error saying that `DISABLE_DEFAULT_BREAKPOINTS` is not exported from `@angular/flex-layout`. My `app.module.ts` file was using this as follows:
```
...
import { FlexLayoutModule, DISABLE_DEFAULT_BREAKPOINTS } from '@angular/flex-layout';
...
  providers: [
    CustomBreakPointsProvider,
    { provide: DISABLE_DEFAULT_BREAKPOINTS, useValue: true }
  ],
```
Looking through the latest documentation I see this is still valid and I therefore expected it to work.

Has this method of disabling the default breakpoints changed in the latest version?

**Comment by Mufasa** [comment] 2018-12-02 18:14
Please ignore my previous comment. Just read this: https://github.com/angular/flex-layout/blob/master/CHANGELOG.md#breaking-changes

**Comment by Mufasa** [comment] 2018-12-02 18:34
OK, now if I use `angular/flex-layout-builds` then I see that the constructor for `ShowHideDirective` has been changed - it seems to take one extra parameter now - `LayoutConfigOptions`. I changed my `CustomShowHideDirective` class (which extends `ShowHideDirective`) to pass in `{}` as the last parameter. When I serve this using `ng serve` I now see the following stacktrace in the console:
```
ERROR Error: StaticInjectorError(AppModule)[AppComponent -> ObservableMedia]: 
  StaticInjectorError(Platform: core)[AppComponent -> ObservableMedia]: 
    NullInjectorError: No provider for ObservableMedia!
    at NullInjector.push../node_modules/@angular/core/fesm5/core.js.NullInjector.get (core.js:717)
    at resolveToken (core.js:954)
    at tryResolveToken (core.js:898)
    at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (core.js:795)
    at resolveToken (core.js:954)
    at tryResolveToken (core.js:898)
    at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (core.js:795)
    at resolveNgModuleDep (core.js:17656)
    at NgModuleRef_.push../node_modules/@angular/core/fesm5/core.js.NgModuleRef_.get (core.js:18345)
    at resolveDep (core.js:18716)
```

**Comment by CaerusKaru** [comment] 2018-12-02 18:52
@Mufasa that is an unfortunate regression that will be patched in the next commit. Until then, please use the new `MediaObserver` API (exactly the same, except you subscribe to `mediaObserver.media$` instead of directly to it).

**Comment by Mufasa** [comment] 2018-12-02 18:53
@CaerusKaru OK, after a lot of playing around, I think I have worked out how to use the latest version. I changed my `app.module.ts` to have:
```
...
imports: [
...
FlexLayoutModule.withConfig({ disableDefaultBps: true }, CUSTOM_BREAKPOINTS),
...
],
...
```
`CUSTOM_BREAKPOINTS` is defined in `custom-breakpoints.ts` as:
```
const MOBILE_PORTRAIT = 'screen and (orientation: portrait) and (max-width: 599px)';
const TABLET_PORTRAIT = 'screen and (orientation: portrait) and (min-width: 600px) and (max-width: 839px)';
const WEB_PORTRAIT = 'screen and (orientation: portrait) and (min-width: 840px)';

const MOBILE_LANDSCAPE = 'screen and (orientation: landscape) and (max-width: 959px)';
const TABLET_LANDSCAPE = 'screen and (orientation: landscape) and (min-width: 960px)  and (max-width: 1279px)';
const WEB_LANDSCAPE = 'screen and (orientation: landscape) and (min-width: 1280px)';

const SCREEN_TYPES = {
  MOBILE: `${MOBILE_PORTRAIT}, ${MOBILE_LANDSCAPE}`,
  TABLET: `${TABLET_PORTRAIT}, ${TABLET_LANDSCAPE}`,
  WEB: `${WEB_PORTRAIT}, ${WEB_LANDSCAPE}`,

  MOBILE_PORTRAIT: `${MOBILE_PORTRAIT}`,
  TABLET_PORTRAIT: `${TABLET_PORTRAIT}`,
  WEB_PORTRAIT: `${WEB_PORTRAIT}`,

  MOBILE_LANDSCAPE: `${MOBILE_LANDSCAPE}`,
  TABLET_LANDSCAPE: `${TABLET_LANDSCAPE}`,
  WEB_LANDSCAPE: `${WEB_LANDSCAPE}`
};

export const CUSTOM_BREAKPOINTS = [
  { 'alias': 'mobile', 'mediaQuery': SCREEN_TYPES.MOBILE },
  { 'alias': 'mobile.portrait', 'mediaQuery': SCREEN_TYPES.MOBILE_PORTRAIT },
  { 'alias': 'mobile.landscape', 'mediaQuery': SCREEN_TYPES.MOBILE_LANDSCAPE },

  { 'alias': 'tablet', 'mediaQuery': SCREEN_TYPES.TABLET },
  { 'alias': 'tablet.portrait', 'mediaQuery': SCREEN_TYPES.TABLET_PORTRAIT },
  { 'alias': 'tablet.landscape', 'mediaQuery': SCREEN_TYPES.TABLET_LANDSCAPE },

  { 'alias': 'web', 'mediaQuery': SCREEN_TYPES.WEB },
  { 'alias': 'web.portrait', 'mediaQuery': SCREEN_TYPES.WEB_PORTRAIT },
  { 'alias': 'web.landscape', 'mediaQuery': SCREEN_TYPES.WEB_LANDSCAPE }
];
```
My `CustomShowHideDirective` construction was changed to:
```
...
@Directive({
  selector: `
    [fxHide.mobile],
    [fxShow.mobile],
    [fxHide.mobile.portrait],
    [fxShow.mobile.portrait],
    [fxHide.mobile.landscape],
    [fxShow.mobile.landscape],
    [fxHide.tablet],
    [fxShow.tablet],
    [fxHide.tablet.portrait],
    [fxShow.tablet.portrait],
    [fxHide.tablet.landscape],
    [fxShow.tablet.landscape],
    [fxHide.web],
    [fxShow.web],
    [fxHide.web.portrait],
    [fxShow.web.portrait],
    [fxHide.web.landscape],
    [fxShow.web.landscape]
  `
})
export class CustomShowHideDirective extends ShowHideDirective {
  constructor(monitor: MediaMonitor,
              @Optional() @Self() protected layout: LayoutDirective,
              protected elRef: ElementRef,
              protected styleUtils: StyleUtils,
              @Inject(PLATFORM_ID) protected platformId: Object,
              @Optional() @Inject(SERVER_TOKEN) protected serverModuleLoaded: boolean) {
    super(monitor, layout, elRef, styleUtils, platformId, serverModuleLoaded, { disableDefaultBps: true });
  }

  @Input('fxHide.mobile')
  set hideMobile(val) {
    this._cacheInput('showMobile', negativeOf(val));
  }
...
```
And, I replaced the use of `ObservableMedia` with `MediaQuery` as follows:
```
...
constructor(public media: MediaObserver, private changeDetector: ChangeDetectorRef) { }

  ngAfterViewInit() {
    this.updateGrid(null);
    this.media.media$.subscribe(change => { this.updateGrid(change); });
  }
```
I thought this had fixed all the bugs but then I noticed that mobile.portrait is no longer fired by the media observer.

**Comment by CaerusKaru** [comment] 2018-12-02 18:55
@Mufasa does that mean that the custom breakpoints at least are working? If so, can you close this and open a `MediaObserver` issue?

**Comment by Mufasa** [comment] 2018-12-02 18:56
@CaerusKaru Strike my last line in my previous comments. I had not set my browser window to the correct aspect ratio for mobile.portrait to be fired.

Everything is now working - fxShow/Hide all working as expected.

Many thanks for fixing this.

**Closed** 2018-12-02 18:57 UTC
Labels: P2, bug, custom breakpoints
