### ISSUE TITLE
Flex layout issues a network request to /null

### ISSUE THREAD

**Issue by zlepper** [angular/flex-layout#715] opened 2018-04-16 18:08 UTC
#### Bug, feature request, or proposal:
Bug i would assume

#### What is the expected behavior?
No request to /null

#### What is the current behavior?
Somehow a request is send to /null

#### What are the steps to reproduce?
I have absolutely no idea, what so ever, but it is 100% consistent for exactly one of the 1000 elements I have styled using fxLayout

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

    "@angular/animations": "5.2.6",
    "@angular/cdk": "5.2.0",
    "@angular/cli": "1.7.3",
    "@angular/common": "5.2.6",
    "@angular/compiler": "5.2.6",
    "@angular/core": "5.2.6",
    "@angular/flex-layout": "2.0.0-beta.12",
    "@angular/forms": "5.2.6",
    "@angular/http": "5.2.6",
    "@angular/platform-browser": "5.2.6",
    "@angular/platform-browser-dynamic": "5.2.6",
    "@angular/platform-server": "5.2.6",
    "@angular/router": "5.2.6",
    "@angular/service-worker": "5.2.6",

Browser: Chrome

#### Is there anything else we should know?

You will likely want to close this anyway, but incase somebody else comes across this, it doesn't seem to be causing anything bad, or breaking anything. 
![chrome_2018-04-16_20-05-05](https://user-images.githubusercontent.com/1499810/38826919-8819947e-41b1-11e8-8e66-6d6759e4e2b6.png)
![chrome_2018-04-16_20-05-27](https://user-images.githubusercontent.com/1499810/38826920-883617c0-41b1-11e8-86fd-b15a1081e0ab.png)

I'm sorry that I cannot provide anymore info, but i have no clue how or why that is happening. And I haven't seen that before.

**Comment by CaerusKaru** [comment] 2018-04-16 18:14
This is definitely a weird one. Can you provide a StackBlitz reproduction that we can investigate?

**Comment by zlepper** [comment] 2018-04-16 18:50
Sorry, but as I also mention in the issue description, i have no clue at all what is causing this, and no matter what I try in stackblitz, it doesn't seem to be reproducible. 

This is probably as close as I can get to the area I think it's happening in: https://stackblitz.com/edit/angular-flex-layout-seed-kjrube however that still doesn't cause anything weird.

**Comment by CaerusKaru** [comment] 2018-04-16 21:13
Yeah I think we're going to close this one, especially because your reported issue is with v2.0.0-beta.12, which is at least 3 months out-of-date by now. Can you try upgrading to v5.0.0-beta.14 and see if that fixes anything?

**Closed by CaerusKaru** 2018-04-16 21:13 UTC

**Comment by DionisisKav** [comment] 2018-06-27 10:53
The error still exists. .I haven't find any way to reproduce it though.
I think it has to do with mediaQuery
`
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.7
@angular-devkit/build-angular     0.7.0-rc.0
@angular-devkit/build-optimizer   0.7.0-rc.0
@angular-devkit/build-webpack     0.7.0-rc.0
@angular-devkit/core              0.6.7
@angular-devkit/schematics        0.6.7
@angular/cdk                      6.3.0
@angular/cli                      6.0.7
@angular/flex-layout              6.0.0-beta.16
@angular/material                 6.3.0
@ngtools/webpack                  6.1.0-rc.0
@schematics/angular               0.6.7
@schematics/update                0.6.7
rxjs                              6.2.1
typescript                        2.7.2
webpack                           4.9.2
`
![image](https://user-images.githubusercontent.com/37541929/41969845-6d75ae62-7a11-11e8-9bc8-9cd725f55ec8.png)

**Comment by zlepper** [comment] 2018-08-20 10:58
If one of the "official" maintainers could send me an email address, then i have been allowed to share our internal code with said person, so they have a chance to debug this issue with an actual case, even if it's not a minimum reproduction.
