### ISSUE TITLE
fxHide or fxShow do not work in <ng-container> 

### ISSUE THREAD

**Issue by beleta** [angular/flex-layout#1262] opened 2020-05-20 15:10 UTC
# Bug Report

When using te directives fxHide or fxShow in a <ng-container> element inside a body template of a PrimeNG Table like this:

```
<table>
  <tr *pTemplate="'body'" ...>
    <td>...</td>
   ...
  <ng-container fxHide.lt-md>
     <td>...</td>
    ....
     <td>...</td>
  </ng-container>   
</table>
```
The following error is shown:

```
ERROR TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at Function.from (<anonymous>)
    at DefaultShowHideDirective.ngAfterViewInit (show-hide.ts:70)
```
#### What is the expected behavior?

No error shown.

#### What is the current behavior?

The error is shown.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

@angular/core: 9.1.7
@angular/cdk: 9.2.4
@angular/flex-layout: 9.0.0-beta.31

**Comment by CaerusKaru** [comment] 2020-05-21 19:44
@beleta Can you provide a StackBlitz or minimal GitHub repo to demo this? Preferably without PrimeNG but if it must have it then that's fine.

**Comment by beleta** [comment] 2020-05-28 10:56
I found that the problem does not depend on PrimeNg but simply on `<ng-container>`.

This is the StackBlitz project that shows the error: https://stackblitz.com/edit/angular-ivy-ecgfwk.

**Comment by MRMokwa** [comment] 2020-06-09 20:18
IMO it's not a bug, ng-container doesn't get renderered in the html, so the directives won't apply. Changing `ng-container` to a `div` will solve your problems. 
Obs:  Same thing will happen if you specify a class or style in the `ng-container`.

**Comment by beleta** [comment] 2020-06-10 09:55
> IMO it's not a bug, ng-container doesn't get renderered in the html, so the directives won't apply. Changing `ng-container` to a `div` will solve your problems.
> Obs: Same thing will happen if you specify a class or style in the `ng-container`.

I don't agree at all, `ng-container` is used for this kind of things because they don't add a DOM element as `div` do, for example ngIf works with no problem in this case, the following line works perfectly:

`<ng-container *ngIf="!mediaObserver.isActive('lt-md')">`

**Comment by CaerusKaru** [comment] 2020-06-15 23:26
@MRMokwa is correct, and thank you for that explanation! Closing as working as intended.

**Closed by CaerusKaru** 2020-06-15 23:26 UTC
Labels: P1, bug, needs:  demo
