### ISSUE TITLE
Build error after Angular & flexLayout upgrade - MediaQueryListEvent not assinable of type MediaQueryList

### ISSUE THREAD

**Issue by vijender1256** [angular/flex-layout#973] opened 2019-01-08 18:30 UTC
```
export class LayoutComponent implements OnInit, OnDestroy {

  private _router: Subscription;

  mediaMatcher: MediaQueryList = matchMedia(`(max-width: ${SMALL_WIDTH_BREAKPOINT}px)`);
  url: string;
  sidePanelOpened;

  constructor (
    private _element: ElementRef,
    private router: Router) {
    this.mediaMatcher.addListener(mql => zone.run(() => {
      this.mediaMatcher = mql; //i am getting error here Type 'MediaQueryListEvent' is not assignable to type 'MediaQueryList'.
                  //Property 'onchange' is missing in type 'MediaQueryListEvent'.
    }));
  }

  }
```
I upgraded to Angular 7.2 and "@angular/flex-layout": "^7.0.0-beta.22", I am getting build error "MediaQueryListEvent" is not assignable of type MediaQueryList. Is this issue exists with current version of flexLayout ?

**Comment by CaerusKaru** [comment] 2019-01-08 18:34
Duplicate of #861

**Closed by CaerusKaru** 2019-01-08 18:34 UTC

**Comment by vijender1256** [comment] 2019-01-08 20:12
@CaerusKaru As mentioned above , I am using Angular 7.2.0 & typescript 3.2.2 & @angular/flex-layout": "7.0.0-beta.22. The answer provided in issue #861 did not fix it for the above mentioned version, do you want us to downgrade the typescript and angular versions ? please help us out

**Comment by CaerusKaru** [comment] 2019-01-08 21:21
And I'm going to respond by saying that this is very much not a Flex Layout issue. It's likely you need to rebuild your dependencies. See #851 for the full story.
