### ISSUE TITLE
img src.xs stopped working in beta.20/21

### ISSUE THREAD

**Issue by anisabboud** [angular/flex-layout#984] opened 2019-01-13 09:36 UTC
# Bug Report

#### What is the expected behavior?

`<img src="big_image.png" src.xs="small_image.png">` should be responsive.
https://github.com/angular/flex-layout/wiki/imgSrc-API 

#### What is the current behavior?

This feature used to work well, but stopped working properly since beta.20/21.
When you make the window smaller, the image correctly switches to xs, but when you enlarge the window again, it doesn't switch back to the default image.

#### What are the steps to reproduce?

1. Open `app.component.html` in the default [StackBlitz starter](https://stackblitz.com/edit/angular-flex-layout-seed?file=app%2Fapp.component.html).
2. Add this on line 1:
`<img src="https://upload.wikimedia.org/wikipedia/commons/2/2f/Google_2015_logo.svg" src.xs="https://upload.wikimedia.org/wikipedia/commons/5/53/Google_%22G%22_Logo.svg">`
3. Try resizing the window - the image is responsive (with old flex-layout version).
4. Click the update dependencies button, and try again. Image stops being responsive.

#### Which versions of flex-layout are affected?

@angular/flex-layout@7.0.0-beta.19 (and earlier) 🡆 works perfectly
@angular/flex-layout@7.0.0-beta.20 🡆 img src.xs is completely broken
@angular/flex-layout@7.0.0-beta.21 (and later) 🡆 image shrinks but doesn't grow

**Comment by CaerusKaru** [comment] 2019-01-13 21:37
The workaround for now is to put the URLs in variables and assign it with box-syntax:

```html
<img [src]="defaultSrc" [src.xs]="xsSrc">
```

Still tracking the root cause.

**Comment by CaerusKaru** [comment] 2019-01-13 21:52
It turns out that we weren't correctly instantiating the fallback value on imgSrc. Whoops. Will have it patched in https://github.com/angular/flex-layout/pull/986

**Closed** 2019-01-13 22:52 UTC
Labels: P1, bug, has pr
