### ISSUE TITLE
ERROR in node_modules/@angular/flex-layout/media-query/breakpoints/break-points.d.ts(8,10): error TS2305

### ISSUE THREAD

**Issue by ykdevep** [angular/flex-layout#703] opened 2018-04-09 16:36 UTC
#### Bug, feature request, or proposal:
ERROR in node_modules/@angular/flex-layout/media-query/breakpoints/break-points.d.ts(8,10): error TS2305: Module '"/home/enrique/Escritorio/semeat/semeat/client/node_modules/@angular/core/core"' has no exported member 'OpaqueToken'.

#### What is the expected behavior?
When I use the client with ng serve dont work the compile proyect

#### What is the current behavior?
An unexpected error

#### What are the steps to reproduce?
Providing a StackBlitz (or similar) is the *best* way to get the team to see your issue.

*  [StackBlitz starter](https://goo.gl/y38GUZ) using latest `npm` nightly release:

**Comment by CaerusKaru** [comment] 2018-04-09 16:42
Duplicate of #494

**Comment by CaerusKaru** [comment] 2018-04-09 16:42
Upgrade to the 5.x version

**Closed by CaerusKaru** 2018-04-09 16:42 UTC
