### ISSUE TITLE
fxShow/fxHide is setting display: block on inline elements

### ISSUE THREAD

**Issue by adamdport** [angular/flex-layout#724] opened 2018-04-26 14:45 UTC
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?
`fxHide` shouldn't affect the original `display` of the element

#### What is the current behavior?
`fxHide` is sometimes setting `display:block;`

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-flex-layout-seed-8vay7o

#### What is the use-case or motivation for changing an existing behavior?
I sometimes want inline elements that hide at certain breakpoints

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
    "@angular/core": "5.2.9",
    "@angular/flex-layout": "5.0.0-beta.14",
    "@angular/material": "5.2.4",

#### Is there anything else we should know?
#320 fixed some instances of this behavior, but not all. Perhaps this is related to transclusion?

**Comment by CaerusKaru** [comment] 2018-04-26 14:52
Duplicate of #142?

**Comment by jotatoledo** [comment] 2018-05-14 22:41
Just noticed this issue, some `<span>` are now block components, which partially breaks some layouts.

**Comment by CaerusKaru** [comment] 2018-06-11 04:01
Oh I see the problem now. The fallback, ideally, should be blank. I'll try to get in a fix for this by beta 17

**Comment by FrancisS** [comment] 2018-09-07 20:41
Any progress on this? @CaerusKaru @ThomasBurleson

**Comment by FrancisS** [comment] 2018-10-01 19:09
If anyone is looking for a temp solution this is what we had to do

  @media (min-width: 1440px) {
    mat-header-cell,mat-cell{
      &[fxHide\.lt-lg]{
        display: flex !important;
      }
    }
  }
It sets the display to flex when the column is not hidden for a given breakpoint.
You will need separate rules for each breakpoint you use.

**Comment by adamdport** [comment] 2018-10-24 19:36
@CaerusKaru here's another reproduction using mat-table. The cells are supposed to be `display:flex`, but `fxHide` is setting them to `display:block`. Hope it helps. https://stackblitz.com/edit/angular-vpw5kv-r4td8o

**Comment by CaerusKaru** [comment] 2018-10-29 03:02
@aklauza Can you pull together a StackBlitz using your example? The only issue with @adamdport's examples are that they're all using Angular-defined elements, so it's tough to know what the defaults are supposed to be.

**Comment by CaerusKaru** [comment] 2018-11-10 20:05
I think I've got this patched in #881. Please build to make sure. If I don't hear back either way in the next week, I'll push it to the nightly builds (since it's not that far ahead of NPM, it shouldn't impact too many if it breaks something).

**Comment by adamdport** [comment] 2018-11-12 15:49
@CaerusKaru what's the simplest way to test a branch? It looks like the package name is `flex-layout-srcs` which is throwing me off. Do I need to clone it, change it back and install *that* or is there a simpler way?

**Comment by CaerusKaru** [comment] 2018-11-12 17:40
What I do is clone the branch, build the lib, and then run `npm install <src directory>` which would be `dist/releases/flex-layout` IIRC.

Or you can ask @srcn what they did in #848

**Closed** 2018-11-13 23:00 UTC
Labels: P1, bug, has pr
