### ISSUE TITLE
Angular 14 - error TS2420: Class 'MockMediaQueryList' incorrectly implements interface 'MediaQueryList'.   Property 'prototype' is missing in type 'MockMediaQueryList' but required in type 'MediaQueryList'.

### ISSUE THREAD

**Issue by jrayga** [angular/flex-layout#1423] opened 2022-10-11 02:02 UTC
# Bug Report

#### What is the current behavior? 

```ng serve``` build failed to compile. Shows error below

```
Error: node_modules/@angular/flex-layout/core/match-media/mock/mock-match-media.d.ts:59:22 - error TS2420: Class 'MockMediaQueryList' incorrectly implements interface 'MediaQueryList'.
  Property 'prototype' is missing in type 'MockMediaQueryList' but required in type 'MediaQueryList'.

59 export declare class MockMediaQueryList implements MediaQueryList {
                        ~~~~~~~~~~~~~~~~~~

  node_modules/typescript/lib/lib.dom.d.ts:5162:5
    5162     prototype: EventTarget;
             ~~~~~~~~~
    'prototype' is declared here.
```

#### What is the expected behavior?

Complete ng serve compile build

#### Which versions of Angular, Material, OS, TypeScript, and browsers are affected?

package.json below

```
{
"dependencies": {
    "@angular/animations": "~14.2.5",
    "@angular/cdk": "^14.2.4",
    "@angular/common": "~14.2.5",
    "@angular/compiler": "~14.2.5",
    "@angular/core": "~14.2.5",
    "@angular/flex-layout": "^14.0.0-beta.40",
    "@angular/forms": "~14.2.5",
    "@angular/material": "^14.2.4",
    "@angular/material-moment-adapter": "^14.2.4",
    "@angular/platform-browser": "~14.2.5",
    "@angular/platform-browser-dynamic": "~14.2.5",
    "@angular/router": "~14.2.5",
    "@ngrx/effects": "^14.3.2",
    "@ngrx/store": "^14.3.2",
    "@swimlane/ngx-charts": "^20.1.0",
    "jwt-decode": "^3.1.2",
    "lodash-es": "^4.17.21",
    "moment": "^2.29.4",
    "ngx-cookie-service": "^14.0.1",
    "ngx-mask": "^14.2.3",
    "ngx-mat-select-search": "^5.0.0",
    "ngx-pagination": "^6.0.2",
    "rxjs": "~7.5.7",
    "tslib": "^2.4.0",
    "zone.js": "~0.11.8"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~14.2.5",
    "@angular/cli": "~14.2.5",
    "@angular/compiler-cli": "~14.2.5",
    "@faker-js/faker": "^7.5.0",
    "@ngrx/schematics": "^14.3.2",
    "@types/jasmine": "~4.3.0",
    "@types/lodash-es": "^4.17.6",
    "@types/node": "^18.8.4",
    "@types/uuid": "^8.3.4",
    "jasmine-core": "~4.4.0",
    "karma": "~6.4.1",
    "karma-chrome-launcher": "~3.1.1",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.0.0",
    "typescript": "~4.8.4"
  }
}
```

**Comment by stockrel** [comment] 2022-10-11 07:38
+1

**Comment by apeter10** [comment] 2022-10-11 09:31
+1

**Comment by polterguy** [comment] 2022-10-11 10:21
+1

**Comment by StevenDieu** [comment] 2022-10-11 10:25
+1

**Comment by alexdaud** [comment] 2022-10-11 10:36
+1

**Comment by thecerber** [comment] 2022-10-11 11:01
I was helped the downgrade version of rxjs to 6.5.3

**Comment by burner** [comment] 2022-10-11 11:07
I got the hammer and added 	"skipLibCheck": true to the tsconfig.json to get it to work

**Comment by smarza** [comment] 2022-10-11 11:22
> I was helped the downgrade version of rxjs to 6.5.3

Downgrading the rxjs to 6.5.3 worked but it also changed a lot of import paths like filter and tap (rxjs) for example.
So, that´s not the ideal fix to my projects.

Appreciate your help.

**Comment by smarza** [comment] 2022-10-11 11:26
> 

Worked beautifully for now.

But, it concerns me because "skipLibCheck" will probably mask a lot of future issues.
So use with care. :)

For now, I´m going to enable skipLibCheck too.

Thanks a lot.

**Comment by burner** [comment] 2022-10-11 11:27
> But, it concerns me because "skipLibCheck" will probably mask a lot of future issues.

Yes, as soon as there is a patch for this on the flex-layout side, I'll will update to it and set skipLibCheck to false.

**Comment by CaerusKaru** [comment] 2022-10-11 15:25
I recognize this as a wide-reaching issue, I am not dismissing this. Unfortunately, I'm not able to reproduce this issue in our repo even with the exact dependencies listed. Can someone provide a minimal reproduction I can look into? If provided, this will be investigated expeditiously (but the repro must be minimal).

**Comment by marklbarlow** [comment] 2022-10-11 15:27
I'm pretty sure this is caused by:

`"@types/node": "^18.8.4"`

**Comment by aolszowka** [comment] 2022-10-11 15:29
@CaerusKaru Sorry for asking the obvious but did you clear out your `package-lock.json` before attempting to reproduce it? I believe its because many people (ourselves include) have floating dependencies and no `package-lock.json` (I know, a discussion for another time...). If you've done that I will work towards getting a minimal repro for you unless someone beats me to the punch.

**Comment by CaerusKaru** [comment] 2022-10-11 15:47
Tracking fix, will land in v14: https://github.com/angular/flex-layout/pull/1424

**Comment by tarlepp** [comment] 2022-10-11 17:25
Just faced this same issue - and looks like there is some work already done - great!

**Comment by VashJuan** [comment] 2022-10-11 19:26
Also reported as:
https://github.com/angular/angular/issues/47736
I'll put a note to refer to this issue...

**Comment by sumitsarraf** [comment] 2022-10-12 04:58
+1

**Comment by anisabboud** [comment] 2022-10-12 06:09
@CaerusKaru Thank you for the quick fix!!

Can the new version ([beta.41](https://github.com/angular/flex-layout/blob/master/CHANGELOG.md)) be published to [npm](https://www.npmjs.com/package/@angular/flex-layout)?

**Comment by polterguy** [comment] 2022-10-12 07:46
Thx guys and gals, finally [our stuff](https://aista.com/) is working again. I applied the `skipLibCheck` as a temporary fix and things are building ...

Note2self - Include the _"package-lock.json"_ file in the git repo ... :/

**Comment by CaerusKaru** [comment] 2022-10-12 18:41
v14.0.0-beta.41 has been released to NPM, please upgrade to that version. Unfortunately we will _not_ be backporting this patch to older, unsupported versions, so you have three options for mitigation on an older version:
1. Set `skipLibCheck` to `true` (this is my recommendation for really any project, regardless of circumstance)
2. Do not use Node v18 or its typings
3. Upgrade to latest

**Closed** 2023-05-05 01:41 UTC
Labels: has pr, P0
