### ISSUE TITLE
TypeError: Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by splincode** [angular/flex-layout#958] opened 2018-12-25 13:35 UTC
# Bug Report

#### What is the expected behavior?

```ts
const fixture = TestBed.createComponent(ConfirmDialogComponent);
fixture.detectChanges();
```

```ts
 TypeError: Cannot read property 'trim' of undefined

      at StyleUtils.Object.<anonymous>.StyleUtils.lookupStyle (node_modules/@angular/src/lib/core/style-utils/style-utils.ts:101:18)
      at DefaultLayoutGapDirective.Object.<anonymous>.LayoutGapDirective.willDisplay (node_modules/@angular/src/lib/flex/layout-gap/layout-gap.ts:207:40)
      at node_modules/@angular/src/lib/flex/layout-gap/layout-gap.ts:176:47
          at Array.filter (<anonymous>)
      at DefaultLayoutGapDirective.Object.<anonymous>.LayoutGapDirective.updateWithValue (node_modules/@angular/src/lib/flex/layout-gap/layout-gap.ts:176:8)
      at MediaMarshaller.Object.<anonymous>.MediaMarshaller.updateElement (node_modules/@angular/src/lib/core/media-marshaller/media-marshaller.ts:210:9)
      at MediaMarshaller.Object.<anonymous>.MediaMarshaller.setValue (node_modules/@angular/src/lib/core/media-marshaller/media-marshaller.ts:151:10)
      at DefaultLayoutGapDirective.Object.<anonymous>.BaseDirective2.setValue (node_modules/@angular/src/lib/core/base/base2.ts:144:18)
      at node_modules/@angular/src/lib/core/base/base2.ts:58:14
          at Array.forEach (<anonymous>)
      at DefaultLayoutGapDirective.Object.<anonymous>.BaseDirective2.ngOnChanges (node_modules/@angular/src/lib/core/base/base2.ts:54:26)
      at checkAndUpdateDirectiveInline (node_modules/@angular/core/bundles/npm_package.esm5/packages/core/packages/core/src/view/provider.ts:208:15)
      at checkAndUpdateNodeInline (node_modules/@angular/core/bundles/npm_package.esm5/packages/core/packages/core/src/view/view.ts:429:14)
      at checkAndUpdateNode (node_modules/@angular/core/bundles/npm_package.esm5/packages/core/packages/core/src/view/view.ts:389:12)
      at debugCheckAndUpdateNode (node_modules/@angular/core/bundles/npm_package.esm5/packages/core/packages/core/src/view/services.ts:432:44)
      at debugCheckDirectivesFn (node_modules/@angular/core/bundles/npm_package.esm5/packages/core/packages/core/src/view/services.ts:393:7)
      at Object.eval [as updateDirectives] (ng:/MaterialDevKitModule/ConfirmDialogComponent.ngfactory.js:63:5)
      at Object.debugUpdateDirectives [as updateDirectives] (node_modules/@angular/core/bundles/npm_package.esm5/packages/core/packages/core/src/view/services.ts:387:19)
      at checkAndUpdateView (node_modules/@angular/core/bundles/npm_package.esm5/packages/core/packages/core/src/view/view.ts:359:12)
      at callViewAction (node_modules/@angular/core/bundles/npm_package.esm5/packages/core/packages/core/src/view/view.ts:615:11)
      at execComponentViewsAction (node_modules/@angular/core/bundles/npm_package.esm5/packages/core/packages/core/src/view/view.ts:559:7)
      at checkAndUpdateView (node_modules/@angular/core/bundles/npm_package.esm5/packages/core/packages/core/src/view/view.ts:370:3)
      at callWithDebugContext (node_modules/@angular/core/bundles/npm_package.esm5/packages/core/packages/core/src/view/services.ts:652:23)
      at Object.debugCheckAndUpdateView [as checkAndUpdateView] (node_modules/@angular/core/bundles/npm_package.esm5/packages/core/packages/core/src/view/services.ts:348:10)
      at ViewRef_.Object.<anonymous>.ViewRef_.detectChanges (node_modules/@angular/core/bundles/npm_package.esm5/packages/core/packages/core/src/view/refs.ts:261:16)
      at ComponentFixture.Object.<anonymous>.ComponentFixture._tick (node_modules/@angular/core/bundles/npm_package.esm5/packages/packages/core/testing/src/component_fixture.ts:107:28)
      at node_modules/@angular/core/bundles/npm_package.esm5/packages/packages/core/testing/src/component_fixture.ts:120:36
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:388:26)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/proxy.js:128:39)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:387:32)
      at Object.onInvoke (node_modules/@angular/core/bundles/npm_package.esm5/packages/core/packages/core/src/zone/ng_zone.ts:273:25)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:387:32)
      at Zone.Object.<anonymous>.Zone.run (node_modules/zone.js/dist/zone.js:138:43)
      at NgZone.Object.<anonymous>.NgZone.run (node_modules/@angular/core/bundles/npm_package.esm5/packages/core/packages/core/src/zone/ng_zone.ts:171:50)
      at ComponentFixture.Object.<anonymous>.ComponentFixture.detectChanges (node_modules/@angular/core/bundles/npm_package.esm5/packages/packages/core/testing/src/component_fixture.ts:120:19)
      at Object.<anonymous> (src/app/shared/material-devkit/material-devkit.module.spec.ts:44:17)
      at step (src/app/shared/material-devkit/material-devkit.module.spec.ts:73:23)
      at Object.next (src/app/shared/material-devkit/material-devkit.module.spec.ts:40:20)
      at src/app/shared/material-devkit/material-devkit.module.spec.ts:24:71
      at new ZoneAwarePromise (node_modules/zone.js/dist/zone.js:891:29)
      at Object.<anonymous>.__awaiter (src/app/shared/material-devkit/material-devkit.module.spec.ts:4:12)
      at src/app/shared/material-devkit/material-devkit.module.spec.ts:39:50
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:388:26)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/proxy.js:128:39)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:387:32)
      at Zone.Object.<anonymous>.Zone.run (node_modules/zone.js/dist/zone.js:138:43)
      at Object.testBody.length (node_modules/jest-zone-patch/index.js:50:27)

```

```ts
<app-dialog>

  <ng-container class="dialog__title-content">
    title
  </ng-container>

  <ng-container class="dialog__body">
    <div fxLayout="row" fxLayoutAlign="center center" fxLayoutGap="10px">
      text
    </div>
  </ng-container>

</app-dialog>

```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

@angular/flex-layout - 7.0.0-beta.22

**Comment by CaerusKaru** [comment] 2018-12-25 13:41
Duplicate of #947

**Closed by CaerusKaru** 2018-12-25 13:41 UTC
