### ISSUE TITLE
Property media$ was marked as deprecated without any alternatives

### ISSUE THREAD

**Issue by belyan** [angular/flex-layout#1085] opened 2019-06-21 14:45 UTC
I use the following code for defined if current media is desktop.

```
isDesktop$ = this._mediaObserver.media$.pipe(
    map((mediaChange: MediaChange) => [ 'xs', 'sm' ].indexOf(mediaChange.mqAlias) === -1)
);
```

But in version **7.0.0-beta.24** property `media$` was deprecated. If I try to use method `asObservable` when I get array of media changes instead of one object. It doesn't suit me because I need to match a few values with one media change.

I could not find some examples in documentation. What I should to do to avoid of using deprecated property?

**Comment by CaerusKaru** [comment] 2019-07-04 01:01
Excellent question. I'm pretty sure @ThomasBurleson had the migration guide written. If not, we'll write one and add it to the Wiki before removing the API.

**Comment by Jemanuels** [comment] 2019-09-25 14:18
This is how I have used it:
     Subscription.asObservable()
      .pipe(
        filter((changes: MediaChange[]) => changes.length > 0),
        map((changes: MediaChange[]) => changes[0])
      )
      .subscribe((change: MediaChange) => {
        if (change.mqAlias === 'sm' || change.mqAlias === 'xs') {
          // do something
        } else {
          // do something else
        }
      });

**Comment by macure** [comment] 2020-05-05 11:43
Since the documentation is still not updated, I will just leave this here, maybe it will be helpful to someone.

What I found most useful for me is to include orientation breakpoints as well:
```ts
@NgModule({
  imports: [
   ...
    FlexLayoutModule.withConfig({ addOrientationBps: true }),
    ...
  ]
})
export class AppModule {}
```

Then in your component import `ScreenTypes` and compare `change.mediaQuery` with predefined screen types. Note that I've user [Array.prototype.some() ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some) to find at least one matching value and return boolean.
```ts
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { Component, OnInit } from '@angular/core';
import { MediaChange, MediaObserver, ScreenTypes } from '@angular/flex-layout';

@Component({
  selector: 'na-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss']
})
export class HeaderComponent implements OnInit {
  /** Is the device a hendset */
  public isHandset$: Observable<boolean>;

  constructor(private mediaObserver: MediaObserver) {}

  ngOnInit(): void {
    this.isHandset$ = this.mediaObserver
      .asObservable()
      .pipe(
        map((changes: MediaChange[]) =>
          changes.some(
            (change: MediaChange) => change.mediaQuery === ScreenTypes.HANDSET
          )
        )
      );
  }
}

```
in component template you can then do:
```html
<div *ngIf="isHandset$ | async">This visible on Mobile</div>
```

**Comment by CaerusKaru** [comment] 2020-05-09 22:42
Duplicate of #1040

**Closed by CaerusKaru** 2020-05-09 22:42 UTC
Labels: P4, docs
