### ISSUE TITLE
FlexLayout for non-angular projects

### ISSUE THREAD

**Issue by st-clair-clarke** [angular/flex-layout#1223] opened 2020-03-26 10:44 UTC
# Flex-layout for non-angular projects

#### Is there anything else we should know? I use angular flex-layout in my angular project. I would also like to use it in my non-angular projects. I see this article [Possible? Use of "flex-layout" in non angular environments. #717](https://github.com/angular/flex-layout/issues/717). However I cannot find it on the site. Is there a link for downloading it? Or has it evolved into another name.

Thanks

**Comment by CaerusKaru** [comment] 2020-03-26 13:23
The issue mentions that it’s experimental on the adam/ce branch. You have to clone the repo and checkout that branch. However it hasn’t been updated in some time.

In the meantime, I’m closing this issue as a duplicate of #717. Any updates will be posted there.

**Closed by CaerusKaru** 2020-03-26 13:23 UTC
