### ISSUE TITLE
ERROR TypeError: Cannot read property 'init' of undefined

### ISSUE THREAD

**Issue by perjerz3434** [angular/flex-layout#959] opened 2018-12-26 04:44 UTC
# Bug Report
After update ng update to @angular/flex-layout@7.0.0-beta.22 from beta.19
And after try beta.22, 21, 20 still gets error

#### What is the expected behavior?
To work well, No error

#### What is the current behavior?
ng serve
Error
![image](https://user-images.githubusercontent.com/5865946/50432275-49401880-0903-11e9-8cd8-6068dcd1d652.png)
![image](https://user-images.githubusercontent.com/5865946/50432357-bbb0f880-0903-11e9-975c-275f5542550d.png)
Callstack
![image](https://user-images.githubusercontent.com/5865946/50432366-cd929b80-0903-11e9-956c-492d9ae3c371.png)

#### What are the steps to reproduce?
Providing a StackBlitz (or similar) is the *best* way to get the team to see your issue.
https://github.com/AngularThailand/who-use-angular-in-thailand 
update angular/flex-layout to latest

*  [StackBlitz starter](https://goo.gl/y38GUZ) using latest `npm` nightly release: 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
```
Angular CLI: 7.1.4
Node: 8.9.4
OS: darwin x64
Angular: 7.1.4
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.10.7
@angular-devkit/build-angular      0.10.7
@angular-devkit/build-ng-packagr   0.10.7
@angular-devkit/build-optimizer    0.10.7
@angular-devkit/build-webpack      0.10.7
@angular-devkit/core               7.0.7
@angular-devkit/schematics         7.0.7
@angular/cdk                       7.2.0
@angular/flex-layout               7.0.0-beta.20
@angular/material                  7.2.0
@angular/pwa                       0.10.7
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.0.7
@schematics/angular                7.0.7
@schematics/update                 0.11.4
ng-packagr                         4.4.5
rxjs                               6.3.3
typescript                         3.1.6
webpack                            4.28.2
```

#### Is there anything else we should know?
When downgrade to beta.19, it works correctly.

**Comment by CaerusKaru** [comment] 2018-12-26 04:52
Duplicate of #950

**Closed by CaerusKaru** 2018-12-26 04:52 UTC

**Comment by RUPALAVECINO** [comment] 2019-03-20 12:14
No encuentro la solución
